from __future__ import annotations

from pathlib import Path
from typing import Any, Dict

from app.labint_frontmatter_batch_restore_utils import (
    apply_frontmatter_batch_generic,
    load_abbreviation_seeds,
    load_family_pattern_seeds,
    load_page_knowledge_seeds,
)

FRONTMATTER_BATCH46_VERSION = 'labint_frontmatter_batch46_v1_20260412'
SOURCE_LABEL = 'named_reactions_frontmatter_batch46'
LATEST_SOURCE_ZIP = 'backend_batch15_46_frontmatter_cumulative_patch_20260412.zip'

PAGE_KNOWLEDGE_SEEDS = load_page_knowledge_seeds(46, SOURCE_LABEL)
FAMILY_PATTERN_SEEDS = load_family_pattern_seeds(46, FRONTMATTER_BATCH46_VERSION)
BATCH46_SOURCE_PAGES = {
 "Cp2ZrHCl": 400,
 "n-BuNC": 401,
 "Ni(COD)2": 401,
 "Ti(O-iPr)4": 408,
 "D-(-)-DET": 408,
 "L-(+)-DET": 409,
 "AD-mix α": 406,
 "AD-mix β": 406,
 "K2OsO2(OH)4": 404,
 "K3Fe(CN)6": 407
}
CURATED_BATCH46_ABBREVIATIONS = load_abbreviation_seeds(
    46,
    SOURCE_LABEL,
    source_pages=BATCH46_SOURCE_PAGES,
    default_note='batch46 frontmatter abbreviation seed',
)
PAGE_ENTITY_SEEDS = [{'page_label': 'p400',
  'entity_text': 'Schwartz Hydrozirconation',
  'canonical_name': 'Schwartz Hydrozirconation',
  'entity_type': 'reaction_family',
  'family_name': 'Schwartz Hydrozirconation',
  'notes': 'Overview page family anchor for Schwartz hydrozirconation.',
  'confidence': 0.93},
 {'page_label': 'p400',
  'entity_text': 'Cp2ZrHCl',
  'canonical_name': 'zirconocene hydrochloride',
  'entity_type': 'abbreviation',
  'family_name': 'Schwartz Hydrozirconation',
  'notes': 'Classical Schwartz reagent used for hydrozirconation of alkenes and alkynes.',
  'confidence': 0.91},
 {'page_label': 'p400',
  'entity_text': 'alkene',
  'canonical_name': None,
  'entity_type': 'reactant_class',
  'family_name': 'Schwartz Hydrozirconation',
  'notes': 'Alkene substrates are hydrozirconated in a syn fashion to give alkylzirconium species.',
  'confidence': 0.85},
 {'page_label': 'p400',
  'entity_text': 'alkyne',
  'canonical_name': None,
  'entity_type': 'reactant_class',
  'family_name': 'Schwartz Hydrozirconation',
  'notes': 'Alkynes are hydrozirconated to vinylzirconium intermediates.',
  'confidence': 0.85},
 {'page_label': 'p400',
  'entity_text': 'alkyl- or alkenylzirconium intermediate',
  'canonical_name': None,
  'entity_type': 'intermediate_class',
  'family_name': 'Schwartz Hydrozirconation',
  'notes': 'Signature organozirconium intermediate generated on the overview page.',
  'confidence': 0.86},
 {'page_label': 'p401',
  'entity_text': '(+)-Curacin A',
  'canonical_name': '(+)-Curacin A',
  'entity_type': 'target_molecule',
  'family_name': 'Schwartz Hydrozirconation',
  'notes': 'Target featuring hydrozirconation/electrophile trapping in side-chain assembly.',
  'confidence': 0.86},
 {'page_label': 'p401',
  'entity_text': 'Apoptolidin',
  'canonical_name': 'Apoptolidin',
  'entity_type': 'target_molecule',
  'family_name': 'Schwartz Hydrozirconation',
  'notes': 'Natural product fragment synthesis featuring selective hydrozirconation/trapping of a vinyl '
           'iodide precursor.',
  'confidence': 0.85},
 {'page_label': 'p401',
  'entity_text': 'isodomoic acid G',
  'canonical_name': 'isodomoic acid G',
  'entity_type': 'target_molecule',
  'family_name': 'Schwartz Hydrozirconation',
  'notes': 'The pyrrolidinone core was assembled through tandem hydrozirconation/transmetalation chemistry.',
  'confidence': 0.84},
 {'page_label': 'p401',
  'entity_text': 'n-BuNC',
  'canonical_name': 'n-butyl isocyanide',
  'entity_type': 'abbreviation',
  'family_name': 'Schwartz Hydrozirconation',
  'notes': 'Electrophile trap used after hydrozirconation of the curacin polyene precursor.',
  'confidence': 0.9},
 {'page_label': 'p401',
  'entity_text': 'Ni(COD)2',
  'canonical_name': 'bis(1,5-cyclooctadiene)nickel(0)',
  'entity_type': 'abbreviation',
  'family_name': 'Schwartz Hydrozirconation',
  'notes': 'Nickel catalyst used after hydrozirconation/transmetalation in the isodomoic acid G example.',
  'confidence': 0.9},
 {'page_label': 'p402',
  'entity_text': 'Seyferth-Gilbert Homologation',
  'canonical_name': 'Seyferth-Gilbert Homologation',
  'entity_type': 'reaction_family',
  'family_name': 'Seyferth-Gilbert Homologation',
  'notes': 'Overview page family anchor for the Seyferth-Gilbert homologation.',
  'confidence': 0.93},
 {'page_label': 'p402',
  'entity_text': 'Ohira-Bestmann protocol',
  'canonical_name': 'Ohira-Bestmann homologation',
  'entity_type': 'named_variant',
  'family_name': 'Seyferth-Gilbert Homologation',
  'notes': 'Modified diazophosphonate protocol for mild aldehyde-to-terminal alkyne homologation.',
  'confidence': 0.88},
 {'page_label': 'p402',
  'entity_text': 'diazophosphonate reagent',
  'canonical_name': None,
  'entity_type': 'reagent_class',
  'family_name': 'Seyferth-Gilbert Homologation',
  'notes': 'Carbonyl homologation reagent class that delivers alkynes under basic conditions.',
  'confidence': 0.84},
 {'page_label': 'p402',
  'entity_text': 'terminal alkyne',
  'canonical_name': None,
  'entity_type': 'product_class',
  'family_name': 'Seyferth-Gilbert Homologation',
  'notes': 'Characteristic product from aldehydes under Ohira-Bestmann conditions.',
  'confidence': 0.86},
 {'page_label': 'p402',
  'entity_text': 'internal alkyne',
  'canonical_name': None,
  'entity_type': 'product_class',
  'family_name': 'Seyferth-Gilbert Homologation',
  'notes': 'Product class from ketones or non-aldehydic carbonyl substrates in the classical protocol.',
  'confidence': 0.84},
 {'page_label': 'p403',
  'entity_text': 'Polycavernoside A',
  'canonical_name': 'Polycavernoside A',
  'entity_type': 'target_molecule',
  'family_name': 'Seyferth-Gilbert Homologation',
  'notes': 'Marine toxin whose side-chain aldehyde was homologated to a terminal alkyne before elaboration.',
  'confidence': 0.85},
 {'page_label': 'p403',
  'entity_text': '(-)-Minquartynoic acid',
  'canonical_name': '(-)-Minquartynoic acid',
  'entity_type': 'target_molecule',
  'family_name': 'Seyferth-Gilbert Homologation',
  'notes': 'Polyacetylenic natural product assembled using a modified Seyferth-Gilbert homologation step.',
  'confidence': 0.85},
 {'page_label': 'p403',
  'entity_text': 'C5-C20 subunit of the aplyronines',
  'canonical_name': None,
  'entity_type': 'target_scaffold',
  'family_name': 'Seyferth-Gilbert Homologation',
  'notes': 'Subunit accessed through carbonyl homologation to the corresponding alkyne.',
  'confidence': 0.83},
 {'page_label': 'p403',
  'entity_text': '(-)-Laulimalide',
  'canonical_name': '(-)-Laulimalide',
  'entity_type': 'target_molecule',
  'family_name': 'Seyferth-Gilbert Homologation',
  'notes': 'Late-stage use of modified Seyferth-Gilbert homologation in total synthesis of laulimalide.',
  'confidence': 0.84},
 {'page_label': 'p404',
  'entity_text': 'Sharpless Asymmetric Aminohydroxylation',
  'canonical_name': 'Sharpless Asymmetric Aminohydroxylation',
  'entity_type': 'reaction_family',
  'family_name': 'Sharpless Asymmetric Aminohydroxylation',
  'notes': 'Overview page family anchor for Sharpless asymmetric aminohydroxylation.',
  'confidence': 0.93},
 {'page_label': 'p404',
  'entity_text': 'enantiopure cis aminoalcohol',
  'canonical_name': None,
  'entity_type': 'product_class',
  'family_name': 'Sharpless Asymmetric Aminohydroxylation',
  'notes': 'Characteristic product class of the Sharpless aminohydroxylation.',
  'confidence': 0.86},
 {'page_label': 'p404',
  'entity_text': 'K2OsO2(OH)4',
  'canonical_name': 'potassium osmate dihydrate',
  'entity_type': 'abbreviation',
  'family_name': 'Sharpless Asymmetric Aminohydroxylation',
  'notes': 'Catalytic osmium source shown on the overview page.',
  'confidence': 0.9},
 {'page_label': 'p404',
  'entity_text': '(DHQD)2PHAL',
  'canonical_name': 'bis(dihydroquinidino)phthalazine',
  'entity_type': 'abbreviation',
  'family_name': 'Sharpless Asymmetric Aminohydroxylation',
  'notes': 'Chiral ligand used for asymmetric induction in Sharpless aminohydroxylation.',
  'confidence': 0.89},
 {'page_label': 'p404',
  'entity_text': 'nitrogen source',
  'canonical_name': None,
  'entity_type': 'reagent_class',
  'family_name': 'Sharpless Asymmetric Aminohydroxylation',
  'notes': 'N-halo carbamates or chloramine equivalents that deliver the amino functionality.',
  'confidence': 0.83},
 {'page_label': 'p405',
  'entity_text': 'Ustiloxin D',
  'canonical_name': 'Ustiloxin D',
  'entity_type': 'target_molecule',
  'family_name': 'Sharpless Asymmetric Aminohydroxylation',
  'notes': 'Natural product accessed via Sharpless regio-reversed aminohydroxylation of a cinnamate '
           'derivative.',
  'confidence': 0.85},
 {'page_label': 'p405',
  'entity_text': 'Dragmacidin A',
  'canonical_name': 'Dragmacidin A',
  'entity_type': 'target_molecule',
  'family_name': 'Sharpless Asymmetric Aminohydroxylation',
  'notes': 'Bisindole alkaloid precursor prepared from a vinyl indole through asymmetric aminohydroxylation.',
  'confidence': 0.85},
 {'page_label': 'p405',
  'entity_text': 'Teicoplanin aglycone',
  'canonical_name': 'Teicoplanin aglycone',
  'entity_type': 'target_molecule',
  'family_name': 'Sharpless Asymmetric Aminohydroxylation',
  'notes': 'G- and F-ring phenylglycinol precursors were prepared using Sharpless aminohydroxylation.',
  'confidence': 0.85},
 {'page_label': 'p405',
  'entity_text': '(-)-Ephedradine A',
  'canonical_name': '(-)-Ephedradine A',
  'entity_type': 'target_molecule',
  'family_name': 'Sharpless Asymmetric Aminohydroxylation',
  'notes': 'Alkaloid target whose benzylic amino alcohol stereochemistry was set by Sharpless '
           'aminohydroxylation.',
  'confidence': 0.84},
 {'page_label': 'p406',
  'entity_text': 'Sharpless Asymmetric Dihydroxylation',
  'canonical_name': 'Sharpless Asymmetric Dihydroxylation',
  'entity_type': 'reaction_family',
  'family_name': 'Sharpless Asymmetric Dihydroxylation',
  'notes': 'Overview page family anchor for Sharpless asymmetric dihydroxylation.',
  'confidence': 0.93},
 {'page_label': 'p406',
  'entity_text': 'AD-mix α',
  'canonical_name': 'Sharpless AD-mix alpha',
  'entity_type': 'abbreviation',
  'family_name': 'Sharpless Asymmetric Dihydroxylation',
  'notes': 'Premixed reagent set delivering one enantiomer of the cis vicinal diol product.',
  'confidence': 0.91},
 {'page_label': 'p406',
  'entity_text': 'AD-mix β',
  'canonical_name': 'Sharpless AD-mix beta',
  'entity_type': 'abbreviation',
  'family_name': 'Sharpless Asymmetric Dihydroxylation',
  'notes': 'Complementary premixed reagent set for the opposite cis vicinal diol enantiomer.',
  'confidence': 0.91},
 {'page_label': 'p406',
  'entity_text': 'cis vicinal diol',
  'canonical_name': None,
  'entity_type': 'product_class',
  'family_name': 'Sharpless Asymmetric Dihydroxylation',
  'notes': 'Characteristic syn dihydroxylation product depicted on the overview page.',
  'confidence': 0.87},
 {'page_label': 'p406',
  'entity_text': '(DHQ)2PHAL',
  'canonical_name': 'bis(dihydroquinino)phthalazine',
  'entity_type': 'abbreviation',
  'family_name': 'Sharpless Asymmetric Dihydroxylation',
  'notes': 'Pseudoeenantiomeric ligand for the complementary AD-mix reagent set.',
  'confidence': 0.88},
 {'page_label': 'p407',
  'entity_text': '(+)-Zaragozic acid C',
  'canonical_name': '(+)-Zaragozic acid C',
  'entity_type': 'target_molecule',
  'family_name': 'Sharpless Asymmetric Dihydroxylation',
  'notes': 'Double Sharpless dihydroxylation sequence used to establish multiple contiguous stereocenters.',
  'confidence': 0.85},
 {'page_label': 'p407',
  'entity_text': 'KDO',
  'canonical_name': '3-deoxy-D-manno-2-octulosonic acid',
  'entity_type': 'target_molecule',
  'family_name': 'Sharpless Asymmetric Dihydroxylation',
  'notes': 'Carbohydrate acid target obtained after dihydroxylation of a vinyl dihydropyran precursor.',
  'confidence': 0.84},
 {'page_label': 'p407',
  'entity_text': '(+)-1-Epiaustraline',
  'canonical_name': '(+)-1-Epiaustraline',
  'entity_type': 'target_molecule',
  'family_name': 'Sharpless Asymmetric Dihydroxylation',
  'notes': 'Tetrahydroxypyrrolizidine alkaloid prepared through terminal-olefin dihydroxylation.',
  'confidence': 0.84},
 {'page_label': 'p407',
  'entity_text': 'K3Fe(CN)6',
  'canonical_name': 'potassium ferricyanide',
  'entity_type': 'abbreviation',
  'family_name': 'Sharpless Asymmetric Dihydroxylation',
  'notes': 'Reoxidant present in AD-mix reagent systems and shown in application conditions.',
  'confidence': 0.89},
 {'page_label': 'p408',
  'entity_text': 'Sharpless Asymmetric Epoxidation',
  'canonical_name': 'Sharpless Asymmetric Epoxidation',
  'entity_type': 'reaction_family',
  'family_name': 'Sharpless Asymmetric Epoxidation',
  'notes': 'Overview page family anchor for Sharpless asymmetric epoxidation.',
  'confidence': 0.93},
 {'page_label': 'p408',
  'entity_text': 'allylic alcohol',
  'canonical_name': None,
  'entity_type': 'reactant_class',
  'family_name': 'Sharpless Asymmetric Epoxidation',
  'notes': 'Required substrate class for the titanium-tartrate epoxidation manifold.',
  'confidence': 0.87},
 {'page_label': 'p408',
  'entity_text': 'epoxy alcohol',
  'canonical_name': None,
  'entity_type': 'product_class',
  'family_name': 'Sharpless Asymmetric Epoxidation',
  'notes': 'Canonical product obtained after enantioselective epoxidation of allylic alcohols.',
  'confidence': 0.88},
 {'page_label': 'p408',
  'entity_text': 'Ti(O-iPr)4',
  'canonical_name': 'titanium tetraisopropoxide',
  'entity_type': 'abbreviation',
  'family_name': 'Sharpless Asymmetric Epoxidation',
  'notes': 'Titanium alkoxide catalyst precursor used in the Sharpless epoxidation system.',
  'confidence': 0.91},
 {'page_label': 'p408',
  'entity_text': 'TBHP',
  'canonical_name': 'tert-butyl hydroperoxide',
  'entity_type': 'abbreviation',
  'family_name': 'Sharpless Asymmetric Epoxidation',
  'notes': 'Terminal oxidant used in the Sharpless epoxidation manifold.',
  'confidence': 0.9},
 {'page_label': 'p408',
  'entity_text': 'D-(-)-DET',
  'canonical_name': 'D-(-)-diethyl tartrate',
  'entity_type': 'abbreviation',
  'family_name': 'Sharpless Asymmetric Epoxidation',
  'notes': 'One tartrate ligand enantiomer used to control epoxide facial selectivity.',
  'confidence': 0.9},
 {'page_label': 'p408',
  'entity_text': 'L-(+)-DET',
  'canonical_name': 'L-(+)-diethyl tartrate',
  'entity_type': 'abbreviation',
  'family_name': 'Sharpless Asymmetric Epoxidation',
  'notes': 'Pseudoeenantiomeric tartrate ligand used for the opposite epoxide enantiomer.',
  'confidence': 0.9},
 {'page_label': 'p409',
  'entity_text': '(+)-Parviflorin',
  'canonical_name': '(+)-Parviflorin',
  'entity_type': 'target_molecule',
  'family_name': 'Sharpless Asymmetric Epoxidation',
  'notes': 'Annonaceous acetogenin synthesized with sequential Sharpless asymmetric epoxidation and '
           'dihydroxylation.',
  'confidence': 0.85},
 {'page_label': 'p409',
  'entity_text': '(20R)-Homocamptothecin',
  'canonical_name': '(20R)-Homocamptothecin',
  'entity_type': 'target_molecule',
  'family_name': 'Sharpless Asymmetric Epoxidation',
  'notes': 'Target whose C20 stereocenter was set by Sharpless asymmetric epoxidation.',
  'confidence': 0.85},
 {'page_label': 'p409',
  'entity_text': '(-)-Laulimalide',
  'canonical_name': '(-)-Laulimalide',
  'entity_type': 'target_molecule',
  'family_name': 'Sharpless Asymmetric Epoxidation',
  'notes': 'Macrocyclic diol selectively epoxidized under Sharpless conditions to install the C16-C17 '
           'epoxide.',
  'confidence': 0.85},
 {'page_label': 'p409',
  'entity_text': '(+)-Madindoline A',
  'canonical_name': '(+)-Madindoline A',
  'entity_type': 'target_molecule',
  'family_name': 'Sharpless Asymmetric Epoxidation',
  'notes': 'One of the Madindoline natural products accessed through indole double-bond Sharpless '
           'epoxidation.',
  'confidence': 0.84},
 {'page_label': 'p409',
  'entity_text': '(-)-Madindoline B',
  'canonical_name': '(-)-Madindoline B',
  'entity_type': 'target_molecule',
  'family_name': 'Sharpless Asymmetric Epoxidation',
  'notes': 'Companion Madindoline natural product produced in the same Sharpless epoxidation sequence.',
  'confidence': 0.84},
 {'page_label': 'p409',
  'entity_text': 'DIPT',
  'canonical_name': 'diisopropyl tartrate',
  'entity_type': 'abbreviation',
  'family_name': 'Sharpless Asymmetric Epoxidation',
  'notes': 'Tartrate ligand abbreviation appearing in the laulimalide application example.',
  'confidence': 0.87}]

def apply_frontmatter_batch46(db_path: str | Path) -> Dict[str, Any]:
    return apply_frontmatter_batch_generic(
        db_path=db_path,
        source_label=SOURCE_LABEL,
        version=FRONTMATTER_BATCH46_VERSION,
        latest_source_zip=LATEST_SOURCE_ZIP,
        batch_no=46,
        page_knowledge_seeds=PAGE_KNOWLEDGE_SEEDS,
        family_pattern_seeds=FAMILY_PATTERN_SEEDS,
        abbreviation_seeds=CURATED_BATCH46_ABBREVIATIONS,
        page_entity_seeds=PAGE_ENTITY_SEEDS,
        replace_existing_page_entities=False,
    )
