from __future__ import annotations

from pathlib import Path
from typing import Any, Dict

from app.labint_frontmatter_batch_restore_utils import (
    apply_frontmatter_batch_generic,
    load_abbreviation_seeds,
    load_family_pattern_seeds,
    load_page_knowledge_seeds,
)

FRONTMATTER_BATCH42_VERSION = 'labint_frontmatter_batch42_v1_20260412'
SOURCE_LABEL = 'named_reactions_frontmatter_batch42'
LATEST_SOURCE_ZIP = 'backend_batch15_42_frontmatter_cumulative_patch_20260412.zip'

PAGE_KNOWLEDGE_SEEDS = load_page_knowledge_seeds(42, SOURCE_LABEL)
FAMILY_PATTERN_SEEDS = load_family_pattern_seeds(42, FRONTMATTER_BATCH42_VERSION)
BATCH42_SOURCE_PAGES = {'AgOAc': 361,
 'AgOBz': 360,
 'Me2AlCl': 365,
 'OTIPS': 363,
 'PhCO2Ag': 360,
 'Raney-Ni': 369,
 'TMSNEt2': 369,
 'sym-collidine': 369}
CURATED_BATCH42_ABBREVIATIONS = load_abbreviation_seeds(
    42,
    SOURCE_LABEL,
    source_pages=BATCH42_SOURCE_PAGES,
    default_note='batch42 frontmatter abbreviation seed',
)
PAGE_ENTITY_SEEDS = [{'canonical_name': 'Prévost Reaction',
  'confidence': 0.92,
  'entity_text': 'Prévost Reaction',
  'entity_type': 'reaction_family',
  'family_name': 'Prévost Reaction',
  'notes': 'Overview page family anchor for the Prévost reaction.',
  'page_label': 'p360'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'alkene + iodine + silver carboxylate',
  'entity_type': 'reactant_class',
  'family_name': 'Prévost Reaction',
  'notes': 'Canonical reagent set for the Prévost anti-dihydroxylation manifold.',
  'page_label': 'p360'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'trans-1,2-diol',
  'entity_type': 'product_class',
  'family_name': 'Prévost Reaction',
  'notes': 'Characteristic product under anhydrous Prévost conditions.',
  'page_label': 'p360'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'cis-1,2-diol via Woodward-Brutcher modification',
  'entity_type': 'product_class',
  'family_name': 'Prévost Reaction',
  'notes': 'Characteristic vicinal diol outcome when water or acetic acid diverts the common '
           'intermediate.',
  'page_label': 'p360'},
 {'canonical_name': 'Prévost Reaction',
  'confidence': 0.92,
  'entity_text': 'Prévost Reaction',
  'entity_type': 'reaction_family',
  'family_name': 'Prévost Reaction',
  'notes': 'Application page family anchor.',
  'page_label': 'p361'},
 {'canonical_name': '1,7,8-Trihydroxy-trans-7,8-dihydrobenzo[a]pyrene',
  'confidence': 0.85,
  'entity_text': '1,7,8-Trihydroxy-trans-7,8-dihydrobenzo[a]pyrene',
  'entity_type': 'target_molecule',
  'family_name': 'Prévost Reaction',
  'notes': 'Phenolic benzo[a]pyrene derivative prepared through dry Prévost dihydroxylation.',
  'page_label': 'p361'},
 {'canonical_name': '(-)-SS20846A',
  'confidence': 0.85,
  'entity_text': '(-)-SS20846A',
  'entity_type': 'target_molecule',
  'family_name': 'Prévost Reaction',
  'notes': 'Antibacterial piperidine natural product featuring a hydroxyl group installed by a '
           'Prévost sequence.',
  'page_label': 'p361'},
 {'canonical_name': '(±)-Momilactone A',
  'confidence': 0.84,
  'entity_text': '(±)-Momilactone A',
  'entity_type': 'target_molecule',
  'family_name': 'Prévost Reaction',
  'notes': 'Natural product whose β-keto acid precursor underwent Prévost chemistry before later '
           'lactonization.',
  'page_label': 'p361'},
 {'canonical_name': '(±)-2,3-Dihydrofratiglisin C',
  'confidence': 0.84,
  'entity_text': '(±)-2,3-Dihydrofratiglisin C',
  'entity_type': 'target_molecule',
  'family_name': 'Prévost Reaction',
  'notes': 'Woodward-Brutcher example delivering a cis-vicinal diol in a complex sesquiterpene '
           'framework.',
  'page_label': 'p361'},
 {'canonical_name': 'Prilezhaev Reaction',
  'confidence': 0.92,
  'entity_text': 'Prilezhaev Reaction',
  'entity_type': 'reaction_family',
  'family_name': 'Prilezhaev Reaction',
  'notes': 'Overview page family anchor for peroxyacid epoxidation chemistry.',
  'page_label': 'p362'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'alkene + peroxyacid',
  'entity_type': 'reactant_class',
  'family_name': 'Prilezhaev Reaction',
  'notes': 'Canonical substrate pair for the Prilezhaev epoxidation.',
  'page_label': 'p362'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'epoxide retaining alkene geometry',
  'entity_type': 'product_class',
  'family_name': 'Prilezhaev Reaction',
  'notes': 'Characteristic stereospecific product of peroxyacid epoxidation.',
  'page_label': 'p362'},
 {'canonical_name': 'meta-chloroperoxybenzoic acid',
  'confidence': 0.9,
  'entity_text': 'mCPBA',
  'entity_type': 'abbreviation',
  'family_name': 'Prilezhaev Reaction',
  'notes': 'Common peracid reagent highlighted repeatedly on the overview page.',
  'page_label': 'p362'},
 {'canonical_name': 'Prilezhaev Reaction',
  'confidence': 0.92,
  'entity_text': 'Prilezhaev Reaction',
  'entity_type': 'reaction_family',
  'family_name': 'Prilezhaev Reaction',
  'notes': 'Application page family anchor.',
  'page_label': 'p363'},
 {'canonical_name': '(-)-21-Isopentenylpaxilline',
  'confidence': 0.85,
  'entity_text': '(-)-21-Isopentenylpaxilline',
  'entity_type': 'target_molecule',
  'family_name': 'Prilezhaev Reaction',
  'notes': 'Complex tetracyclic lactone substrate epoxidized diastereoselectively with mCPBA.',
  'page_label': 'p363'},
 {'canonical_name': 'Briarielin F',
  'confidence': 0.85,
  'entity_text': 'Briarielin F',
  'entity_type': 'target_molecule',
  'family_name': 'Prilezhaev Reaction',
  'notes': 'Briarane diterpene reached through selective α-epoxidation in the presence of a '
           'terminal alkyne.',
  'page_label': 'p363'},
 {'canonical_name': '11-Deoxytetrodotoxin',
  'confidence': 0.85,
  'entity_text': '11-Deoxytetrodotoxin',
  'entity_type': 'target_molecule',
  'family_name': 'Prilezhaev Reaction',
  'notes': 'Target whose six-membered cyclic allylic alcohol was epoxidized in near-quantitative '
           'yield.',
  'page_label': 'p363'},
 {'canonical_name': 'Epothilone B',
  'confidence': 0.85,
  'entity_text': 'Epothilone B',
  'entity_type': 'target_molecule',
  'family_name': 'Prilezhaev Reaction',
  'notes': 'Natural product obtained after highly diastereoselective epoxidation of epothilone D.',
  'page_label': 'p363'},
 {'canonical_name': 'Prins Reaction',
  'confidence': 0.92,
  'entity_text': 'Prins Reaction',
  'entity_type': 'reaction_family',
  'family_name': 'Prins Reaction',
  'notes': 'Overview page family anchor for the Prins reaction.',
  'page_label': 'p364'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'alkene + aldehyde under protic or Lewis acid',
  'entity_type': 'reactant_class',
  'family_name': 'Prins Reaction',
  'notes': 'Canonical input set for Prins-type oxocarbenium chemistry.',
  'page_label': 'p364'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': '1,3-dioxane or 3-substituted alcohol',
  'entity_type': 'product_class',
  'family_name': 'Prins Reaction',
  'notes': 'Common product classes formed after carbocation capture in a Prins reaction.',
  'page_label': 'p364'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'allylic alcohol or 1,3-diol by-product',
  'entity_type': 'product_class',
  'family_name': 'Prins Reaction',
  'notes': 'Alternative outcomes accessible from the same oxocarbenium manifold.',
  'page_label': 'p364'},
 {'canonical_name': 'Prins Reaction',
  'confidence': 0.92,
  'entity_text': 'Prins Reaction',
  'entity_type': 'reaction_family',
  'family_name': 'Prins Reaction',
  'notes': 'Application page family anchor.',
  'page_label': 'p365'},
 {'canonical_name': '(+)-Chatancin',
  'confidence': 0.85,
  'entity_text': '(+)-Chatancin',
  'entity_type': 'target_molecule',
  'family_name': 'Prins Reaction',
  'notes': 'Biomimetic total synthesis target prepared using a Prins reaction on a trans-trans '
           'farnesol-derived substrate.',
  'page_label': 'p365'},
 {'canonical_name': 'Leucascandrolide A',
  'confidence': 0.85,
  'entity_text': 'Leucascandrolide A',
  'entity_type': 'target_molecule',
  'family_name': 'Prins Reaction',
  'notes': 'Macrolide target assembled via a tandem Mukaiyama aldol-Prins cyclization.',
  'page_label': 'p365'},
 {'canonical_name': '(-)-Centrolobine',
  'confidence': 0.85,
  'entity_text': '(-)-Centrolobine',
  'entity_type': 'target_molecule',
  'family_name': 'Prins Reaction',
  'notes': 'Natural product obtained through segment-coupling Prins cyclization that avoided '
           'oxonia-Cope side reactions.',
  'page_label': 'p365'},
 {'canonical_name': '(+)-Isocycloseychellene',
  'confidence': 0.84,
  'entity_text': '(+)-Isocycloseychellene',
  'entity_type': 'target_molecule',
  'family_name': 'Prins Reaction',
  'notes': 'Tricyclic ketone target accessed through an oxidative catalyst-free oxodive Prins '
           'process.',
  'page_label': 'p365'},
 {'canonical_name': 'Prins-Pinacol Rearrangement',
  'confidence': 0.92,
  'entity_text': 'Prins-Pinacol Rearrangement',
  'entity_type': 'reaction_family',
  'family_name': 'Prins-Pinacol Rearrangement',
  'notes': 'Overview page family anchor for the tandem Prins-pinacol rearrangement.',
  'page_label': 'p366'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'allylic 1,2-diol or allylic acetal + aldehyde/ketone',
  'entity_type': 'reactant_class',
  'family_name': 'Prins-Pinacol Rearrangement',
  'notes': 'Canonical substrate combination that initiates the tandem cyclization-rearrangement '
           'sequence.',
  'page_label': 'p366'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'highly substituted tetrahydrofuran',
  'entity_type': 'product_class',
  'family_name': 'Prins-Pinacol Rearrangement',
  'notes': 'Core heterocycle formed in the simplest Prins-pinacol products.',
  'page_label': 'p366'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'annulated 3-acyl tetrahydrofuran or cyclopentanone product',
  'entity_type': 'product_class',
  'family_name': 'Prins-Pinacol Rearrangement',
  'notes': 'Characteristic annulated products created when ring enlargement accompanies the tandem '
           'cascade.',
  'page_label': 'p366'},
 {'canonical_name': 'Prins-Pinacol Rearrangement',
  'confidence': 0.92,
  'entity_text': 'Prins-Pinacol Rearrangement',
  'entity_type': 'reaction_family',
  'family_name': 'Prins-Pinacol Rearrangement',
  'notes': 'Application page family anchor.',
  'page_label': 'p367'},
 {'canonical_name': 'Briarielin F',
  'confidence': 0.85,
  'entity_text': 'Briarielin F',
  'entity_type': 'target_molecule',
  'family_name': 'Prins-Pinacol Rearrangement',
  'notes': 'Briarane diterpene constructed using an early enantioselective Prins-pinacol '
           'rearrangement sequence.',
  'page_label': 'p367'},
 {'canonical_name': '(-)-Magellaninone',
  'confidence': 0.85,
  'entity_text': '(-)-Magellaninone',
  'entity_type': 'target_molecule',
  'family_name': 'Prins-Pinacol Rearrangement',
  'notes': 'Magellane alkaloid framework assembled through ring-enlarging all-carbon tetracycle '
           'formation.',
  'page_label': 'p367'},
 {'canonical_name': '(-)-Citreoviral',
  'confidence': 0.85,
  'entity_text': '(-)-Citreoviral',
  'entity_type': 'target_molecule',
  'family_name': 'Prins-Pinacol Rearrangement',
  'notes': 'Polysubstituted tetrahydrofuran target prepared from an unsymmetrical ketone with '
           'catalytic TMSOTf and SnCl4.',
  'page_label': 'p367'},
 {'canonical_name': '(+)-Shahamin K',
  'confidence': 0.85,
  'entity_text': '(+)-Shahamin K',
  'entity_type': 'target_molecule',
  'family_name': 'Prins-Pinacol Rearrangement',
  'notes': 'Natural product whose hydroazulene core arose through a thio-Prins-pinacol '
           'rearrangement.',
  'page_label': 'p367'},
 {'canonical_name': 'Pummerer Rearrangement',
  'confidence': 0.92,
  'entity_text': 'Pummerer Rearrangement',
  'entity_type': 'reaction_family',
  'family_name': 'Pummerer Rearrangement',
  'notes': 'Overview page family anchor for the Pummerer rearrangement.',
  'page_label': 'p368'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'sulfoxide activated by Ac2O or TFAA',
  'entity_type': 'reactant_class',
  'family_name': 'Pummerer Rearrangement',
  'notes': 'Canonical activated sulfoxide precursor class.',
  'page_label': 'p368'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'α-substituted sulfide',
  'entity_type': 'product_class',
  'family_name': 'Pummerer Rearrangement',
  'notes': 'Characteristic product class from nucleophile capture of sulfur-stabilized cations.',
  'page_label': 'p368'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'thiol plus carbonyl compound after hydrolysis',
  'entity_type': 'product_class',
  'family_name': 'Pummerer Rearrangement',
  'notes': 'Characteristic hydrolysis outcome for α-acetoxy sulfide products.',
  'page_label': 'p368'},
 {'canonical_name': 'Pummerer Rearrangement',
  'confidence': 0.92,
  'entity_text': 'Pummerer Rearrangement',
  'entity_type': 'reaction_family',
  'family_name': 'Pummerer Rearrangement',
  'notes': 'Application page family anchor.',
  'page_label': 'p369'},
 {'canonical_name': 'Enantiopure pyrrolidine',
  'confidence': 0.84,
  'entity_text': 'Enantiopure pyrrolidine',
  'entity_type': 'target_molecule',
  'family_name': 'Pummerer Rearrangement',
  'notes': 'Polyhydroxylated pyrrolidine accessed by a one-pot Pummerer rearrangement/NaBH4 '
           'reduction sequence from a chiral sulfoxide precursor.',
  'page_label': 'p369'},
 {'canonical_name': 'exo-Spirotenonate',
  'confidence': 0.85,
  'entity_text': 'exo-Spirotenonate',
  'entity_type': 'target_molecule',
  'family_name': 'Pummerer Rearrangement',
  'notes': 'Spirotetronate subunit prepared through Ac2O/NaOAc-promoted rearrangement of a '
           'sulfoxide.',
  'page_label': 'p369'},
 {'canonical_name': '(±)-Deethylibophyllidine',
  'confidence': 0.85,
  'entity_text': '(±)-Deethylibophyllidine',
  'entity_type': 'target_molecule',
  'family_name': 'Pummerer Rearrangement',
  'notes': 'Alkaloid target formed by tandem Pummerer rearrangement and iminium-ion cyclization '
           'followed by desulfurization.',
  'page_label': 'p369'},
 {'canonical_name': 'Solanopyrone D',
  'confidence': 0.85,
  'entity_text': 'Solanopyrone D',
  'entity_type': 'target_molecule',
  'family_name': 'Pummerer Rearrangement',
  'notes': 'Natural product whose formyl group was introduced through a vinylogous Pummerer '
           'rearrangement.',
  'page_label': 'p369'}]


def apply_frontmatter_batch42(db_path: str | Path) -> Dict[str, Any]:
    return apply_frontmatter_batch_generic(
        db_path=db_path,
        source_label=SOURCE_LABEL,
        version=FRONTMATTER_BATCH42_VERSION,
        latest_source_zip=LATEST_SOURCE_ZIP,
        batch_no=42,
        page_knowledge_seeds=PAGE_KNOWLEDGE_SEEDS,
        family_pattern_seeds=FAMILY_PATTERN_SEEDS,
        abbreviation_seeds=CURATED_BATCH42_ABBREVIATIONS,
        page_entity_seeds=PAGE_ENTITY_SEEDS,
    )
