from __future__ import annotations

from pathlib import Path
from typing import Any, Dict

from app.labint_frontmatter_batch_restore_utils import (
    apply_frontmatter_batch_generic,
    load_abbreviation_seeds,
    load_family_pattern_seeds,
    load_page_knowledge_seeds,
)

FRONTMATTER_BATCH44_VERSION = 'labint_frontmatter_batch44_v1_20260412'
SOURCE_LABEL = 'named_reactions_frontmatter_batch44'
LATEST_SOURCE_ZIP = 'backend_batch15_44_frontmatter_cumulative_patch_20260412.zip'

PAGE_KNOWLEDGE_SEEDS = load_page_knowledge_seeds(44, SOURCE_LABEL)
FAMILY_PATTERN_SEEDS = load_family_pattern_seeds(44, FRONTMATTER_BATCH44_VERSION)
BATCH44_SOURCE_PAGES = {'SeO2': 380,
 'Hg(NO3)2': 383,
 'LiCuMe2': 385,
 '4 Å MS': 386,
 'TESOTf': 389,
 'OTBDMS': 389}
CURATED_BATCH44_ABBREVIATIONS = load_abbreviation_seeds(
    44,
    SOURCE_LABEL,
    source_pages=BATCH44_SOURCE_PAGES,
    default_note='batch44 frontmatter abbreviation seed',
)
PAGE_ENTITY_SEEDS = [{'page_label': 'p380',
  'entity_text': 'Riley Selenium Dioxide Oxidation',
  'canonical_name': 'Riley Selenium Dioxide Oxidation',
  'entity_type': 'reaction_family',
  'family_name': 'Riley Selenium Dioxide Oxidation',
  'notes': 'Overview page family anchor for the Riley selenium dioxide oxidation.',
  'confidence': 0.92},
 {'page_label': 'p380',
  'entity_text': 'α-methylene ketone or aldehyde',
  'canonical_name': None,
  'entity_type': 'reactant_class',
  'family_name': 'Riley Selenium Dioxide Oxidation',
  'notes': 'Canonical carbonyl substrate class oxidized by selenium dioxide at the α-position.',
  'confidence': 0.84},
 {'page_label': 'p380',
  'entity_text': 'allylic alkene with an accessible allylic C–H bond',
  'canonical_name': None,
  'entity_type': 'reactant_class',
  'family_name': 'Riley Selenium Dioxide Oxidation',
  'notes': 'Representative olefin substrate family for selenium dioxide allylic oxidation.',
  'confidence': 0.84},
 {'page_label': 'p380',
  'entity_text': 'α-dicarbonyl compound or allylic alcohol',
  'canonical_name': None,
  'entity_type': 'product_class',
  'family_name': 'Riley Selenium Dioxide Oxidation',
  'notes': 'Typical oxidation products highlighted on the overview page.',
  'confidence': 0.84},
 {'page_label': 'p381',
  'entity_text': 'Riley Selenium Dioxide Oxidation',
  'canonical_name': 'Riley Selenium Dioxide Oxidation',
  'entity_type': 'reaction_family',
  'family_name': 'Riley Selenium Dioxide Oxidation',
  'notes': 'Application page family anchor.',
  'confidence': 0.92},
 {'page_label': 'p381',
  'entity_text': '6-epi-Hamigeran B',
  'canonical_name': '6-epi-Hamigeran B',
  'entity_type': 'target_molecule',
  'family_name': 'Riley Selenium Dioxide Oxidation',
  'notes': 'Tricarbocyclic antiviral natural product whose 1,2-diketone motif was introduced by '
           'Riley oxidation.',
  'confidence': 0.85},
 {'page_label': 'p381',
  'entity_text': 'α-amino acid',
  'canonical_name': 'α-amino acid',
  'entity_type': 'product_class',
  'family_name': 'Riley Selenium Dioxide Oxidation',
  'notes': 'Chiral amino-acid products obtained after Riley oxidation of a camphor-derived '
           'iminolactone equivalent and subsequent alkylation/hydrolysis.',
  'confidence': 0.85},
 {'page_label': 'p381',
  'entity_text': 'Cristatic acid',
  'canonical_name': 'Cristatic acid',
  'entity_type': 'target_molecule',
  'family_name': 'Riley Selenium Dioxide Oxidation',
  'notes': 'Prenylated aromatic antibiotic synthesized using SeO2-catalyzed allylic oxidation to '
           'introduce the E-allylic alcohol.',
  'confidence': 0.85},
 {'page_label': 'p381',
  'entity_text': 'Miroestrol',
  'canonical_name': 'Miroestrol',
  'entity_type': 'target_molecule',
  'family_name': 'Riley Selenium Dioxide Oxidation',
  'notes': 'Natural product whose bridgehead hydroxyl group was installed by selenium '
           'dioxide/tert-butyl hydroperoxide oxidation.',
  'confidence': 0.85},
 {'page_label': 'p382',
  'entity_text': 'Ritter Reaction',
  'canonical_name': 'Ritter Reaction',
  'entity_type': 'reaction_family',
  'family_name': 'Ritter Reaction',
  'notes': 'Overview page family anchor for the Ritter reaction.',
  'confidence': 0.92},
 {'page_label': 'p382',
  'entity_text': 'nitrile + carbocation precursor (alkene or tertiary alcohol)',
  'canonical_name': None,
  'entity_type': 'reactant_class',
  'family_name': 'Ritter Reaction',
  'notes': 'General substrate pairing used to access nitrilium ions under acidic conditions.',
  'confidence': 0.84},
 {'page_label': 'p382',
  'entity_text': 'nitrilium ion',
  'canonical_name': None,
  'entity_type': 'mechanistic_intermediate',
  'family_name': 'Ritter Reaction',
  'notes': 'Key cationic intermediate formed when the nitrile traps the carbocation.',
  'confidence': 0.84},
 {'page_label': 'p382',
  'entity_text': 'N-alkyl carboxamide',
  'canonical_name': None,
  'entity_type': 'product_class',
  'family_name': 'Ritter Reaction',
  'notes': 'Canonical hydrolysis product of the Ritter reaction.',
  'confidence': 0.84},
 {'page_label': 'p383',
  'entity_text': 'Ritter Reaction',
  'canonical_name': 'Ritter Reaction',
  'entity_type': 'reaction_family',
  'family_name': 'Ritter Reaction',
  'notes': 'Application page family anchor.',
  'confidence': 0.92},
 {'page_label': 'p383',
  'entity_text': '(+)-Aristotelone',
  'canonical_name': '(+)-Aristotelone',
  'entity_type': 'target_molecule',
  'family_name': 'Ritter Reaction',
  'notes': 'Alkaloid accessed through a biomimetic Hg(NO3)2-mediated Ritter reaction of a '
           'pinene-derived carbocation.',
  'confidence': 0.85},
 {'page_label': 'p383',
  'entity_text': '(+)-Isocyanoallopupukeanane',
  'canonical_name': '(+)-Isocyanoallopupukeanane',
  'entity_type': 'target_molecule',
  'family_name': 'Ritter Reaction',
  'notes': 'Marine sesquiterpene synthesized by introducing the isocyano unit via Ritter reaction '
           'at a tricyclic alkene stage.',
  'confidence': 0.85},
 {'page_label': 'p383',
  'entity_text': 'Electron-rich analogue of PK 11195',
  'canonical_name': 'Electron-rich analogue of PK 11195',
  'entity_type': 'target_molecule',
  'family_name': 'Ritter Reaction',
  'notes': 'Dihydroisoquinoline prepared under modified Ritter conditions using HBF4 in ether.',
  'confidence': 0.85},
 {'page_label': 'p383',
  'entity_text': 'Potential dopamine receptor ligand',
  'canonical_name': 'Potential dopamine receptor ligand',
  'entity_type': 'target_molecule',
  'family_name': 'Ritter Reaction',
  'notes': 'Lactam target obtained through intramolecular trapping of a benzylic carbocation by a '
           'pendant nitrile.',
  'confidence': 0.85},
 {'page_label': 'p384',
  'entity_text': 'Robinson Annulation',
  'canonical_name': 'Robinson Annulation',
  'entity_type': 'reaction_family',
  'family_name': 'Robinson Annulation',
  'notes': 'Overview page family anchor for the Robinson annulation.',
  'confidence': 0.92},
 {'page_label': 'p384',
  'entity_text': 'ketone enolate + α,β-unsaturated ketone',
  'canonical_name': None,
  'entity_type': 'reactant_class',
  'family_name': 'Robinson Annulation',
  'notes': 'Canonical reactant pairing for Robinson annulation.',
  'confidence': 0.84},
 {'page_label': 'p384',
  'entity_text': 'Michael addition / intramolecular aldol condensation sequence',
  'canonical_name': None,
  'entity_type': 'mechanism_type',
  'family_name': 'Robinson Annulation',
  'notes': 'Two-step bond-forming sequence that defines the annulation.',
  'confidence': 0.84},
 {'page_label': 'p384',
  'entity_text': 'substituted cyclohexenone or fused bicyclic enone',
  'canonical_name': None,
  'entity_type': 'product_class',
  'family_name': 'Robinson Annulation',
  'notes': 'Typical annulation product class shown on the overview page.',
  'confidence': 0.84},
 {'page_label': 'p385',
  'entity_text': 'Robinson Annulation',
  'canonical_name': 'Robinson Annulation',
  'entity_type': 'reaction_family',
  'family_name': 'Robinson Annulation',
  'notes': 'Application page family anchor.',
  'confidence': 0.92},
 {'page_label': 'p385',
  'entity_text': 'Hispidospermidin',
  'canonical_name': 'Hispidospermidin',
  'entity_type': 'target_molecule',
  'family_name': 'Robinson Annulation',
  'notes': 'Highly stereoselective alkaloid target assembled through a conjugate-cuprate-addition '
           'Robinson annulation sequence.',
  'confidence': 0.85},
 {'page_label': 'p385',
  'entity_text': '(+)-Codeine',
  'canonical_name': '(+)-Codeine',
  'entity_type': 'target_molecule',
  'family_name': 'Robinson Annulation',
  'notes': 'Asymmetric total synthesis using Robinson annulation to build a phenanthrenone '
           'precursor.',
  'confidence': 0.85},
 {'page_label': 'p385',
  'entity_text': '(−)-Austalide B',
  'canonical_name': '(−)-Austalide B',
  'entity_type': 'target_molecule',
  'family_name': 'Robinson Annulation',
  'notes': 'Mixed polyketide-terpenoid metabolite accessed through an enantioselective '
           'Hajos–Parrish annulation.',
  'confidence': 0.85},
 {'page_label': 'p385',
  'entity_text': '(+)-Guanacastepene A',
  'canonical_name': '(+)-Guanacastepene A',
  'entity_type': 'target_molecule',
  'family_name': 'Robinson Annulation',
  'notes': 'Target reached via a Stork–Jung modified Robinson annulation after allylsilane '
           'alkylation and Fleming–Tamao oxidation.',
  'confidence': 0.85},
 {'page_label': 'p386',
  'entity_text': 'Roush Asymmetric Allylation',
  'canonical_name': 'Roush Asymmetric Allylation',
  'entity_type': 'reaction_family',
  'family_name': 'Roush Asymmetric Allylation',
  'notes': 'Overview page family anchor for the Roush asymmetric allylation.',
  'confidence': 0.92},
 {'page_label': 'p386',
  'entity_text': 'tartrate-derived allylboronate or crotylboronate + aldehyde',
  'canonical_name': None,
  'entity_type': 'reactant_class',
  'family_name': 'Roush Asymmetric Allylation',
  'notes': 'Canonical reagent combination used in the Roush allylation manifold.',
  'confidence': 0.84},
 {'page_label': 'p386',
  'entity_text': 'syn or anti homoallylic alcohol',
  'canonical_name': None,
  'entity_type': 'product_class',
  'family_name': 'Roush Asymmetric Allylation',
  'notes': 'Characteristic product class whose stereochemistry is controlled by allylboronate '
           'geometry.',
  'confidence': 0.84},
 {'page_label': 'p386',
  'entity_text': 'chairlike allylboration transition state',
  'canonical_name': None,
  'entity_type': 'mechanism_type',
  'family_name': 'Roush Asymmetric Allylation',
  'notes': 'Transition-state model used to rationalize enantio- and diastereoselectivity.',
  'confidence': 0.84},
 {'page_label': 'p387',
  'entity_text': 'Roush Asymmetric Allylation',
  'canonical_name': 'Roush Asymmetric Allylation',
  'entity_type': 'reaction_family',
  'family_name': 'Roush Asymmetric Allylation',
  'notes': 'Application page family anchor.',
  'confidence': 0.92},
 {'page_label': 'p387',
  'entity_text': 'C15-C25 subunit of (+)-Lasonolide A',
  'canonical_name': 'C15-C25 subunit of (+)-Lasonolide A',
  'entity_type': 'target_molecule',
  'family_name': 'Roush Asymmetric Allylation',
  'notes': 'Fragment whose C21 and C23 stereocenters were installed by sequential Roush asymmetric '
           'allylations.',
  'confidence': 0.85},
 {'page_label': 'p387',
  'entity_text': 'C38-C51 subunit of Spongistatin 1',
  'canonical_name': 'C38-C51 subunit of Spongistatin 1',
  'entity_type': 'target_molecule',
  'family_name': 'Roush Asymmetric Allylation',
  'notes': 'Fragment synthesis in which Roush allylation was applied twice to set C39 and C41 '
           'stereocenters.',
  'confidence': 0.85},
 {'page_label': 'p387',
  'entity_text': 'Stevastelin B',
  'canonical_name': 'Stevastelin B',
  'entity_type': 'target_molecule',
  'family_name': 'Roush Asymmetric Allylation',
  'notes': 'Depsipeptide natural product whose allylation used an (S,S)-diisopropyl '
           'tartrate-derived (E)-crotyl boronate.',
  'confidence': 0.85},
 {'page_label': 'p387',
  'entity_text': 'Clerocidin',
  'canonical_name': 'Clerocidin',
  'entity_type': 'target_molecule',
  'family_name': 'Roush Asymmetric Allylation',
  'notes': 'Diterpenoid antibiotic synthesized using asymmetric homoallylboration to set the C12 '
           'stereocenter.',
  'confidence': 0.85},
 {'page_label': 'p388',
  'entity_text': 'Rubottom Oxidation',
  'canonical_name': 'Rubottom Oxidation',
  'entity_type': 'reaction_family',
  'family_name': 'Rubottom Oxidation',
  'notes': 'Overview page family anchor for the Rubottom oxidation.',
  'confidence': 0.92},
 {'page_label': 'p388',
  'entity_text': 'silyl enol ether treated with a peracid',
  'canonical_name': None,
  'entity_type': 'reactant_class',
  'family_name': 'Rubottom Oxidation',
  'notes': 'Canonical substrate/reactant class for the Rubottom oxidation.',
  'confidence': 0.84},
 {'page_label': 'p388',
  'entity_text': 'α-hydroxy ketone or α-hydroxy aldehyde',
  'canonical_name': None,
  'entity_type': 'product_class',
  'family_name': 'Rubottom Oxidation',
  'notes': 'Principal product class obtained after oxidation and hydrolysis of the enol silane.',
  'confidence': 0.84},
 {'page_label': 'p388',
  'entity_text': 'α-silyloxy epoxide and [1,4]-silyl shift',
  'canonical_name': None,
  'entity_type': 'mechanism_type',
  'family_name': 'Rubottom Oxidation',
  'notes': 'Mechanistic signature of the Rubottom oxidation highlighted on the overview page.',
  'confidence': 0.84},
 {'page_label': 'p389',
  'entity_text': 'Rubottom Oxidation',
  'canonical_name': 'Rubottom Oxidation',
  'entity_type': 'reaction_family',
  'family_name': 'Rubottom Oxidation',
  'notes': 'Application page family anchor.',
  'confidence': 0.92},
 {'page_label': 'p389',
  'entity_text': '(+)-Rishirilide B',
  'canonical_name': '(+)-Rishirilide B',
  'entity_type': 'target_molecule',
  'family_name': 'Rubottom Oxidation',
  'notes': 'Antithrombotic polyketide target obtained through diastereoselective α-hydroxylation '
           'of a six-membered silyl dienol ether.',
  'confidence': 0.85},
 {'page_label': 'p389',
  'entity_text': 'FR901464',
  'canonical_name': 'FR901464',
  'entity_type': 'target_molecule',
  'family_name': 'Rubottom Oxidation',
  'notes': 'Antitumor antibiotic whose enol silane intermediate underwent buffered mCPBA Rubottom '
           'oxidation.',
  'confidence': 0.85},
 {'page_label': 'p389',
  'entity_text': 'd,l-Isospongiadol',
  'canonical_name': 'd,l-Isospongiadol',
  'entity_type': 'target_molecule',
  'family_name': 'Rubottom Oxidation',
  'notes': 'Furanoditerpene natural product accessed after an oxidative free-radical cyclization '
           'sequence ending with Rubottom hydroxylation.',
  'confidence': 0.85},
 {'page_label': 'p389',
  'entity_text': 'Hispidospermidin',
  'canonical_name': 'Hispidospermidin',
  'entity_type': 'target_molecule',
  'family_name': 'Rubottom Oxidation',
  'notes': 'Alkaloid target whose C10 oxygenation was installed by Rubottom oxidation of a TES '
           'enol ether.',
  'confidence': 0.85}]


def apply_frontmatter_batch44(db_path: str | Path) -> Dict[str, Any]:
    return apply_frontmatter_batch_generic(
        db_path=db_path,
        source_label=SOURCE_LABEL,
        version=FRONTMATTER_BATCH44_VERSION,
        latest_source_zip=LATEST_SOURCE_ZIP,
        batch_no=44,
        page_knowledge_seeds=PAGE_KNOWLEDGE_SEEDS,
        family_pattern_seeds=FAMILY_PATTERN_SEEDS,
        abbreviation_seeds=CURATED_BATCH44_ABBREVIATIONS,
        page_entity_seeds=PAGE_ENTITY_SEEDS,
        replace_existing_page_entities=False,
    )
