from __future__ import annotations

from pathlib import Path
from typing import Any, Dict

from app.labint_frontmatter_batch_restore_utils import (
    apply_frontmatter_batch_generic,
    load_abbreviation_seeds,
    load_family_pattern_seeds,
    load_page_knowledge_seeds,
)

FRONTMATTER_BATCH28_VERSION = 'labint_frontmatter_batch28_v1_20260412'
SOURCE_LABEL = 'named_reactions_frontmatter_batch28'
LATEST_SOURCE_ZIP = 'backend_batch15_28_frontmatter_cumulative_patch_20260412.zip'

PAGE_KNOWLEDGE_SEEDS = load_page_knowledge_seeds(28, SOURCE_LABEL)
FAMILY_PATTERN_SEEDS = load_family_pattern_seeds(28, FRONTMATTER_BATCH28_VERSION)
BATCH28_SOURCE_PAGES = {'HNO2': 224,
 'NaOAc': 224,
 'CO2': 224,
 'H2O': 224,
 'KOH': 225,
 'EtOH': 225,
 'NaNO2': 225,
 'TsOH': 227,
 'PivOH': 227,
 'TBS': 227,
 'CrO3': 228,
 'PCC': 228,
 'PDC': 228,
 'H2SO4': 228,
 'TiCl4': 228,
 'DMDO': 229,
 'Na(Hg)': 230,
 'MeOH': 230,
 'SmI2': 230,
 'PT-sulfone': 230,
 'NaHMDS': 231,
 'HMPA': 231,
 'TFA': 231,
 'TBAF': 231,
 'THF': 232,
 'NiI2': 232,
 'Fe(DBM)3': 232,
 'RuCl3': 232,
 'NaIO4': 232,
 'MeCN': 232,
 'CCl4': 232,
 'DCC': 233,
 'DMAP': 233,
 'LDA': 233}
CURATED_BATCH28_ABBREVIATIONS = load_abbreviation_seeds(
    28,
    SOURCE_LABEL,
    source_pages=BATCH28_SOURCE_PAGES,
    default_note='batch28 frontmatter abbreviation seed',
)
PAGE_ENTITY_SEEDS = [{'page_label': 'p224',
  'entity_text': 'Japp-Klingemann Reaction',
  'canonical_name': 'Japp-Klingemann Reaction',
  'entity_type': 'reaction_family',
  'family_name': 'Japp-Klingemann Reaction',
  'notes': 'Named diazonium coupling family overview.',
  'confidence': 0.92},
 {'page_label': 'p224',
  'entity_text': 'Fischer Indole Synthesis',
  'canonical_name': 'Fischer Indole Synthesis',
  'entity_type': 'related_reaction',
  'family_name': 'Japp-Klingemann Reaction',
  'notes': 'Arylhydrazones from the Japp-Klingemann reaction are highlighted as key precursors for Fischer indole synthesis.',
  'confidence': 0.87},
 {'page_label': 'p224',
  'entity_text': 'arylhydrazone',
  'canonical_name': None,
  'entity_type': 'product_class',
  'family_name': 'Japp-Klingemann Reaction',
  'notes': 'Characteristic hydrazone product class obtained from diazonium coupling of 1,3-dicarbonyl compounds.',
  'confidence': 0.84},
 {'page_label': 'p225',
  'entity_text': 'Japp-Klingemann Reaction',
  'canonical_name': 'Japp-Klingemann Reaction',
  'entity_type': 'reaction_family',
  'family_name': 'Japp-Klingemann Reaction',
  'notes': 'Application page family anchor.',
  'confidence': 0.92},
 {'page_label': 'p225',
  'entity_text': '(-)-Gilbertine',
  'canonical_name': '(-)-Gilbertine',
  'entity_type': 'target_molecule',
  'family_name': 'Japp-Klingemann Reaction',
  'notes': 'Indole alkaloid synthesized using a modified Japp-Klingemann reaction followed by Fischer indole formation.',
  'confidence': 0.86},
 {'page_label': 'p225',
  'entity_text': 'Arnoamine A',
  'canonical_name': 'Arnoamine A',
  'entity_type': 'target_molecule',
  'family_name': 'Japp-Klingemann Reaction',
  'notes': 'Pentacyclic pyridoacridine alkaloid prepared through Japp-Klingemann-derived hydrazone chemistry.',
  'confidence': 0.85},
 {'page_label': 'p226',
  'entity_text': 'Johnson-Claisen Rearrangement',
  'canonical_name': 'Johnson-Claisen Rearrangement',
  'entity_type': 'reaction_family',
  'family_name': 'Johnson-Claisen Rearrangement',
  'notes': 'Named orthoester Claisen family overview.',
  'confidence': 0.92},
 {'page_label': 'p226',
  'entity_text': 'Claisen Rearrangement',
  'canonical_name': 'Claisen Rearrangement',
  'entity_type': 'related_reaction',
  'family_name': 'Johnson-Claisen Rearrangement',
  'notes': 'Parent [3,3]-sigmatropic rearrangement family from which the Johnson-Claisen variant derives.',
  'confidence': 0.87},
 {'page_label': 'p226',
  'entity_text': 'γ,δ-unsaturated ester',
  'canonical_name': None,
  'entity_type': 'product_class',
  'family_name': 'Johnson-Claisen Rearrangement',
  'notes': 'Characteristic rearrangement product class generated from allylic alcohols and ortho esters.',
  'confidence': 0.84},
 {'page_label': 'p227',
  'entity_text': 'Johnson-Claisen Rearrangement',
  'canonical_name': 'Johnson-Claisen Rearrangement',
  'entity_type': 'reaction_family',
  'family_name': 'Johnson-Claisen Rearrangement',
  'notes': 'Application page family anchor.',
  'confidence': 0.92},
 {'page_label': 'p227',
  'entity_text': 'Halomon',
  'canonical_name': 'Halomon',
  'entity_type': 'target_molecule',
  'family_name': 'Johnson-Claisen Rearrangement',
  'notes': 'Antitumor agent whose tertiary chlorinated stereocenter was set through a Johnson-Claisen rearrangement of a '
           'trans-dichloroallyl alcohol.',
  'confidence': 0.86},
 {'page_label': 'p227',
  'entity_text': '(+)-Brefeldin A',
  'canonical_name': '(+)-Brefeldin A',
  'entity_type': 'target_molecule',
  'family_name': 'Johnson-Claisen Rearrangement',
  'notes': 'Macrocyclic natural product whose 13-membered framework was advanced through an ortho ester Claisen rearrangement.',
  'confidence': 0.85},
 {'page_label': 'p228',
  'entity_text': 'Jones Oxidation',
  'canonical_name': 'Jones Oxidation',
  'entity_type': 'reaction_family',
  'family_name': 'Jones Oxidation',
  'notes': 'Chromium(VI) oxidation family overview.',
  'confidence': 0.92},
 {'page_label': 'p228',
  'entity_text': 'Collins Oxidation',
  'canonical_name': 'Collins Oxidation',
  'entity_type': 'related_reaction',
  'family_name': 'Jones Oxidation',
  'notes': 'Related nonaqueous Cr(VI) oxidation variant compared on the overview page alongside Sarett, PCC, and PDC oxidations.',
  'confidence': 0.87},
 {'page_label': 'p228',
  'entity_text': 'ketone',
  'canonical_name': None,
  'entity_type': 'product_class',
  'family_name': 'Jones Oxidation',
  'notes': 'Representative oxidation product class from secondary alcohols under Jones or related chromium-reagent conditions.',
  'confidence': 0.84},
 {'page_label': 'p229',
  'entity_text': 'Jones Oxidation',
  'canonical_name': 'Jones Oxidation',
  'entity_type': 'reaction_family',
  'family_name': 'Jones Oxidation',
  'notes': 'Application page family anchor.',
  'confidence': 0.92},
 {'page_label': 'p229',
  'entity_text': '(-)-CP-263,114 (Phomoidride B)',
  'canonical_name': '(-)-CP-263,114 (Phomoidride B)',
  'entity_type': 'target_molecule',
  'family_name': 'Jones Oxidation',
  'notes': 'Natural product synthesis used Jones oxidation in a late-stage side-chain oxidation sequence.',
  'confidence': 0.86},
 {'page_label': 'p229',
  'entity_text': '(+)-Bilobalide',
  'canonical_name': '(+)-Bilobalide',
  'entity_type': 'target_molecule',
  'family_name': 'Jones Oxidation',
  'notes': 'Ginkgolide natural product assembled through multiple Jones oxidations during endgame oxidation and lactone formation.',
  'confidence': 0.85},
 {'page_label': 'p230',
  'entity_text': 'Julia-Lythgoe Olefination',
  'canonical_name': 'Julia-Lythgoe Olefination',
  'entity_type': 'reaction_family',
  'family_name': 'Julia-Lythgoe Olefination',
  'notes': 'Sulfone olefination family overview.',
  'confidence': 0.92},
 {'page_label': 'p230',
  'entity_text': 'Kocienski-Modified Julia Olefination',
  'canonical_name': 'Kocienski-Modified Julia Olefination',
  'entity_type': 'related_reaction',
  'family_name': 'Julia-Lythgoe Olefination',
  'notes': 'One-pot heteroaryl sulfone variant highlighted on the overview page.',
  'confidence': 0.87},
 {'page_label': 'p230',
  'entity_text': '(E)-alkene',
  'canonical_name': None,
  'entity_type': 'product_class',
  'family_name': 'Julia-Lythgoe Olefination',
  'notes': 'Characteristic major alkene geometry delivered by the classical Julia-Lythgoe sequence.',
  'confidence': 0.84},
 {'page_label': 'p231',
  'entity_text': 'Julia-Lythgoe Olefination',
  'canonical_name': 'Julia-Lythgoe Olefination',
  'entity_type': 'reaction_family',
  'family_name': 'Julia-Lythgoe Olefination',
  'notes': 'Application page family anchor.',
  'confidence': 0.92},
 {'page_label': 'p231',
  'entity_text': '(+/-)-Indolizomycin',
  'canonical_name': '(+/-)-Indolizomycin',
  'entity_type': 'target_molecule',
  'family_name': 'Julia-Lythgoe Olefination',
  'notes': 'Natural product whose trienyl side chain was elaborated through the classical Julia-Lythgoe olefination.',
  'confidence': 0.86},
 {'page_label': 'p231',
  'entity_text': '(+)-Ambruticin',
  'canonical_name': '(+)-Ambruticin',
  'entity_type': 'target_molecule',
  'family_name': 'Julia-Lythgoe Olefination',
  'notes': 'Antifungal natural product assembled through a highly E-selective Kocienski-modified Julia olefination to forge the C8-C9 '
           'alkene.',
  'confidence': 0.85},
 {'page_label': 'p232',
  'entity_text': 'Kagan-Molander Samarium Diiodide-Mediated Coupling',
  'canonical_name': 'Kagan-Molander Samarium Diiodide-Mediated Coupling',
  'entity_type': 'reaction_family',
  'family_name': 'Kagan-Molander Samarium Diiodide-Mediated Coupling',
  'notes': 'SmI2-mediated coupling family overview.',
  'confidence': 0.92},
 {'page_label': 'p232',
  'entity_text': 'Samarium Barbier Reaction',
  'canonical_name': 'Samarium Barbier Reaction',
  'entity_type': 'related_reaction',
  'family_name': 'Kagan-Molander Samarium Diiodide-Mediated Coupling',
  'notes': 'The overview explicitly situates Kagan-Molander chemistry within samarium Barbier and samarium Grignard manifolds.',
  'confidence': 0.87},
 {'page_label': 'p232',
  'entity_text': 'bicyclic alcohol',
  'canonical_name': None,
  'entity_type': 'product_class',
  'family_name': 'Kagan-Molander Samarium Diiodide-Mediated Coupling',
  'notes': 'Representative product class obtained from intramolecular SmI2-mediated coupling of halo carbonyl precursors.',
  'confidence': 0.84},
 {'page_label': 'p233',
  'entity_text': 'Kagan-Molander Samarium Diiodide-Mediated Coupling',
  'canonical_name': 'Kagan-Molander Samarium Diiodide-Mediated Coupling',
  'entity_type': 'reaction_family',
  'family_name': 'Kagan-Molander Samarium Diiodide-Mediated Coupling',
  'notes': 'Application page family anchor.',
  'confidence': 0.92},
 {'page_label': 'p233',
  'entity_text': 'Variecolin',
  'canonical_name': 'Variecolin',
  'entity_type': 'target_molecule',
  'family_name': 'Kagan-Molander Samarium Diiodide-Mediated Coupling',
  'notes': 'Sesterterpenoid target whose ABC ring system was assembled through samarium diiodide mediated coupling chemistry.',
  'confidence': 0.86},
 {'page_label': 'p233',
  'entity_text': 'Pederin',
  'canonical_name': 'Pederin',
  'entity_type': 'target_molecule',
  'family_name': 'Kagan-Molander Samarium Diiodide-Mediated Coupling',
  'notes': 'Potent insect toxin synthesized using an intramolecular samarium diiodide-induced Reformatsky reaction as a key '
           'lactone-forming step.',
  'confidence': 0.85}]


def apply_frontmatter_batch28(db_path: str | Path) -> Dict[str, Any]:
    return apply_frontmatter_batch_generic(
        db_path=db_path,
        source_label=SOURCE_LABEL,
        version=FRONTMATTER_BATCH28_VERSION,
        latest_source_zip=LATEST_SOURCE_ZIP,
        batch_no=28,
        page_knowledge_seeds=PAGE_KNOWLEDGE_SEEDS,
        family_pattern_seeds=FAMILY_PATTERN_SEEDS,
        abbreviation_seeds=CURATED_BATCH28_ABBREVIATIONS,
        page_entity_seeds=PAGE_ENTITY_SEEDS,
        replace_existing_page_entities=True,
    )
