from __future__ import annotations

from pathlib import Path
from typing import Any, Dict

from app.labint_frontmatter_batch_restore_utils import (
    apply_frontmatter_batch_generic,
    load_abbreviation_seeds,
    load_family_pattern_seeds,
    load_page_knowledge_seeds,
)

FRONTMATTER_BATCH33_VERSION = 'labint_frontmatter_batch33_v1_20260412'
SOURCE_LABEL = 'named_reactions_frontmatter_batch33'
LATEST_SOURCE_ZIP = 'backend_batch15_33_frontmatter_cumulative_patch_20260412.zip'

PAGE_KNOWLEDGE_SEEDS = load_page_knowledge_seeds(33, SOURCE_LABEL)
FAMILY_PATTERN_SEEDS = load_family_pattern_seeds(33, FRONTMATTER_BATCH33_VERSION)
BATCH33_SOURCE_PAGES = {'Al(i-PrO)3': 280,
 'BF3·Et2O': 279,
 'Cu2O': 279,
 'CuCl': 278,
 'CuCl2·H2O': 279,
 'DBU': 283,
 'DMF': 275,
 'H2O2': 283,
 'KCl': 279,
 'KHMDS': 275,
 'MMPP': 283,
 'NFLX': 283,
 'NH4Cl': 274,
 'NH4OAc': 274,
 'NaNO2': 278,
 'TFA': 275,
 'THF': 283,
 'TMSCl': 275,
 'TiCl3': 276,
 'TiCl4': 277,
 'Zn': 276,
 'mCPBA': 282}
CURATED_BATCH33_ABBREVIATIONS = load_abbreviation_seeds(
    33,
    SOURCE_LABEL,
    source_pages=BATCH33_SOURCE_PAGES,
    default_note='batch33 frontmatter abbreviation seed',
)
PAGE_ENTITY_SEEDS = [{'canonical_name': 'Mannich Reaction',
  'confidence': 0.92,
  'entity_text': 'Mannich Reaction',
  'entity_type': 'reaction_family',
  'family_name': 'Mannich Reaction',
  'notes': 'Aminomethylation reaction family overview.',
  'page_label': 'p274'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'enolizable carbonyl compound',
  'entity_type': 'reactant_class',
  'family_name': 'Mannich Reaction',
  'notes': 'Typical nucleophilic component that reacts with iminium intermediates in the Mannich reaction.',
  'page_label': 'p274'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'Mannich base',
  'entity_type': 'product_class',
  'family_name': 'Mannich Reaction',
  'notes': 'Characteristic beta-amino carbonyl product class formed by aminomethylation.',
  'page_label': 'p274'},
 {'canonical_name': 'Mannich Reaction',
  'confidence': 0.92,
  'entity_text': 'Mannich Reaction',
  'entity_type': 'reaction_family',
  'family_name': 'Mannich Reaction',
  'notes': 'Application page family anchor.',
  'page_label': 'p275'},
 {'canonical_name': '(+)-Aspidospermidine',
  'confidence': 0.86,
  'entity_text': '(+)-Aspidospermidine',
  'entity_type': 'target_molecule',
  'family_name': 'Mannich Reaction',
  'notes': 'Alkaloid target assembled through an intramolecular Mannich-type cyclization that formed multiple rings in one operation.',
  'page_label': 'p275'},
 {'canonical_name': '(+)-Croomine',
  'confidence': 0.85,
  'entity_text': '(+)-Croomine',
  'entity_type': 'target_molecule',
  'family_name': 'Mannich Reaction',
  'notes': 'Natural-product target accessed via a vinylogous Mannich reaction to establish the butenolide stereochemistry.',
  'page_label': 'p275'},
 {'canonical_name': 'McMurry Coupling',
  'confidence': 0.92,
  'entity_text': 'McMurry Coupling',
  'entity_type': 'reaction_family',
  'family_name': 'McMurry Coupling',
  'notes': 'Low-valent titanium reductive coupling family overview.',
  'page_label': 'p276'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'aldehyde or ketone',
  'entity_type': 'reactant_class',
  'family_name': 'McMurry Coupling',
  'notes': 'Carbonyl partners that are reductively coupled under low-valent titanium conditions.',
  'page_label': 'p276'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'alkene',
  'entity_type': 'product_class',
  'family_name': 'McMurry Coupling',
  'notes': 'Characteristic olefin product produced after reductive dimerization and deoxygenation of carbonyl compounds.',
  'page_label': 'p276'},
 {'canonical_name': 'McMurry Coupling',
  'confidence': 0.92,
  'entity_text': 'McMurry Coupling',
  'entity_type': 'reaction_family',
  'family_name': 'McMurry Coupling',
  'notes': 'Application page family anchor.',
  'page_label': 'p277'},
 {'canonical_name': '(-)-13-Hydroxyoeocembrene',
  'confidence': 0.83,
  'entity_text': '(-)-13-Hydroxyoeocembrene',
  'entity_type': 'target_molecule',
  'family_name': 'McMurry Coupling',
  'notes': 'Macrocyclic natural product formed through intramolecular McMurry coupling as the key ring-closing step.',
  'page_label': 'p277'},
 {'canonical_name': 'ADAM II non-nucleoside reverse transcriptase inhibitor',
  'confidence': 0.84,
  'entity_text': 'ADAM II non-nucleoside reverse transcriptase inhibitor',
  'entity_type': 'target_molecule',
  'family_name': 'McMurry Coupling',
  'notes': 'Diaryl-ketone/aldehyde coupling example showcasing the utility of McMurry chemistry in medicinal-target synthesis.',
  'page_label': 'p277'},
 {'canonical_name': 'Meerwein Arylation',
  'confidence': 0.92,
  'entity_text': 'Meerwein Arylation',
  'entity_type': 'reaction_family',
  'family_name': 'Meerwein Arylation',
  'notes': 'Aryldiazonium-radical arylation family overview.',
  'page_label': 'p278'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'aryldiazonium salt',
  'entity_type': 'reactant_class',
  'family_name': 'Meerwein Arylation',
  'notes': 'Aryl-radical precursor generated in situ from substituted anilines and nitrite under acidic conditions.',
  'page_label': 'p278'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'aryl-substituted olefin',
  'entity_type': 'product_class',
  'family_name': 'Meerwein Arylation',
  'notes': 'Characteristic product class formed after radical aryl addition and elimination from activated olefins.',
  'page_label': 'p278'},
 {'canonical_name': 'Meerwein Arylation',
  'confidence': 0.92,
  'entity_text': 'Meerwein Arylation',
  'entity_type': 'reaction_family',
  'family_name': 'Meerwein Arylation',
  'notes': 'Application page family anchor.',
  'page_label': 'p279'},
 {'canonical_name': 'Calpain I inhibitor',
  'confidence': 0.85,
  'entity_text': 'Calpain I inhibitor',
  'entity_type': 'target_molecule',
  'family_name': 'Meerwein Arylation',
  'notes': 'Peptidomimetic aldehyde inhibitor assembled through diazonium-based Meerwein arylation of acrylonitrile.',
  'page_label': 'p279'},
 {'canonical_name': 'Gilvocarcin-M aglycone',
  'confidence': 0.85,
  'entity_text': 'Gilvocarcin-M aglycone',
  'entity_type': 'target_molecule',
  'family_name': 'Meerwein Arylation',
  'notes': 'Aromatic natural-product aglycone reached by a tandem Meerwein arylation/Diels-Alder sequence.',
  'page_label': 'p279'},
 {'canonical_name': 'Meerwein-Ponndorf-Verley Reduction',
  'confidence': 0.92,
  'entity_text': 'Meerwein-Ponndorf-Verley Reduction',
  'entity_type': 'reaction_family',
  'family_name': 'Meerwein-Ponndorf-Verley Reduction',
  'notes': 'MPV transfer-hydrogen reduction family overview.',
  'page_label': 'p280'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'ketone or aldehyde',
  'entity_type': 'reactant_class',
  'family_name': 'Meerwein-Ponndorf-Verley Reduction',
  'notes': 'Carbonyl substrates that undergo transfer-hydride reduction with aluminum alkoxides.',
  'page_label': 'p280'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': '1° or 2° alcohol',
  'entity_type': 'product_class',
  'family_name': 'Meerwein-Ponndorf-Verley Reduction',
  'notes': 'Characteristic alcohol product obtained under MPV transfer-hydrogenation conditions.',
  'page_label': 'p280'},
 {'canonical_name': 'Meerwein-Ponndorf-Verley Reduction',
  'confidence': 0.92,
  'entity_text': 'Meerwein-Ponndorf-Verley Reduction',
  'entity_type': 'reaction_family',
  'family_name': 'Meerwein-Ponndorf-Verley Reduction',
  'notes': 'Application page family anchor.',
  'page_label': 'p281'},
 {'canonical_name': 'GA111 methyl ester',
  'confidence': 0.85,
  'entity_text': 'GA111 methyl ester',
  'entity_type': 'target_molecule',
  'family_name': 'Meerwein-Ponndorf-Verley Reduction',
  'notes': 'Selective reduction example where transfer hydrogenation delivered one diastereomeric alcohol preferentially in the final '
           'stages of total synthesis.',
  'page_label': 'p281'},
 {'canonical_name': 'dl-Coccuvinine',
  'confidence': 0.84,
  'entity_text': 'dl-Coccuvinine',
  'entity_type': 'target_molecule',
  'family_name': 'Meerwein-Ponndorf-Verley Reduction',
  'notes': 'Alkaloid target prepared using chemoselective MPV reduction of an alpha,beta-unsaturated ketone in the presence of other '
           'sensitive functionality.',
  'page_label': 'p281'},
 {'canonical_name': 'Meisenheimer Rearrangement',
  'confidence': 0.92,
  'entity_text': 'Meisenheimer Rearrangement',
  'entity_type': 'reaction_family',
  'family_name': 'Meisenheimer Rearrangement',
  'notes': 'N-oxide rearrangement family overview.',
  'page_label': 'p282'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': '3° amine N-oxide',
  'entity_type': 'reactant_class',
  'family_name': 'Meisenheimer Rearrangement',
  'notes': 'Characteristic rearrangement precursor that undergoes [1,2]- or [2,3]-migration.',
  'page_label': 'p282'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'N,O-disubstituted hydroxylamine',
  'entity_type': 'product_class',
  'family_name': 'Meisenheimer Rearrangement',
  'notes': 'Common rearrangement product class formed after migration from amine N-oxides.',
  'page_label': 'p282'},
 {'canonical_name': 'Meisenheimer Rearrangement',
  'confidence': 0.92,
  'entity_text': 'Meisenheimer Rearrangement',
  'entity_type': 'reaction_family',
  'family_name': 'Meisenheimer Rearrangement',
  'notes': 'Application page family anchor.',
  'page_label': 'p283'},
 {'canonical_name': '(R)-Sulcatol',
  'confidence': 0.86,
  'entity_text': '(R)-Sulcatol',
  'entity_type': 'target_molecule',
  'family_name': 'Meisenheimer Rearrangement',
  'notes': 'Aggregation pheromone prepared through a stereospecific allylic [2,3]-Meisenheimer rearrangement of an amine N-oxide.',
  'page_label': 'p283'},
 {'canonical_name': 'Magallanesine',
  'confidence': 0.85,
  'entity_text': 'Magallanesine',
  'entity_type': 'target_molecule',
  'family_name': 'Meisenheimer Rearrangement',
  'notes': 'Alkaloid target assembled through [1,2]-Meisenheimer rearrangement and Heck cyclization en route to an azocine derivative.',
  'page_label': 'p283'}]


def apply_frontmatter_batch33(db_path: str | Path) -> Dict[str, Any]:
    return apply_frontmatter_batch_generic(
        db_path=db_path,
        source_label=SOURCE_LABEL,
        version=FRONTMATTER_BATCH33_VERSION,
        latest_source_zip=LATEST_SOURCE_ZIP,
        batch_no=33,
        page_knowledge_seeds=PAGE_KNOWLEDGE_SEEDS,
        family_pattern_seeds=FAMILY_PATTERN_SEEDS,
        abbreviation_seeds=CURATED_BATCH33_ABBREVIATIONS,
        page_entity_seeds=PAGE_ENTITY_SEEDS,
        replace_existing_page_entities=True,
    )
