from __future__ import annotations
from pathlib import Path
from typing import Any, Dict

from app.labint_frontmatter_batch_restore_utils import (
    apply_frontmatter_batch_generic,
    load_abbreviation_seeds,
    load_family_pattern_seeds,
    load_page_knowledge_seeds,
)

FRONTMATTER_BATCH49_VERSION = 'labint_frontmatter_batch49_v1_20260414'
SOURCE_LABEL = 'named_reactions_frontmatter_batch49'
LATEST_SOURCE_ZIP = 'backend_batch15_49_frontmatter_cumulative_patch_20260412.zip'

PAGE_KNOWLEDGE_SEEDS = load_page_knowledge_seeds(49, SOURCE_LABEL)
FAMILY_PATTERN_SEEDS = load_family_pattern_seeds(49, FRONTMATTER_BATCH49_VERSION)
BATCH49_SOURCE_PAGES = {'MeNHNH2': 431,
 'NH2NH2': 431,
 'NaCN': 432,
 'Ni-Al': 431,
 'Pd(dppf)2': 431,
 'PhLi': 435,
 'SnCl2': 430,
 'TREN': 431}
CURATED_BATCH49_ABBREVIATIONS = load_abbreviation_seeds(
    49,
    SOURCE_LABEL,
    source_pages=BATCH49_SOURCE_PAGES,
    default_note='batch49 frontmatter abbreviation seed',
)
PAGE_ENTITY_SEEDS = [{'canonical_name': 'Stephen Aldehyde Synthesis (Stephen Reduction)',
  'confidence': 0.93,
  'entity_text': 'Stephen Aldehyde Synthesis (Stephen Reduction)',
  'entity_type': 'reaction_family',
  'family_name': 'Stephen Aldehyde Synthesis (Stephen Reduction)',
  'notes': 'Overview page family anchor for the Stephen reduction of nitriles to aldehydes.',
  'page_label': 'p430'},
 {'canonical_name': 'Stephen reduction',
  'confidence': 0.91,
  'entity_text': 'Stephen reduction',
  'entity_type': 'named_variant',
  'family_name': 'Stephen Aldehyde Synthesis (Stephen Reduction)',
  'notes': 'Common shorter name for the Stephen aldehyde synthesis.',
  'page_label': 'p430'},
 {'canonical_name': 'stannous chloride',
  'confidence': 0.9,
  'entity_text': 'SnCl2',
  'entity_type': 'abbreviation',
  'family_name': 'Stephen Aldehyde Synthesis (Stephen Reduction)',
  'notes': 'Tin(II) reductant that converts the imidoyl chloride to the aldimine tin complex.',
  'page_label': 'p430'},
 {'canonical_name': None,
  'confidence': 0.87,
  'entity_text': 'imidoyl chloride',
  'entity_type': 'intermediate_class',
  'family_name': 'Stephen Aldehyde Synthesis (Stephen Reduction)',
  'notes': 'Activated nitrile-derived cationic intermediate formed under anhydrous hydrogen chloride.',
  'page_label': 'p430'},
 {'canonical_name': None,
  'confidence': 0.86,
  'entity_text': 'aldimine hexachlorostannane',
  'entity_type': 'intermediate_class',
  'family_name': 'Stephen Aldehyde Synthesis (Stephen Reduction)',
  'notes': 'Tin complex intermediate that hydrolyzes to the target aldehyde on workup.',
  'page_label': 'p430'},
 {'canonical_name': None,
  'confidence': 0.85,
  'entity_text': 'pyrazolo[3,4-b][1,8]naphthyridine derivative',
  'entity_type': 'target_scaffold',
  'family_name': 'Stephen Aldehyde Synthesis (Stephen Reduction)',
  'notes': 'Condensed heteroaromatic scaffold accessed after Stephen reduction of the chloroformyl precursor and '
           'hydrazine cyclization.',
  'page_label': 'p431'},
 {'canonical_name': "[1,1'-Binaphthalenyl]-2,2'-dicarbaldehyde",
  'confidence': 0.85,
  'entity_text': "[1,1'-binaphthalenyl]-2,2'-dicarbaldehyde",
  'entity_type': 'target_molecule',
  'family_name': 'Stephen Aldehyde Synthesis (Stephen Reduction)',
  'notes': 'Biaryl dialdehyde obtained from a dinitrile precursor after catalytic cyanation and Stephen reduction.',
  'page_label': 'p431'},
 {'canonical_name': 'tripodal polypeptide',
  'confidence': 0.84,
  'entity_text': 'tripodal polypeptide',
  'entity_type': 'target_scaffold',
  'family_name': 'Stephen Aldehyde Synthesis (Stephen Reduction)',
  'notes': 'Peptide-templated scaffold assembled by reducing a 4-cyanomethyl benzoate to the corresponding aldehyde '
           'then reductive amination with TREN.',
  'page_label': 'p431'},
 {'canonical_name': 'trans-stilbene benzenesulfonamide derivative',
  'confidence': 0.84,
  'entity_text': 'trans-stilbene benzenesulfonamide derivative',
  'entity_type': 'target_molecule',
  'family_name': 'Stephen Aldehyde Synthesis (Stephen Reduction)',
  'notes': 'Medicinal-chemistry target prepared through nitrile-to-aldehyde conversion using a Raney nickel '
           'alloy/formic acid variant of the Stephen reduction.',
  'page_label': 'p431'},
 {'canonical_name': 'tris(2-aminoethyl)amine',
  'confidence': 0.89,
  'entity_text': 'TREN',
  'entity_type': 'abbreviation',
  'family_name': 'Stephen Aldehyde Synthesis (Stephen Reduction)',
  'notes': 'Tripodal amine used for reductive amination after aldehyde formation in the peptide-template example.',
  'page_label': 'p431'},
 {'canonical_name': 'Stetter Reaction',
  'confidence': 0.93,
  'entity_text': 'Stetter Reaction',
  'entity_type': 'reaction_family',
  'family_name': 'Stetter Reaction',
  'notes': 'Overview page family anchor for cyanide- and thiazolium-catalyzed umpolung conjugate acylation chemistry.',
  'page_label': 'p432'},
 {'canonical_name': 'sodium cyanide',
  'confidence': 0.89,
  'entity_text': 'NaCN',
  'entity_type': 'abbreviation',
  'family_name': 'Stetter Reaction',
  'notes': 'Classical nucleophilic catalyst used in the original Stetter examples.',
  'page_label': 'p432'},
 {'canonical_name': None,
  'confidence': 0.87,
  'entity_text': 'thiazolium salt',
  'entity_type': 'catalyst_class',
  'family_name': 'Stetter Reaction',
  'notes': 'Catalyst precursor that generates an N-heterocyclic carbene or Breslow-type acyl anion equivalent under '
           'basic conditions.',
  'page_label': 'p432'},
 {'canonical_name': None,
  'confidence': 0.86,
  'entity_text': 'γ-diketone',
  'entity_type': 'product_class',
  'family_name': 'Stetter Reaction',
  'notes': 'Characteristic 1,4-dicarbonyl product manifold of the Stetter reaction with enones.',
  'page_label': 'p432'},
 {'canonical_name': None,
  'confidence': 0.85,
  'entity_text': 'γ-oxo nitrile',
  'entity_type': 'product_class',
  'family_name': 'Stetter Reaction',
  'notes': 'Product class obtained when activated nitriles serve as Michael acceptors in the Stetter reaction.',
  'page_label': 'p432'},
 {'canonical_name': 'CI-981',
  'confidence': 0.85,
  'entity_text': 'CI-981',
  'entity_type': 'target_molecule',
  'family_name': 'Stetter Reaction',
  'notes': 'Tissue-selective HMG-CoA reductase inhibitor whose central pyrrole precursor was assembled using the '
           'Stetter reaction and Paal-Knorr pyrrole synthesis.',
  'page_label': 'p433'},
 {'canonical_name': 'Roseophilin',
  'confidence': 0.86,
  'entity_text': 'Roseophilin',
  'entity_type': 'target_molecule',
  'family_name': 'Stetter Reaction',
  'notes': 'Natural product synthesized from a macrocyclic 1,4-diketone formed by catalytic Stetter reaction.',
  'page_label': 'p433'},
 {'canonical_name': '(±)-trans-Sabinene hydrate',
  'confidence': 0.84,
  'entity_text': '(±)-trans-Sabinene hydrate',
  'entity_type': 'target_molecule',
  'family_name': 'Stetter Reaction',
  'notes': 'Flavor compound prepared by sequential Stetter reaction and intramolecular aldol condensation after '
           'Nazarov approaches failed.',
  'page_label': 'p433'},
 {'canonical_name': '(+)-Monomorine I',
  'confidence': 0.84,
  'entity_text': '(+)-Monomorine I',
  'entity_type': 'target_molecule',
  'family_name': 'Stetter Reaction',
  'notes': 'Indolizidine alkaloid obtained from a Stetter-reaction-generated masked enedione precursor.',
  'page_label': 'p433'},
 {'canonical_name': 'triethylamine',
  'confidence': 0.88,
  'entity_text': 'Et3N',
  'entity_type': 'abbreviation',
  'family_name': 'Stetter Reaction',
  'notes': 'Base used with chiral thiazolium catalysts in several asymmetric Stetter applications.',
  'page_label': 'p433'},
 {'canonical_name': 'Stevens Rearrangement',
  'confidence': 0.93,
  'entity_text': 'Stevens Rearrangement',
  'entity_type': 'reaction_family',
  'family_name': 'Stevens Rearrangement',
  'notes': 'Overview page family anchor for [1,2]-migration of ammonium or sulfonium ylides.',
  'page_label': 'p434'},
 {'canonical_name': None,
  'confidence': 0.87,
  'entity_text': 'quaternary ammonium salt',
  'entity_type': 'intermediate_class',
  'family_name': 'Stevens Rearrangement',
  'notes': 'Typical onium precursor that generates a nitrogen ylide under strong-base conditions.',
  'page_label': 'p434'},
 {'canonical_name': None,
  'confidence': 0.87,
  'entity_text': 'sulfonium salt',
  'entity_type': 'intermediate_class',
  'family_name': 'Stevens Rearrangement',
  'notes': 'Sulfur ylide precursor used in the sulfonium version of the Stevens rearrangement.',
  'page_label': 'p434'},
 {'canonical_name': '[1,2]-migration',
  'confidence': 0.85,
  'entity_text': '[1,2]-migration',
  'entity_type': 'mechanistic_term',
  'family_name': 'Stevens Rearrangement',
  'notes': 'Characteristic shift step that transfers carbon substituents from the onium center to the adjacent ylide '
           'carbon.',
  'page_label': 'p434'},
 {'canonical_name': 'sodium methoxide',
  'confidence': 0.88,
  'entity_text': 'NaOMe',
  'entity_type': 'abbreviation',
  'family_name': 'Stevens Rearrangement',
  'notes': 'Base used in the sulfonium-salt Stevens example shown on the overview page.',
  'page_label': 'p434'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': '5,7-fused isoindolo-benzazepine system',
  'entity_type': 'target_scaffold',
  'family_name': 'Stevens Rearrangement',
  'notes': 'Ring system generated by transition-metal-catalyzed diazo decomposition, in situ ylide formation, and '
           'Stevens rearrangement.',
  'page_label': 'p435'},
 {'canonical_name': '(±)-Desoxycodeine-D',
  'confidence': 0.85,
  'entity_text': '(±)-Desoxycodeine-D',
  'entity_type': 'target_molecule',
  'family_name': 'Stevens Rearrangement',
  'notes': 'Morphine-skeleton target assembled through rearrangement of a tetrahydroisoquinoline-derived quaternary '
           'ammonium salt.',
  'page_label': 'p435'},
 {'canonical_name': "1,2-(1,1'-ferrocenediyl)ethene",
  'confidence': 0.84,
  'entity_text': "1,2-(1,1'-ferrocenediyl)ethene",
  'entity_type': 'target_molecule',
  'family_name': 'Stevens Rearrangement',
  'notes': 'Strained ferrocenophene product obtained using a sulfonium-salt rearrangement strategy after '
           'Ramberg–Bäcklund attempts failed.',
  'page_label': 'p435'},
 {'canonical_name': '(P)-(+)-Pentahelicene',
  'confidence': 0.85,
  'entity_text': '(P)-(+)-Pentahelicene',
  'entity_type': 'target_molecule',
  'family_name': 'Stevens Rearrangement',
  'notes': 'Helicene target accessed through axial-to-central chirality transfer during a benzylic ammonium Stevens '
           'rearrangement.',
  'page_label': 'p435'},
 {'canonical_name': 'phenyllithium',
  'confidence': 0.89,
  'entity_text': 'PhLi',
  'entity_type': 'abbreviation',
  'family_name': 'Stevens Rearrangement',
  'notes': 'Strong base/nucleophile used to trigger the quaternary ammonium Stevens rearrangement in the '
           'desoxycodeine-D synthesis.',
  'page_label': 'p435'}]

def apply_frontmatter_batch49(db_path: str | Path) -> Dict[str, Any]:
    return apply_frontmatter_batch_generic(
        db_path=db_path,
        source_label=SOURCE_LABEL,
        version=FRONTMATTER_BATCH49_VERSION,
        latest_source_zip=LATEST_SOURCE_ZIP,
        batch_no=49,
        page_knowledge_seeds=PAGE_KNOWLEDGE_SEEDS,
        family_pattern_seeds=FAMILY_PATTERN_SEEDS,
        abbreviation_seeds=CURATED_BATCH49_ABBREVIATIONS,
        page_entity_seeds=PAGE_ENTITY_SEEDS,
        replace_existing_page_entities=False,
    )
