from __future__ import annotations

from pathlib import Path
from typing import Any, Dict

from app.labint_frontmatter_batch_restore_utils import (
    apply_frontmatter_batch_generic,
    load_abbreviation_seeds,
    load_family_pattern_seeds,
    load_page_knowledge_seeds,
)

FRONTMATTER_BATCH45_VERSION = 'labint_frontmatter_batch45_v1_20260412'
SOURCE_LABEL = 'named_reactions_frontmatter_batch45'
LATEST_SOURCE_ZIP = 'backend_batch15_45_frontmatter_cumulative_patch_20260412.zip'

PAGE_KNOWLEDGE_SEEDS = load_page_knowledge_seeds(45, SOURCE_LABEL)
FAMILY_PATTERN_SEEDS = load_family_pattern_seeds(45, FRONTMATTER_BATCH45_VERSION)
BATCH45_SOURCE_PAGES = {'BF3·OEt2': 393,
 'DMAP': 398,
 'HN3': 396,
 'MeCN': 395,
 'Pd(OAc)2': 390,
 'TMSCl': 390,
 'TMSOTf': 391,
 'TiCl4': 392,
 't-BuONO': 394}
CURATED_BATCH45_ABBREVIATIONS = load_abbreviation_seeds(
    45,
    SOURCE_LABEL,
    source_pages=BATCH45_SOURCE_PAGES,
    default_note='batch45 frontmatter abbreviation seed',
)
PAGE_ENTITY_SEEDS = [{'page_label': 'p390',
  'entity_text': 'Saegusa Oxidation',
  'canonical_name': 'Saegusa Oxidation',
  'entity_type': 'reaction_family',
  'family_name': 'Saegusa Oxidation',
  'notes': 'Overview page family anchor for the Saegusa oxidation.',
  'confidence': 0.93},
 {'page_label': 'p390',
  'entity_text': 'silyl enol ether',
  'canonical_name': None,
  'entity_type': 'reactant_class',
  'family_name': 'Saegusa Oxidation',
  'notes': 'Canonical substrate class that undergoes palladium-mediated dehydrogenation to enones.',
  'confidence': 0.86},
 {'page_label': 'p390',
  'entity_text': 'α,β-unsaturated ketone or aldehyde',
  'canonical_name': None,
  'entity_type': 'product_class',
  'family_name': 'Saegusa Oxidation',
  'notes': 'Characteristic product family formed after β-hydride elimination from the palladium '
           'intermediate.',
  'confidence': 0.86},
 {'page_label': 'p390',
  'entity_text': 'p-benzoquinone',
  'canonical_name': 'p-benzoquinone',
  'entity_type': 'oxidant',
  'family_name': 'Saegusa Oxidation',
  'notes': 'Common co-oxidant used in stoichiometric Saegusa conditions and depicted on the overview page.',
  'confidence': 0.84},
 {'page_label': 'p390',
  'entity_text': 'Pd(OAc)2',
  'canonical_name': 'palladium(II) acetate',
  'entity_type': 'abbreviation',
  'family_name': 'Saegusa Oxidation',
  'notes': 'Key palladium oxidant that defines the classical Saegusa oxidation.',
  'confidence': 0.9},
 {'page_label': 'p391',
  'entity_text': '(-)-Gambierol',
  'canonical_name': '(-)-Gambierol',
  'entity_type': 'target_molecule',
  'family_name': 'Saegusa Oxidation',
  'notes': 'Marine polycyclic ether target whose FGH tricyclic subunit was accessed using Saegusa oxidation.',
  'confidence': 0.86},
 {'page_label': 'p391',
  'entity_text': '(-)-Preussomerin G',
  'canonical_name': '(-)-Preussomerin G',
  'entity_type': 'target_molecule',
  'family_name': 'Saegusa Oxidation',
  'notes': 'Natural product featuring a cyclohexenone installed through Saegusa oxidation of a silyl enol '
           'ether.',
  'confidence': 0.85},
 {'page_label': 'p391',
  'entity_text': '(±)-8,14-Cedranoxide',
  'canonical_name': '(±)-8,14-Cedranoxide',
  'entity_type': 'target_molecule',
  'family_name': 'Saegusa Oxidation',
  'notes': 'Tricyclic cedranoid assembled after Larock-modified catalytic Saegusa oxidation.',
  'confidence': 0.84},
 {'page_label': 'p391',
  'entity_text': 'cis-fused 2,5-disubstituted octahydroquinoline',
  'canonical_name': None,
  'entity_type': 'target_scaffold',
  'family_name': 'Saegusa Oxidation',
  'notes': 'Octahydroquinoline core obtained after enone formation from a silyl enol ether precursor.',
  'confidence': 0.83},
 {'page_label': 'p392',
  'entity_text': 'Sakurai Allylation',
  'canonical_name': 'Sakurai Allylation',
  'entity_type': 'reaction_family',
  'family_name': 'Sakurai Allylation',
  'notes': 'Overview page family anchor for the Sakurai allylation.',
  'confidence': 0.93},
 {'page_label': 'p392',
  'entity_text': 'allylsilane',
  'canonical_name': None,
  'entity_type': 'reactant_class',
  'family_name': 'Sakurai Allylation',
  'notes': 'Canonical nucleophilic allyl donor used in the Hosomi-Sakurai reaction.',
  'confidence': 0.87},
 {'page_label': 'p392',
  'entity_text': 'Lewis-acid-activated carbonyl compound',
  'canonical_name': None,
  'entity_type': 'reactant_class',
  'family_name': 'Sakurai Allylation',
  'notes': 'Electrophile class encompassing aldehydes, ketones, acetals, and ketals activated toward '
           'allylation.',
  'confidence': 0.84},
 {'page_label': 'p392',
  'entity_text': 'homoallylic alcohol',
  'canonical_name': None,
  'entity_type': 'product_class',
  'family_name': 'Sakurai Allylation',
  'notes': 'Characteristic product class of allylsilane addition to aldehydes and ketones.',
  'confidence': 0.86},
 {'page_label': 'p392',
  'entity_text': 'TiCl4',
  'canonical_name': 'titanium tetrachloride',
  'entity_type': 'abbreviation',
  'family_name': 'Sakurai Allylation',
  'notes': 'One of the most common Lewis acids for promoting Sakurai allylation.',
  'confidence': 0.9},
 {'page_label': 'p393',
  'entity_text': 'Furaquinocin A',
  'canonical_name': 'Furaquinocin A',
  'entity_type': 'target_molecule',
  'family_name': 'Sakurai Allylation',
  'notes': 'Natural product intermediate assembled through diastereoselective Sakurai allylation.',
  'confidence': 0.85},
 {'page_label': 'p393',
  'entity_text': '(-)-Amphidinolide P',
  'canonical_name': '(-)-Amphidinolide P',
  'entity_type': 'target_molecule',
  'family_name': 'Sakurai Allylation',
  'notes': 'Macrocyclic target whose C7 hydroxyl and homoallyl side chain were installed through Sakurai '
           'allylation.',
  'confidence': 0.85},
 {'page_label': 'p393',
  'entity_text': '(-)-Laulimalide',
  'canonical_name': '(-)-Laulimalide',
  'entity_type': 'target_molecule',
  'family_name': 'Sakurai Allylation',
  'notes': 'Complex asymmetric allylation example enabled by a chiral acyloxyborane Lewis acid.',
  'confidence': 0.85},
 {'page_label': 'p393',
  'entity_text': 'BF3·OEt2',
  'canonical_name': 'boron trifluoride diethyl etherate',
  'entity_type': 'abbreviation',
  'family_name': 'Sakurai Allylation',
  'notes': 'Lewis acid used in several synthetic application examples on the Sakurai allylation page.',
  'confidence': 0.89},
 {'page_label': 'p394',
  'entity_text': 'Sandmeyer Reaction',
  'canonical_name': 'Sandmeyer Reaction',
  'entity_type': 'reaction_family',
  'family_name': 'Sandmeyer Reaction',
  'notes': 'Overview page family anchor for the Sandmeyer reaction.',
  'confidence': 0.93},
 {'page_label': 'p394',
  'entity_text': 'aryldiazonium halide',
  'canonical_name': None,
  'entity_type': 'intermediate_class',
  'family_name': 'Sandmeyer Reaction',
  'notes': 'Key aryl electrophile generated by diazotization prior to copper-mediated substitution.',
  'confidence': 0.86},
 {'page_label': 'p394',
  'entity_text': 'copper(I) salt',
  'canonical_name': None,
  'entity_type': 'reagent_class',
  'family_name': 'Sandmeyer Reaction',
  'notes': 'Classical promoter family used to install chloride, bromide, or nitrile on aromatic rings.',
  'confidence': 0.85},
 {'page_label': 'p394',
  'entity_text': 'aryl halide or nitrile',
  'canonical_name': None,
  'entity_type': 'product_class',
  'family_name': 'Sandmeyer Reaction',
  'notes': 'Canonical product family produced after dediazoniative substitution.',
  'confidence': 0.84},
 {'page_label': 'p394',
  'entity_text': 't-BuONO',
  'canonical_name': 'tert-butyl nitrite',
  'entity_type': 'abbreviation',
  'family_name': 'Sandmeyer Reaction',
  'notes': 'Organic nitrite frequently used for nonaqueous diazotization on sensitive substrates.',
  'confidence': 0.9},
 {'page_label': 'p395',
  'entity_text': 'Teicoplanin aglycone',
  'canonical_name': 'Teicoplanin aglycone',
  'entity_type': 'target_molecule',
  'family_name': 'Sandmeyer Reaction',
  'notes': 'Advanced glycopeptide intermediate bearing an aryl chloride introduced by Sandmeyer chemistry.',
  'confidence': 0.85},
 {'page_label': 'p395',
  'entity_text': 'Nemertelline',
  'canonical_name': 'Nemertelline',
  'entity_type': 'target_molecule',
  'family_name': 'Sandmeyer Reaction',
  'notes': 'Neurotoxic quaterpyridine natural product accessed from a Sandmeyer-prepared chloropyridine '
           'boronic acid precursor.',
  'confidence': 0.84},
 {'page_label': 'p395',
  'entity_text': '(±)-A80915G',
  'canonical_name': '(±)-A80915G',
  'entity_type': 'target_molecule',
  'family_name': 'Sandmeyer Reaction',
  'notes': 'Naphthyridinomycin-family target whose iodine substituent was introduced using the Sandmeyer '
           'reaction.',
  'confidence': 0.84},
 {'page_label': 'p395',
  'entity_text': 'aryl iodide',
  'canonical_name': None,
  'entity_type': 'product_class',
  'family_name': 'Sandmeyer Reaction',
  'notes': 'Important halogenated intermediate class highlighted in the synthetic applications.',
  'confidence': 0.83},
 {'page_label': 'p396',
  'entity_text': 'Schmidt Reaction',
  'canonical_name': 'Schmidt Reaction',
  'entity_type': 'reaction_family',
  'family_name': 'Schmidt Reaction',
  'notes': 'Overview page family anchor for the Schmidt reaction.',
  'confidence': 0.93},
 {'page_label': 'p396',
  'entity_text': 'hydrazoic acid',
  'canonical_name': 'hydrazoic acid',
  'entity_type': 'reagent',
  'family_name': 'Schmidt Reaction',
  'notes': 'Azide reagent that reacts with ketones, aldehydes, and carboxylic acids under acidic conditions.',
  'confidence': 0.88},
 {'page_label': 'p396',
  'entity_text': 'ketone, aldehyde, or carboxylic acid substrate',
  'canonical_name': None,
  'entity_type': 'reactant_class',
  'family_name': 'Schmidt Reaction',
  'notes': 'Main substrate manifold that undergoes azide addition and rearrangement.',
  'confidence': 0.84},
 {'page_label': 'p396',
  'entity_text': 'amide, lactam, amine, or nitrile product',
  'canonical_name': None,
  'entity_type': 'product_class',
  'family_name': 'Schmidt Reaction',
  'notes': 'Broad product space of the Schmidt reaction depending on substrate class and migration event.',
  'confidence': 0.84},
 {'page_label': 'p396',
  'entity_text': 'HN3',
  'canonical_name': 'hydrazoic acid',
  'entity_type': 'abbreviation',
  'family_name': 'Schmidt Reaction',
  'notes': 'Common shorthand for hydrazoic acid on the Schmidt reaction overview page.',
  'confidence': 0.9},
 {'page_label': 'p397',
  'entity_text': 'fully functionalized skeleton of lysergic acid',
  'canonical_name': None,
  'entity_type': 'target_scaffold',
  'family_name': 'Schmidt Reaction',
  'notes': 'Complex bicyclic framework assembled through an intramolecular Schmidt-type cycloaddition '
           'pathway.',
  'confidence': 0.84},
 {'page_label': 'p397',
  'entity_text': '(+)-Methylxanthoxylol',
  'canonical_name': '(+)-Methylxanthoxylol',
  'entity_type': 'target_molecule',
  'family_name': 'Schmidt Reaction',
  'notes': 'Natural product reached from a deacylative diazo transfer sequence terminating in '
           'rhodium-mediated cycloaddition.',
  'confidence': 0.84},
 {'page_label': 'p397',
  'entity_text': 'carbocyclic [6-7] core of guanacastepenes',
  'canonical_name': None,
  'entity_type': 'target_scaffold',
  'family_name': 'Schmidt Reaction',
  'notes': 'Ring system forged from diazo carbonyl chemistry linked to a Schmidt-type sequence.',
  'confidence': 0.83},
 {'page_label': 'p397',
  'entity_text': 'A58365A',
  'canonical_name': 'A58365A',
  'entity_type': 'target_molecule',
  'family_name': 'Schmidt Reaction',
  'notes': 'Pyridone acid target prepared via diazo-imide chemistry and rhodium-catalyzed cycloaddition '
           'preceding functionalization.',
  'confidence': 0.83},
 {'page_label': 'p398',
  'entity_text': 'Schotten-Baumann Reaction',
  'canonical_name': 'Schotten-Baumann Reaction',
  'entity_type': 'reaction_family',
  'family_name': 'Schotten-Baumann Reaction',
  'notes': 'Overview page family anchor for the Schotten-Baumann reaction.',
  'confidence': 0.93},
 {'page_label': 'p398',
  'entity_text': 'acyl halide or anhydride',
  'canonical_name': None,
  'entity_type': 'reactant_class',
  'family_name': 'Schotten-Baumann Reaction',
  'notes': 'Electrophile class used for interfacial acylation of amines and alcohols.',
  'confidence': 0.86},
 {'page_label': 'p398',
  'entity_text': 'amine or alcohol nucleophile',
  'canonical_name': None,
  'entity_type': 'reactant_class',
  'family_name': 'Schotten-Baumann Reaction',
  'notes': 'Substrate class acylated under aqueous base or related Schotten-Baumann conditions.',
  'confidence': 0.84},
 {'page_label': 'p398',
  'entity_text': 'amide or ester product',
  'canonical_name': None,
  'entity_type': 'product_class',
  'family_name': 'Schotten-Baumann Reaction',
  'notes': 'Characteristic acylation products of the Schotten-Baumann manifold.',
  'confidence': 0.84},
 {'page_label': 'p398',
  'entity_text': 'DMAP',
  'canonical_name': '4-dimethylaminopyridine',
  'entity_type': 'abbreviation',
  'family_name': 'Schotten-Baumann Reaction',
  'notes': 'Representative acylation catalyst mentioned among modern Schotten-Baumann modifications.',
  'confidence': 0.89},
 {'page_label': 'p399',
  'entity_text': '(-)-Tejedine',
  'canonical_name': '(-)-Tejedine',
  'entity_type': 'target_molecule',
  'family_name': 'Schotten-Baumann Reaction',
  'notes': 'Alkaloid target assembled using chiral-auxiliary-assisted amide formation under Schotten-Baumann '
           'conditions.',
  'confidence': 0.85},
 {'page_label': 'p399',
  'entity_text': 'Fumiquinazoline G',
  'canonical_name': 'Fumiquinazoline G',
  'entity_type': 'target_molecule',
  'family_name': 'Schotten-Baumann Reaction',
  'notes': 'Fumiquinazoline alkaloid whose peptide bond was forged efficiently under biphasic carbonate '
           'conditions.',
  'confidence': 0.84},
 {'page_label': 'p399',
  'entity_text': 'ceramide with a thienyl sphingoid moiety',
  'canonical_name': None,
  'entity_type': 'target_scaffold',
  'family_name': 'Schotten-Baumann Reaction',
  'notes': 'Ceramide analogue produced by selective amino-diol acylation with hexanoyl chloride.',
  'confidence': 0.83},
 {'page_label': 'p399',
  'entity_text': '(+)-Cannabisativine',
  'canonical_name': '(+)-Cannabisativine',
  'entity_type': 'target_molecule',
  'family_name': 'Schotten-Baumann Reaction',
  'notes': 'First asymmetric synthesis used Schotten-Baumann amidation of a bicyclic acid chloride with a '
           'diamino alcohol.',
  'confidence': 0.84}]


def apply_frontmatter_batch45(db_path: str | Path) -> Dict[str, Any]:
    return apply_frontmatter_batch_generic(
        db_path=db_path,
        source_label=SOURCE_LABEL,
        version=FRONTMATTER_BATCH45_VERSION,
        latest_source_zip=LATEST_SOURCE_ZIP,
        batch_no=45,
        page_knowledge_seeds=PAGE_KNOWLEDGE_SEEDS,
        family_pattern_seeds=FAMILY_PATTERN_SEEDS,
        abbreviation_seeds=CURATED_BATCH45_ABBREVIATIONS,
        page_entity_seeds=PAGE_ENTITY_SEEDS,
        replace_existing_page_entities=False,
    )
