from __future__ import annotations

from pathlib import Path
from typing import Any, Dict

from app.labint_frontmatter_batch_restore_utils import (
    apply_frontmatter_batch_generic,
    load_abbreviation_seeds,
    load_family_pattern_seeds,
    load_page_knowledge_seeds,
)

FRONTMATTER_BATCH21_VERSION = 'labint_frontmatter_batch21_v1_20260412'
SOURCE_LABEL = 'named_reactions_frontmatter_batch21'
LATEST_SOURCE_ZIP = 'backend_batch15_21_frontmatter_cumulative_patch_20260412.zip'

PAGE_KNOWLEDGE_SEEDS = load_page_knowledge_seeds(21, SOURCE_LABEL)
FAMILY_PATTERN_SEEDS = load_family_pattern_seeds(21, FRONTMATTER_BATCH21_VERSION)
BATCH21_SOURCE_PAGES = {'Al2O3': 155,
 'Bu2BOTf': 162,
 'DBU': 155,
 'DIPEA': 163,
 'DMA-DMA': 156,
 'DMP': 159,
 "Eschenmoser's salt": 154,
 'Et3N': 163,
 'HCHO': 160,
 'HCO2H': 160,
 'Hg(CF3CO2)2': 159,
 'LDA': 155,
 'LiAlH4': 159,
 'LiHMDS': 155,
 'LiTMP': 155,
 'NaBH3CN': 161,
 'TBAF': 155,
 'TsNHNH2': 158,
 'mCPBA': 155,
 'xylene': 157}
CURATED_BATCH21_ABBREVIATIONS = load_abbreviation_seeds(
    21,
    SOURCE_LABEL,
    source_pages=BATCH21_SOURCE_PAGES,
    default_note='batch21 frontmatter abbreviation seed',
)
PAGE_ENTITY_SEEDS = [{'canonical_name': 'Eschenmoser Methenylation',
  'confidence': 0.92,
  'entity_text': 'Eschenmoser Methenylation',
  'entity_type': 'reaction_family',
  'family_name': 'Eschenmoser Methenylation',
  'notes': 'Named alpha-methylenation family overview.',
  'page_label': 'p154'},
 {'canonical_name': 'dimethylmethyleneammonium iodide',
  'confidence': 0.88,
  'entity_text': "Eschenmoser's salt",
  'entity_type': 'reagent',
  'family_name': 'Eschenmoser Methenylation',
  'notes': 'Characteristic methylene-transfer reagent highlighted on the overview page.',
  'page_label': 'p154'},
 {'canonical_name': None,
  'confidence': 0.85,
  'entity_text': 'alpha-Methylenated carbonyl compound',
  'entity_type': 'product_class',
  'family_name': 'Eschenmoser Methenylation',
  'notes': 'Canonical product class formed after elimination from the aminomethylated '
           'intermediate.',
  'page_label': 'p154'},
 {'canonical_name': 'Eschenmoser Methenylation',
  'confidence': 0.92,
  'entity_text': 'Eschenmoser Methenylation',
  'entity_type': 'reaction_family',
  'family_name': 'Eschenmoser Methenylation',
  'notes': 'Application page family anchor.',
  'page_label': 'p155'},
 {'canonical_name': None,
  'confidence': 0.86,
  'entity_text': 'exo-Methylene hydroazulenone',
  'entity_type': 'target_molecule',
  'family_name': 'Eschenmoser Methenylation',
  'notes': 'Hydroazulenone target produced through Eschenmoser methenylation.',
  'page_label': 'p155'},
 {'canonical_name': '(+)-Crassin acetate methyl ether',
  'confidence': 0.85,
  'entity_text': 'Crassin acetate methyl ether',
  'entity_type': 'target_molecule',
  'family_name': 'Eschenmoser Methenylation',
  'notes': 'Cembranoid natural-product target featuring late-stage alpha-methylene installation.',
  'page_label': 'p155'},
 {'canonical_name': 'Eschenmoser-Claisen Rearrangement',
  'confidence': 0.92,
  'entity_text': 'Eschenmoser-Claisen Rearrangement',
  'entity_type': 'reaction_family',
  'family_name': 'Eschenmoser-Claisen Rearrangement',
  'notes': 'Named amide-Claisen rearrangement family overview.',
  'page_label': 'p156'},
 {'canonical_name': None,
  'confidence': 0.87,
  'entity_text': 'ketene aminal',
  'entity_type': 'intermediate_class',
  'family_name': 'Eschenmoser-Claisen Rearrangement',
  'notes': 'Reactive ketene aminal / ketene N,O-acetal intermediate shown in the mechanism.',
  'page_label': 'p156'},
 {'canonical_name': None,
  'confidence': 0.85,
  'entity_text': 'gamma,delta-Unsaturated amide',
  'entity_type': 'product_class',
  'family_name': 'Eschenmoser-Claisen Rearrangement',
  'notes': 'Characteristic rearrangement product class generated from allylic alcohol precursors.',
  'page_label': 'p156'},
 {'canonical_name': 'Eschenmoser-Claisen Rearrangement',
  'confidence': 0.92,
  'entity_text': 'Eschenmoser-Claisen Rearrangement',
  'entity_type': 'reaction_family',
  'family_name': 'Eschenmoser-Claisen Rearrangement',
  'notes': 'Application page family anchor.',
  'page_label': 'p157'},
 {'canonical_name': '(+)-Stenine',
  'confidence': 0.86,
  'entity_text': '(+)-Stenine',
  'entity_type': 'target_molecule',
  'family_name': 'Eschenmoser-Claisen Rearrangement',
  'notes': 'Alkaloid target assembled using an intramolecular Diels–Alder / Eschenmoser–Claisen '
           'sequence.',
  'page_label': 'p157'},
 {'canonical_name': '(+)-Pravastatin',
  'confidence': 0.85,
  'entity_text': '(+)-Pravastatin',
  'entity_type': 'target_molecule',
  'family_name': 'Eschenmoser-Claisen Rearrangement',
  'notes': 'Application target in which a stereocenter was introduced through the rearrangement.',
  'page_label': 'p157'},
 {'canonical_name': 'Eschenmoser-Tanabe Fragmentation',
  'confidence': 0.92,
  'entity_text': 'Eschenmoser-Tanabe Fragmentation',
  'entity_type': 'reaction_family',
  'family_name': 'Eschenmoser-Tanabe Fragmentation',
  'notes': 'Named epoxyketone fragmentation family overview.',
  'page_label': 'p158'},
 {'canonical_name': None,
  'confidence': 0.87,
  'entity_text': 'cyclic alkynone',
  'entity_type': 'product_class',
  'family_name': 'Eschenmoser-Tanabe Fragmentation',
  'notes': 'Medium-sized cyclic alkynone product class emphasized in the overview scheme.',
  'page_label': 'p158'},
 {'canonical_name': None,
  'confidence': 0.85,
  'entity_text': 'acyclic alkynal or alkynone',
  'entity_type': 'product_class',
  'family_name': 'Eschenmoser-Tanabe Fragmentation',
  'notes': 'Open-chain alkyne-containing product class accessible from epoxy ketone hydrazones.',
  'page_label': 'p158'},
 {'canonical_name': 'Eschenmoser-Tanabe Fragmentation',
  'confidence': 0.92,
  'entity_text': 'Eschenmoser-Tanabe Fragmentation',
  'entity_type': 'reaction_family',
  'family_name': 'Eschenmoser-Tanabe Fragmentation',
  'notes': 'Application page family anchor.',
  'page_label': 'p159'},
 {'canonical_name': 'Galbulimima alkaloid GB 13',
  'confidence': 0.86,
  'entity_text': 'Galbulimima alkaloid GB 13',
  'entity_type': 'target_molecule',
  'family_name': 'Eschenmoser-Tanabe Fragmentation',
  'notes': 'Alkaloid synthesis application featuring epoxyketone fragmentation to an alkynone.',
  'page_label': 'p159'},
 {'canonical_name': None,
  'confidence': 0.85,
  'entity_text': 'Enol lactone',
  'entity_type': 'product_class',
  'family_name': 'Eschenmoser-Tanabe Fragmentation',
  'notes': 'Elastase-inhibitor-oriented enol lactone product accessed from a fragmented alkynone '
           'precursor.',
  'page_label': 'p159'},
 {'canonical_name': 'Eschweiler-Clarke Methylation',
  'confidence': 0.92,
  'entity_text': 'Eschweiler-Clarke Methylation',
  'entity_type': 'reaction_family',
  'family_name': 'Eschweiler-Clarke Methylation',
  'notes': 'Named reductive methylation family overview.',
  'page_label': 'p160'},
 {'canonical_name': 'Leuckart-Wallach Reaction',
  'confidence': 0.87,
  'entity_text': 'Leuckart-Wallach Reaction',
  'entity_type': 'related_reaction',
  'family_name': 'Eschweiler-Clarke Methylation',
  'notes': 'Related reductive alkylation family explicitly compared on the overview page.',
  'page_label': 'p160'},
 {'canonical_name': None,
  'confidence': 0.85,
  'entity_text': 'N-Methylated amine',
  'entity_type': 'product_class',
  'family_name': 'Eschweiler-Clarke Methylation',
  'notes': 'Canonical tertiary-amine product class formed under Eschweiler-Clarke conditions.',
  'page_label': 'p160'},
 {'canonical_name': 'Eschweiler-Clarke Methylation',
  'confidence': 0.92,
  'entity_text': 'Eschweiler-Clarke Methylation',
  'entity_type': 'reaction_family',
  'family_name': 'Eschweiler-Clarke Methylation',
  'notes': 'Application page family anchor.',
  'page_label': 'p161'},
 {'canonical_name': '(S)-N-Methylanabasine',
  'confidence': 0.86,
  'entity_text': '(S)-N-Methylanabasine',
  'entity_type': 'target_molecule',
  'family_name': 'Eschweiler-Clarke Methylation',
  'notes': 'Tobacco alkaloid target obtained through deprotection-hydrogenation-Eschweiler-Clarke '
           'methylation.',
  'page_label': 'p161'},
 {'canonical_name': '(-)-Horsfiline',
  'confidence': 0.85,
  'entity_text': '(-)-Horsfiline',
  'entity_type': 'target_molecule',
  'family_name': 'Eschweiler-Clarke Methylation',
  'notes': 'Oxindole alkaloid target featuring mild reductive methylation at a late stage.',
  'page_label': 'p161'},
 {'canonical_name': 'Evans Aldol Reaction',
  'confidence': 0.92,
  'entity_text': 'Evans Aldol Reaction',
  'entity_type': 'reaction_family',
  'family_name': 'Evans Aldol Reaction',
  'notes': 'Named boron-mediated aldol family overview.',
  'page_label': 'p162'},
 {'canonical_name': None,
  'confidence': 0.87,
  'entity_text': 'Z-enolate',
  'entity_type': 'intermediate_class',
  'family_name': 'Evans Aldol Reaction',
  'notes': 'Boron enolate geometry that controls the syn-selective aldol addition.',
  'page_label': 'p162'},
 {'canonical_name': None,
  'confidence': 0.85,
  'entity_text': 'Zimmerman-Traxler transition state',
  'entity_type': 'mechanistic_concept',
  'family_name': 'Evans Aldol Reaction',
  'notes': 'Chairlike transition-state model used to rationalize the observed syn '
           'diastereoselectivity.',
  'page_label': 'p162'},
 {'canonical_name': 'Evans Aldol Reaction',
  'confidence': 0.92,
  'entity_text': 'Evans Aldol Reaction',
  'entity_type': 'reaction_family',
  'family_name': 'Evans Aldol Reaction',
  'notes': 'Application page family anchor.',
  'page_label': 'p163'},
 {'canonical_name': 'Glucolipsin A',
  'confidence': 0.86,
  'entity_text': 'Glucolipsin A',
  'entity_type': 'target_molecule',
  'family_name': 'Evans Aldol Reaction',
  'notes': 'Macrolide target whose stereochemistry was secured via syn-selective Evans aldol '
           'chemistry.',
  'page_label': 'p163'},
 {'canonical_name': '(-)-FR182877',
  'confidence': 0.85,
  'entity_text': '(-)-FR182877',
  'entity_type': 'target_molecule',
  'family_name': 'Evans Aldol Reaction',
  'notes': 'Complex natural product assembled using a boron-mediated Evans aldol addition to set '
           'absolute stereochemistry.',
  'page_label': 'p163'}]


def apply_frontmatter_batch21(db_path: str | Path) -> Dict[str, Any]:
    return apply_frontmatter_batch_generic(
        db_path=db_path,
        source_label=SOURCE_LABEL,
        version=FRONTMATTER_BATCH21_VERSION,
        latest_source_zip=LATEST_SOURCE_ZIP,
        batch_no=21,
        page_knowledge_seeds=PAGE_KNOWLEDGE_SEEDS,
        family_pattern_seeds=FAMILY_PATTERN_SEEDS,
        abbreviation_seeds=CURATED_BATCH21_ABBREVIATIONS,
        page_entity_seeds=PAGE_ENTITY_SEEDS,
    )


if __name__ == '__main__':
    from pprint import pprint
    pprint(apply_frontmatter_batch21(Path(__file__).resolve().parent / 'labint.db'))
