from __future__ import annotations

from pathlib import Path
from typing import Any, Dict

from app.labint_frontmatter_batch_restore_utils import (
    apply_frontmatter_batch_generic,
    load_abbreviation_seeds,
    load_family_pattern_seeds,
    load_page_knowledge_seeds,
)

FRONTMATTER_BATCH43_VERSION = 'labint_frontmatter_batch43_v1_20260412'
SOURCE_LABEL = 'named_reactions_frontmatter_batch43'
LATEST_SOURCE_ZIP = 'backend_batch15_43_frontmatter_cumulative_patch_20260412.zip'

PAGE_KNOWLEDGE_SEEDS = load_page_knowledge_seeds(43, SOURCE_LABEL)
FAMILY_PATTERN_SEEDS = load_family_pattern_seeds(43, FRONTMATTER_BATCH43_VERSION)
BATCH43_SOURCE_PAGES = {'CHCl3': 378,
 'HMPA': 373,
 'LAH': 371,
 'MVK': 371,
 'NCS': 373,
 'Pd/C': 379,
 'SmI2': 375,
 'p-ABSA': 377}
CURATED_BATCH43_ABBREVIATIONS = load_abbreviation_seeds(
    43,
    SOURCE_LABEL,
    source_pages=BATCH43_SOURCE_PAGES,
    default_note='batch43 frontmatter abbreviation seed',
)
PAGE_ENTITY_SEEDS = [{'canonical_name': 'Quasi-Favorskii Rearrangement',
  'confidence': 0.92,
  'entity_text': 'Quasi-Favorskii Rearrangement',
  'entity_type': 'reaction_family',
  'family_name': 'Quasi-Favorskii Rearrangement',
  'notes': 'Overview page family anchor for the quasi-favorskii rearrangement.',
  'page_label': 'p370'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'non-enolizable α-halo ketone + nucleophile/base',
  'entity_type': 'reactant_class',
  'family_name': 'Quasi-Favorskii Rearrangement',
  'notes': 'Canonical substrate class for quasi-Favorskii chemistry in which the α-halo ketone '
           'cannot access a normal Favorskii enolate pathway.',
  'page_label': 'p370'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'carboxylic acid derivative after semibenzilic-type migration',
  'entity_type': 'product_class',
  'family_name': 'Quasi-Favorskii Rearrangement',
  'notes': 'Typical acid or carbonyl-derived product formed after rearrangement of an α-halo '
           'ketone under nucleophilic conditions.',
  'page_label': 'p370'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'ring-contracted cyclic or bicyclic carbonyl homologue',
  'entity_type': 'product_class',
  'family_name': 'Quasi-Favorskii Rearrangement',
  'notes': 'Alternative product or skeletal outcome emphasized for this rearrangement manifold.',
  'page_label': 'p370'},
 {'canonical_name': 'Quasi-Favorskii Rearrangement',
  'confidence': 0.92,
  'entity_text': 'Quasi-Favorskii Rearrangement',
  'entity_type': 'reaction_family',
  'family_name': 'Quasi-Favorskii Rearrangement',
  'notes': 'Application page family anchor.',
  'page_label': 'p371'},
 {'canonical_name': 'epi-Modhephene',
  'confidence': 0.85,
  'entity_text': 'epi-Modhephene',
  'entity_type': 'target_molecule',
  'family_name': 'Quasi-Favorskii Rearrangement',
  'notes': 'Terpene target assembled from a bicyclo[3.3.0]octane intermediate created through '
           'quasi-Favorskii rearrangement of a bridgehead bromide.',
  'page_label': 'p371'},
 {'canonical_name': 'Polycyclic ring system',
  'confidence': 0.85,
  'entity_text': 'Polycyclic ring system',
  'entity_type': 'target_molecule',
  'family_name': 'Quasi-Favorskii Rearrangement',
  'notes': 'Rapidly constructed tricyclic framework obtained after sequential [4+3] cycloaddition '
           'and quasi-Favorskii rearrangement of an α-bromo ketone.',
  'page_label': 'p371'},
 {'canonical_name': '(±)-Spatol',
  'confidence': 0.85,
  'entity_text': '(±)-Spatol',
  'entity_type': 'target_molecule',
  'family_name': 'Quasi-Favorskii Rearrangement',
  'notes': 'Racemic natural product reached through quasi-Favorskii ring contraction of a '
           'bridgehead bromoketone precursor.',
  'page_label': 'p371'},
 {'canonical_name': '(±)-Sterpurene',
  'confidence': 0.85,
  'entity_text': '(±)-Sterpurene',
  'entity_type': 'target_molecule',
  'family_name': 'Quasi-Favorskii Rearrangement',
  'notes': 'Tricyclic terpene prepared by intermolecular [4+3] cycloaddition followed by '
           'bridgehead α-bromo ketone quasi-Favorskii rearrangement.',
  'page_label': 'p371'},
 {'canonical_name': 'Ramberg-Bäcklund Rearrangement',
  'confidence': 0.92,
  'entity_text': 'Ramberg-Bäcklund Rearrangement',
  'entity_type': 'reaction_family',
  'family_name': 'Ramberg-Bäcklund Rearrangement',
  'notes': 'Overview page family anchor for the ramberg-bäcklund rearrangement.',
  'page_label': 'p372'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'α-halosulfone + base/heat',
  'entity_type': 'reactant_class',
  'family_name': 'Ramberg-Bäcklund Rearrangement',
  'notes': 'Canonical precursor class in which α-halosulfones are converted into alkenes under '
           'basic conditions.',
  'page_label': 'p372'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'alkene after SO2 extrusion',
  'entity_type': 'product_class',
  'family_name': 'Ramberg-Bäcklund Rearrangement',
  'notes': 'Characteristic alkene product resulting from episulfone formation and sulfur dioxide '
           'extrusion.',
  'page_label': 'p372'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'ring-contracted cyclic alkene from a cyclic sulfone',
  'entity_type': 'product_class',
  'family_name': 'Ramberg-Bäcklund Rearrangement',
  'notes': 'Alternative product or skeletal outcome emphasized for this rearrangement manifold.',
  'page_label': 'p372'},
 {'canonical_name': 'Ramberg-Bäcklund Rearrangement',
  'confidence': 0.92,
  'entity_text': 'Ramberg-Bäcklund Rearrangement',
  'entity_type': 'reaction_family',
  'family_name': 'Ramberg-Bäcklund Rearrangement',
  'notes': 'Application page family anchor.',
  'page_label': 'p373'},
 {'canonical_name': '(+)-Solamin',
  'confidence': 0.85,
  'entity_text': '(+)-Solamin',
  'entity_type': 'target_molecule',
  'family_name': 'Ramberg-Bäcklund Rearrangement',
  'notes': 'Acetogenin target prepared through Meyers-modified Ramberg-Bäcklund rearrangement '
           'after in situ chlorination of a sulfone precursor.',
  'page_label': 'p373'},
 {'canonical_name': '(+)-Eremantholide A',
  'confidence': 0.85,
  'entity_text': '(+)-Eremantholide A',
  'entity_type': 'target_molecule',
  'family_name': 'Ramberg-Bäcklund Rearrangement',
  'notes': 'Sesquiterpene target whose 10-membered macrocycle was closed by Ramberg-Bäcklund ring '
           'contraction.',
  'page_label': 'p373'},
 {'canonical_name': '(+)-Estradiol',
  'confidence': 0.85,
  'entity_text': '(+)-Estradiol',
  'entity_type': 'target_molecule',
  'family_name': 'Ramberg-Bäcklund Rearrangement',
  'notes': 'Steroid framework accessed by benzanulation followed by Ramberg-Bäcklund rearrangement '
           'of a TMS-substituted thiophene-derived sulfone.',
  'page_label': 'p373'},
 {'canonical_name': 'Manzamine C',
  'confidence': 0.85,
  'entity_text': 'Manzamine C',
  'entity_type': 'target_molecule',
  'family_name': 'Ramberg-Bäcklund Rearrangement',
  'notes': 'Marine alkaloid reached through stereoselective formation of an azacycloundecene ring '
           'via strong-base-induced Ramberg-Bäcklund rearrangement.',
  'page_label': 'p373'},
 {'canonical_name': 'Reformatsky Reaction',
  'confidence': 0.92,
  'entity_text': 'Reformatsky Reaction',
  'entity_type': 'reaction_family',
  'family_name': 'Reformatsky Reaction',
  'notes': 'Overview page family anchor for the reformatsky reaction.',
  'page_label': 'p374'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'α-halo ester + aldehyde or ketone under Zn or other metal activation',
  'entity_type': 'reactant_class',
  'family_name': 'Reformatsky Reaction',
  'notes': 'Canonical substrate pairing for the Reformatsky addition manifold that creates '
           'carbon–carbon bonds from α-halo ester pronucleophiles.',
  'page_label': 'p374'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'β-hydroxy ester',
  'entity_type': 'product_class',
  'family_name': 'Reformatsky Reaction',
  'notes': 'Characteristic aldol-type product of the Reformatsky reaction formed after acidic '
           'work-up of a metal enolate addition product.',
  'page_label': 'p374'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'β-keto ester via the Blaise reaction',
  'entity_type': 'product_class',
  'family_name': 'Reformatsky Reaction',
  'notes': 'Alternative product or skeletal outcome emphasized for this rearrangement manifold.',
  'page_label': 'p374'},
 {'canonical_name': 'Reformatsky Reaction',
  'confidence': 0.92,
  'entity_text': 'Reformatsky Reaction',
  'entity_type': 'reaction_family',
  'family_name': 'Reformatsky Reaction',
  'notes': 'Application page family anchor.',
  'page_label': 'p375'},
 {'canonical_name': 'C(16),C(18)-bis-epi-Cytochalasin D',
  'confidence': 0.85,
  'entity_text': 'C(16),C(18)-bis-epi-Cytochalasin D',
  'entity_type': 'target_molecule',
  'family_name': 'Reformatsky Reaction',
  'notes': 'Macrocyclic natural-product framework closed using a sodium-naphthalide-activated zinc '
           'Reformatsky reaction.',
  'page_label': 'p375'},
 {'canonical_name': 'F-H ring framework of decacyclic ciguatoxin model',
  'confidence': 0.85,
  'entity_text': 'F-H ring framework of decacyclic ciguatoxin model',
  'entity_type': 'target_molecule',
  'family_name': 'Reformatsky Reaction',
  'notes': 'SmI2-mediated intramolecular Reformatsky cyclization forged the fused oxononane system '
           'of a ciguatoxin model.',
  'page_label': 'p375'},
 {'canonical_name': 'C1-C6 Fragment of epothilones',
  'confidence': 0.85,
  'entity_text': 'C1-C6 Fragment of epothilones',
  'entity_type': 'target_molecule',
  'family_name': 'Reformatsky Reaction',
  'notes': 'Catalytic CrCl2-promoted Reformatsky coupling delivered the epothilone fragment with '
           'high chemoselectivity and diastereocontrol.',
  'page_label': 'p375'},
 {'canonical_name': 'Dolaproine',
  'confidence': 0.85,
  'entity_text': 'Dolaproine',
  'entity_type': 'target_molecule',
  'family_name': 'Reformatsky Reaction',
  'notes': 'Amino-acid unit of dolastatin 10 prepared through cobalt-promoted Reformatsky addition '
           'on a Boc-protected precursor.',
  'page_label': 'p375'},
 {'canonical_name': 'Regitz Diazo Transfer',
  'confidence': 0.92,
  'entity_text': 'Regitz Diazo Transfer',
  'entity_type': 'reaction_family',
  'family_name': 'Regitz Diazo Transfer',
  'notes': 'Overview page family anchor for the regitz diazo transfer.',
  'page_label': 'p376'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'active methylene β-dicarbonyl compound + sulfonyl azide/base',
  'entity_type': 'reactant_class',
  'family_name': 'Regitz Diazo Transfer',
  'notes': 'Canonical donor–acceptor pairing for Regitz diazo transfer in which a deprotonated '
           'active methylene compound traps a sulfonyl azide.',
  'page_label': 'p376'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'α-diazo-β-dicarbonyl compound',
  'entity_type': 'product_class',
  'family_name': 'Regitz Diazo Transfer',
  'notes': 'Characteristic diazo-bearing carbonyl product obtained from the transfer process.',
  'page_label': 'p376'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'α-diazo ketone via deformylative diazo transfer',
  'entity_type': 'product_class',
  'family_name': 'Regitz Diazo Transfer',
  'notes': 'Alternative product or skeletal outcome emphasized for this rearrangement manifold.',
  'page_label': 'p376'},
 {'canonical_name': 'Regitz Diazo Transfer',
  'confidence': 0.92,
  'entity_text': 'Regitz Diazo Transfer',
  'entity_type': 'reaction_family',
  'family_name': 'Regitz Diazo Transfer',
  'notes': 'Application page family anchor.',
  'page_label': 'p377'},
 {'canonical_name': 'Fully functionalized skeleton of lysergic acid',
  'confidence': 0.85,
  'entity_text': 'Fully functionalized skeleton of lysergic acid',
  'entity_type': 'target_molecule',
  'family_name': 'Regitz Diazo Transfer',
  'notes': 'Cycloaddition precursor for lysergic acid synthesis obtained after standard Regitz '
           'diazo-transfer conditions and rhodium-catalyzed cycloaddition.',
  'page_label': 'p377'},
 {'canonical_name': '(+)-Methylxanthoxylol',
  'confidence': 0.85,
  'entity_text': '(+)-Methylxanthoxylol',
  'entity_type': 'target_molecule',
  'family_name': 'Regitz Diazo Transfer',
  'notes': 'Natural product reached after deacylative diazo transfer on a butyrolactone precursor '
           'followed by C–H insertion chemistry.',
  'page_label': 'p377'},
 {'canonical_name': '[6-7] carbocyclic core of guanacastepenes',
  'confidence': 0.85,
  'entity_text': '[6-7] carbocyclic core of guanacastepenes',
  'entity_type': 'target_molecule',
  'family_name': 'Regitz Diazo Transfer',
  'notes': 'Core carbocycle assembled through intramolecular reaction of a diazo-carbonyl '
           'substrate prepared by Regitz diazo transfer.',
  'page_label': 'p377'},
 {'canonical_name': 'A58365A',
  'confidence': 0.85,
  'entity_text': 'A58365A',
  'entity_type': 'target_molecule',
  'family_name': 'Regitz Diazo Transfer',
  'notes': 'ACE-inhibitor scaffold synthesized through intramolecular [3+2] cycloaddition of a '
           'diazo imide generated by diazo transfer.',
  'page_label': 'p377'},
 {'canonical_name': 'Reimer-Tiemann Reaction',
  'confidence': 0.92,
  'entity_text': 'Reimer-Tiemann Reaction',
  'entity_type': 'reaction_family',
  'family_name': 'Reimer-Tiemann Reaction',
  'notes': 'Overview page family anchor for the reimer-tiemann reaction.',
  'page_label': 'p378'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'phenol or pyrrole + CHCl3/base',
  'entity_type': 'reactant_class',
  'family_name': 'Reimer-Tiemann Reaction',
  'notes': 'Canonical substrate class for Reimer-Tiemann formylation in which a phenoxide or '
           'heteroaromatic anion intercepts dichlorocarbene generated from chloroform and base.',
  'page_label': 'p378'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'ortho-formyl phenol',
  'entity_type': 'product_class',
  'family_name': 'Reimer-Tiemann Reaction',
  'notes': 'Characteristic aldehyde product formed after hydrolysis and tautomerization of the '
           'dichlorocarbene adduct.',
  'page_label': 'p378'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'abnormal dichloromethyl cyclohexadienone or 3-chloropyridine product',
  'entity_type': 'product_class',
  'family_name': 'Reimer-Tiemann Reaction',
  'notes': 'Alternative product or skeletal outcome emphasized for this rearrangement manifold.',
  'page_label': 'p378'},
 {'canonical_name': 'Reimer-Tiemann Reaction',
  'confidence': 0.92,
  'entity_text': 'Reimer-Tiemann Reaction',
  'entity_type': 'reaction_family',
  'family_name': 'Reimer-Tiemann Reaction',
  'notes': 'Application page family anchor.',
  'page_label': 'p379'},
 {'canonical_name': '(±)-β-Copaene',
  'confidence': 0.85,
  'entity_text': '(±)-β-Copaene',
  'entity_type': 'target_molecule',
  'family_name': 'Reimer-Tiemann Reaction',
  'notes': 'Sesquiterpene target accessed from carvacrol after abnormal Reimer-Tiemann reaction to '
           'a dichloromethyl cyclohexadienone and subsequent cyclization.',
  'page_label': 'p379'},
 {'canonical_name': '7-Acetylamino-2-chloro-[1,8]naphthyridine-3-carboxylic acid ethyl ester',
  'confidence': 0.85,
  'entity_text': '7-Acetylamino-2-chloro-[1,8]naphthyridine-3-carboxylic acid ethyl ester',
  'entity_type': 'target_molecule',
  'family_name': 'Reimer-Tiemann Reaction',
  'notes': 'Host–guest system building block whose synthesis began with Reimer-Tiemann formylation '
           'of 2,6-diaminopyridine.',
  'page_label': 'p379'},
 {'canonical_name': 'Methoxy derivative of indatraline',
  'confidence': 0.85,
  'entity_text': 'Methoxy derivative of indatraline',
  'entity_type': 'target_molecule',
  'family_name': 'Reimer-Tiemann Reaction',
  'notes': 'Monoamine-transporter ligand assembled from a dichlorophenol precursor formylated '
           'under Reimer-Tiemann conditions.',
  'page_label': 'p379'},
 {'canonical_name': '(±)-trans-5-Carboxytrimethyleneoxy-enterolactone',
  'confidence': 0.85,
  'entity_text': '(±)-trans-5-Carboxytrimethyleneoxy-enterolactone',
  'entity_type': 'target_molecule',
  'family_name': 'Reimer-Tiemann Reaction',
  'notes': 'Radioimmunoassay hapten prepared through Reimer-Tiemann formylation of a '
           'benzyloxyphenol intermediate.',
  'page_label': 'p379'}]


def apply_frontmatter_batch43(db_path: str | Path) -> Dict[str, Any]:
    return apply_frontmatter_batch_generic(
        db_path=db_path,
        source_label=SOURCE_LABEL,
        version=FRONTMATTER_BATCH43_VERSION,
        latest_source_zip=LATEST_SOURCE_ZIP,
        batch_no=43,
        page_knowledge_seeds=PAGE_KNOWLEDGE_SEEDS,
        family_pattern_seeds=FAMILY_PATTERN_SEEDS,
        abbreviation_seeds=CURATED_BATCH43_ABBREVIATIONS,
        page_entity_seeds=PAGE_ENTITY_SEEDS,
    )
