from __future__ import annotations
from pathlib import Path
from typing import Any, Dict

from app.labint_frontmatter_batch_restore_utils import (
    apply_frontmatter_batch_generic,
    load_abbreviation_seeds,
    load_family_pattern_seeds,
    load_page_knowledge_seeds,
)

FRONTMATTER_BATCH48_VERSION = 'labint_frontmatter_batch48_v1_20260412'
SOURCE_LABEL = 'named_reactions_frontmatter_batch48'
LATEST_SOURCE_ZIP = 'backend_batch15_48_frontmatter_cumulative_patch_20260412.zip'

PAGE_KNOWLEDGE_SEEDS = load_page_knowledge_seeds(48, SOURCE_LABEL)
FAMILY_PATTERN_SEEDS = load_family_pattern_seeds(48, FRONTMATTER_BATCH48_VERSION)
BATCH48_SOURCE_PAGES = {'AcOH': 421,
 'BF3·OEt2': 426,
 'Bu3P': 429,
 'CIPE': 420,
 'CsF': 423,
 'CuBr': 424,
 'CuI': 424,
 'DBU': 423,
 'DoM': 420,
 'EtAlCl2': 427,
 'HMPA': 422,
 'LDA': 421,
 'NaNH2': 422,
 'POCl3': 427,
 'PPh3': 428,
 'Pd(PPh3)2Cl2': 424,
 'Pd(PPh3)4': 424,
 'TMEDA': 420,
 'n-BuLi': 420,
 'sec-BuLi': 421}
CURATED_BATCH48_ABBREVIATIONS = load_abbreviation_seeds(
    48,
    SOURCE_LABEL,
    source_pages=BATCH48_SOURCE_PAGES,
    default_note='batch48 frontmatter abbreviation seed',
)
PAGE_ENTITY_SEEDS = [{'canonical_name': 'Snieckus Directed Ortho Metalation',
  'confidence': 0.93,
  'entity_text': 'Snieckus Directed Ortho Metalation',
  'entity_type': 'reaction_family',
  'family_name': 'Snieckus Directed Ortho Metalation',
  'notes': 'Overview page family anchor for directed ortho lithiation/metallation chemistry popularized by Snieckus.',
  'page_label': 'p420'},
 {'canonical_name': 'directed ortho metalation',
  'confidence': 0.91,
  'entity_text': 'DoM',
  'entity_type': 'abbreviation',
  'family_name': 'Snieckus Directed Ortho Metalation',
  'notes': 'Common acronym for the Snieckus-directed ortho metalation strategy.',
  'page_label': 'p420'},
 {'canonical_name': 'complex-induced proximity effect',
  'confidence': 0.9,
  'entity_text': 'CIPE',
  'entity_type': 'abbreviation',
  'family_name': 'Snieckus Directed Ortho Metalation',
  'notes': 'Mechanistic concept describing precomplexation-guided deprotonation next to a directing metalation group.',
  'page_label': 'p420'},
 {'canonical_name': 'n-butyllithium',
  'confidence': 0.9,
  'entity_text': 'n-BuLi',
  'entity_type': 'abbreviation',
  'family_name': 'Snieckus Directed Ortho Metalation',
  'notes': 'Principal alkyllithium base used for the overview DoM conditions.',
  'page_label': 'p420'},
 {'canonical_name': 'tetramethylethylenediamine',
  'confidence': 0.89,
  'entity_text': 'TMEDA',
  'entity_type': 'abbreviation',
  'family_name': 'Snieckus Directed Ortho Metalation',
  'notes': 'Lewis-basic additive that breaks up organolithium aggregates and enhances ortho metalation.',
  'page_label': 'p420'},
 {'canonical_name': 'Gilvocarcin M aglycone',
  'confidence': 0.86,
  'entity_text': 'Gilvocarcin M aglycone',
  'entity_type': 'target_molecule',
  'family_name': 'Snieckus Directed Ortho Metalation',
  'notes': 'A glycosylated aromatic natural-product aglycone assembled through directed ortho metalation and remote metalation chemistry.',
  'page_label': 'p421'},
 {'canonical_name': 'Suzuki cross-coupling',
  'confidence': 0.84,
  'entity_text': 'Suzuki cross-coupling',
  'entity_type': 'related_method',
  'family_name': 'Snieckus Directed Ortho Metalation',
  'notes': 'Used after directed iodination of the lithiated intermediate in the gilvocarcin application.',
  'page_label': 'p421'},
 {'canonical_name': 'Veiutamine',
  'confidence': 0.85,
  'entity_text': 'Veiutamine',
  'entity_type': 'target_molecule',
  'family_name': 'Snieckus Directed Ortho Metalation',
  'notes': 'Marine alkaloid synthesized by C6 lithiation of a pyrroloiminoquinoline nucleus followed by aldehyde trapping.',
  'page_label': 'p421'},
 {'canonical_name': '(S)-Camptothecin',
  'confidence': 0.86,
  'entity_text': '(S)-Camptothecin',
  'entity_type': 'target_molecule',
  'family_name': 'Snieckus Directed Ortho Metalation',
  'notes': 'Practical synthesis using sequential lithiation, in situ aminoalkoxide generation, and iodination.',
  'page_label': 'p421'},
 {'canonical_name': 'anionic ortho-Fries rearrangement',
  'confidence': 0.83,
  'entity_text': 'ortho-Fries rearrangement',
  'entity_type': 'related_method',
  'family_name': 'Snieckus Directed Ortho Metalation',
  'notes': 'Remote metalation/anionic ortho-Fries process invoked in the gilvocarcin application page.',
  'page_label': 'p421'},
 {'canonical_name': 'Sommelet-Hauser Rearrangement',
  'confidence': 0.93,
  'entity_text': 'Sommelet-Hauser Rearrangement',
  'entity_type': 'reaction_family',
  'family_name': 'Sommelet-Hauser Rearrangement',
  'notes': 'Overview page family anchor for rearrangement of benzylic quaternary ammonium ylides.',
  'page_label': 'p422'},
 {'canonical_name': 'Stevens rearrangement',
  'confidence': 0.88,
  'entity_text': 'Stevens rearrangement',
  'entity_type': 'related_method',
  'family_name': 'Sommelet-Hauser Rearrangement',
  'notes': 'Major competing pathway that often accompanies nitrogen-ylide generation from quaternary ammonium salts.',
  'page_label': 'p422'},
 {'canonical_name': None,
  'confidence': 0.87,
  'entity_text': 'nitrogen ylide',
  'entity_type': 'intermediate_class',
  'family_name': 'Sommelet-Hauser Rearrangement',
  'notes': 'Reactive intermediate generated by deprotonation of benzylic quaternary ammonium salts before [2,3]-shift.',
  'page_label': 'p422'},
 {'canonical_name': 'sodium amide',
  'confidence': 0.9,
  'entity_text': 'NaNH2',
  'entity_type': 'abbreviation',
  'family_name': 'Sommelet-Hauser Rearrangement',
  'notes': 'Strong base commonly employed to generate the ammonium ylide under classic S.-H. conditions.',
  'page_label': 'p422'},
 {'canonical_name': 'hexamethylphosphoramide',
  'confidence': 0.89,
  'entity_text': 'HMPA',
  'entity_type': 'abbreviation',
  'family_name': 'Sommelet-Hauser Rearrangement',
  'notes': 'Polar additive that can favor Sommelet-Hauser rearrangement over Stevens pathways.',
  'page_label': 'p422'},
 {'canonical_name': 'Streptonigrin',
  'confidence': 0.85,
  'entity_text': 'Streptonigrin',
  'entity_type': 'target_molecule',
  'family_name': 'Sommelet-Hauser Rearrangement',
  'notes': 'Antibiotic natural product prepared through modified Sommelet-Hauser rearrangement of a cyanomethylpyrrolidinium salt.',
  'page_label': 'p423'},
 {'canonical_name': '6-Methyl-5,6,7,12-tetrahydro-dibenzo[c,f]azocine',
  'confidence': 0.84,
  'entity_text': '6-Methyl-5,6,7,12-tetrahydro-dibenzo[c,f]azocine',
  'entity_type': 'target_scaffold',
  'family_name': 'Sommelet-Hauser Rearrangement',
  'notes': 'Ring-expanded azocine framework obtained under nonbasic ylide-generation conditions.',
  'page_label': 'p423'},
 {'canonical_name': 'methyl 7-chloroindole-4-carboxylate',
  'confidence': 0.84,
  'entity_text': 'methyl 7-chloroindole-4-carboxylate',
  'entity_type': 'target_molecule',
  'family_name': 'Sommelet-Hauser Rearrangement',
  'notes': 'Indole prepared from an aromatic sulfilimine via sulfonium ylide formation and rearrangement.',
  'page_label': 'p423'},
 {'canonical_name': None,
  'confidence': 0.83,
  'entity_text': 'indolin-2(3H)-one derivative',
  'entity_type': 'target_scaffold',
  'family_name': 'Sommelet-Hauser Rearrangement',
  'notes': 'Regioisomeric tetrahydrophthalimide-substituted indolinone herbicide candidates accessed through sulfonium ylide '
           'rearrangement.',
  'page_label': 'p423'},
 {'canonical_name': 'cesium fluoride',
  'confidence': 0.88,
  'entity_text': 'CsF',
  'entity_type': 'abbreviation',
  'family_name': 'Sommelet-Hauser Rearrangement',
  'notes': 'Fluoride source used for nonbasic desilylation-based ylide generation in the azocine application.',
  'page_label': 'p423'},
 {'canonical_name': 'Sonogashira Cross-Coupling',
  'confidence': 0.93,
  'entity_text': 'Sonogashira Cross-Coupling',
  'entity_type': 'reaction_family',
  'family_name': 'Sonogashira Cross-Coupling',
  'notes': 'Overview page family anchor for Pd/Cu-catalyzed alkyne cross-coupling.',
  'page_label': 'p424'},
 {'canonical_name': 'bis(triphenylphosphine)palladium(II) chloride',
  'confidence': 0.9,
  'entity_text': 'Pd(PPh3)2Cl2',
  'entity_type': 'abbreviation',
  'family_name': 'Sonogashira Cross-Coupling',
  'notes': 'Common palladium precatalyst listed on the overview page.',
  'page_label': 'p424'},
 {'canonical_name': 'tetrakis(triphenylphosphine)palladium(0)',
  'confidence': 0.9,
  'entity_text': 'Pd(PPh3)4',
  'entity_type': 'abbreviation',
  'family_name': 'Sonogashira Cross-Coupling',
  'notes': 'Palladium(0) precursor highlighted for Sonogashira coupling conditions.',
  'page_label': 'p424'},
 {'canonical_name': 'copper(I) iodide',
  'confidence': 0.9,
  'entity_text': 'CuI',
  'entity_type': 'abbreviation',
  'family_name': 'Sonogashira Cross-Coupling',
  'notes': 'Typical copper cocatalyst for terminal alkyne activation in Sonogashira coupling.',
  'page_label': 'p424'},
 {'canonical_name': 'Castro-Stephens coupling',
  'confidence': 0.84,
  'entity_text': 'Castro-Stephens coupling',
  'entity_type': 'related_method',
  'family_name': 'Sonogashira Cross-Coupling',
  'notes': 'Historical copper-mediated alkyne coupling used as a comparison point for the Sonogashira reaction.',
  'page_label': 'p424'},
 {'canonical_name': '(−)-Heliannuol E',
  'confidence': 0.85,
  'entity_text': '(−)-Heliannuol E',
  'entity_type': 'target_molecule',
  'family_name': 'Sonogashira Cross-Coupling',
  'notes': 'Sesquiterpenoid natural product constructed through aryl iodide coupling with propargyl alcohol.',
  'page_label': 'p425'},
 {'canonical_name': 'Mappicine',
  'confidence': 0.85,
  'entity_text': 'Mappicine',
  'entity_type': 'target_molecule',
  'family_name': 'Sonogashira Cross-Coupling',
  'notes': 'Formally synthesized by Sonogashira introduction of an acetylenic unit at C2 of a quinoline precursor.',
  'page_label': 'p425'},
 {'canonical_name': 'N1999-A2 proposed structure',
  'confidence': 0.84,
  'entity_text': 'Proposed structure of N1999-A2',
  'entity_type': 'target_molecule',
  'family_name': 'Sonogashira Cross-Coupling',
  'notes': 'Highly strained enediyne structure assembled by fragment coupling under Sonogashira conditions.',
  'page_label': 'p425'},
 {'canonical_name': 'Callipeltoside aglycon',
  'confidence': 0.84,
  'entity_text': 'Callipeltoside aglycon',
  'entity_type': 'target_molecule',
  'family_name': 'Sonogashira Cross-Coupling',
  'notes': 'Late-stage dienyne assembled efficiently by switching from Pd(PPh3)4 to Pd(PPh3)2Cl2.',
  'page_label': 'p425'},
 {'canonical_name': 'copper(I) bromide',
  'confidence': 0.88,
  'entity_text': 'CuBr',
  'entity_type': 'abbreviation',
  'family_name': 'Sonogashira Cross-Coupling',
  'notes': 'Alternative copper cocatalyst shown on the overview page and in applications.',
  'page_label': 'p425'},
 {'canonical_name': 'Staudinger Ketene Cycloaddition',
  'confidence': 0.93,
  'entity_text': 'Staudinger Ketene Cycloaddition',
  'entity_type': 'reaction_family',
  'family_name': 'Staudinger Ketene Cycloaddition',
  'notes': 'Overview page family anchor for ketene [2+2] cycloaddition chemistry.',
  'page_label': 'p426'},
 {'canonical_name': None,
  'confidence': 0.86,
  'entity_text': 'β-Lactam',
  'entity_type': 'product_class',
  'family_name': 'Staudinger Ketene Cycloaddition',
  'notes': 'Characteristic product class formed in ketene-imine cycloaddition reactions.',
  'page_label': 'p426'},
 {'canonical_name': None,
  'confidence': 0.85,
  'entity_text': 'cyclobutanone derivative',
  'entity_type': 'product_class',
  'family_name': 'Staudinger Ketene Cycloaddition',
  'notes': 'Characteristic product class formed from ketene-alkene [2+2] cycloaddition.',
  'page_label': 'p426'},
 {'canonical_name': 'boron trifluoride etherate',
  'confidence': 0.88,
  'entity_text': 'BF3·OEt2',
  'entity_type': 'abbreviation',
  'family_name': 'Staudinger Ketene Cycloaddition',
  'notes': 'Typical Lewis acid used for ketene reactions with carbonyl compounds or imines.',
  'page_label': 'p426'},
 {'canonical_name': None,
  'confidence': 0.85,
  'entity_text': 'ketene-imine cycloaddition',
  'entity_type': 'mechanistic_motif',
  'family_name': 'Staudinger Ketene Cycloaddition',
  'notes': 'Specific ketene cycloaddition mode that furnishes β-lactams with high diastereocontrol.',
  'page_label': 'p426'},
 {'canonical_name': '(+)-Bakkenolide A',
  'confidence': 0.85,
  'entity_text': '(+)-Bakkenolide A',
  'entity_type': 'target_molecule',
  'family_name': 'Staudinger Ketene Cycloaddition',
  'notes': 'Natural product synthesized via dichloroketene cycloaddition with 1,6-dimethylcyclohexene.',
  'page_label': 'p427'},
 {'canonical_name': 'Sarracenin',
  'confidence': 0.84,
  'entity_text': 'Sarracenin',
  'entity_type': 'target_molecule',
  'family_name': 'Staudinger Ketene Cycloaddition',
  'notes': 'Iridoid monoterpene precursor assembled through fulvene–ketene [2+2] cycloaddition and rearrangement.',
  'page_label': 'p427'},
 {'canonical_name': 'Pentacyclic framework of Ecteinascidin-743',
  'confidence': 0.85,
  'entity_text': 'Pentacyclic framework of Ecteinascidin-743',
  'entity_type': 'target_scaffold',
  'family_name': 'Staudinger Ketene Cycloaddition',
  'notes': 'Chiral ketene-imine cycloaddition used to set the stereochemistry of a β-lactam intermediate.',
  'page_label': 'p427'},
 {'canonical_name': '(−)-Lipstatin',
  'confidence': 0.84,
  'entity_text': '(−)-Lipstatin',
  'entity_type': 'target_molecule',
  'family_name': 'Staudinger Ketene Cycloaddition',
  'notes': 'Aldehyde–ketene cycloaddition under EtAlCl2 activation delivers the four-membered intermediate en route to the antiobesity '
           'agent.',
  'page_label': 'p427'},
 {'canonical_name': 'diethylaluminum chloride',
  'confidence': 0.88,
  'entity_text': 'EtAlCl2',
  'entity_type': 'abbreviation',
  'family_name': 'Staudinger Ketene Cycloaddition',
  'notes': 'Lewis acid activator used in the aldehyde–ketene cycloaddition leading to lipstatin.',
  'page_label': 'p427'},
 {'canonical_name': 'Staudinger Reaction',
  'confidence': 0.93,
  'entity_text': 'Staudinger Reaction',
  'entity_type': 'reaction_family',
  'family_name': 'Staudinger Reaction',
  'notes': 'Overview page family anchor for phosphine-mediated azide reduction and iminophosphorane formation.',
  'page_label': 'p428'},
 {'canonical_name': None,
  'confidence': 0.89,
  'entity_text': 'iminophosphorane',
  'entity_type': 'intermediate_class',
  'family_name': 'Staudinger Reaction',
  'notes': 'Key aza-ylide intermediate formed after phosphazide extrusion of dinitrogen.',
  'page_label': 'p428'},
 {'canonical_name': 'aza-Wittig reaction',
  'confidence': 0.87,
  'entity_text': 'aza-Wittig reaction',
  'entity_type': 'related_method',
  'family_name': 'Staudinger Reaction',
  'notes': 'Transformations of iminophosphoranes with carbonyl compounds to form imines are highlighted on the overview page.',
  'page_label': 'p428'},
 {'canonical_name': 'triphenylphosphine',
  'confidence': 0.9,
  'entity_text': 'PPh3',
  'entity_type': 'abbreviation',
  'family_name': 'Staudinger Reaction',
  'notes': 'Classical phosphine reagent for the Staudinger reaction and azide reduction.',
  'page_label': 'p428'},
 {'canonical_name': None,
  'confidence': 0.86,
  'entity_text': 'phosphazide',
  'entity_type': 'intermediate_class',
  'family_name': 'Staudinger Reaction',
  'notes': 'Initial adduct of the azide with the phosphine before nitrogen extrusion.',
  'page_label': 'p428'},
 {'canonical_name': '(−)-Hennoxazole A',
  'confidence': 0.85,
  'entity_text': '(−)-Hennoxazole A',
  'entity_type': 'target_molecule',
  'family_name': 'Staudinger Reaction',
  'notes': 'Marine antiviral natural product synthesized using wet-solvent Staudinger reduction of a secondary alkyl azide.',
  'page_label': 'p429'},
 {'canonical_name': '(+)-Hamacanthin B',
  'confidence': 0.85,
  'entity_text': '(+)-Hamacanthin B',
  'entity_type': 'target_molecule',
  'family_name': 'Staudinger Reaction',
  'notes': 'Marine indole alkaloid prepared using tandem Staudinger reduction and intramolecular aza-Wittig cyclization.',
  'page_label': 'p429'},
 {'canonical_name': 'Mycosporin-Gly',
  'confidence': 0.84,
  'entity_text': 'Mycosporin-Gly',
  'entity_type': 'target_molecule',
  'family_name': 'Staudinger Reaction',
  'notes': 'Fungal metabolite structure confirmed by azide reduction to an iminophosphorane followed by imine capture and reduction.',
  'page_label': 'p429'},
 {'canonical_name': 'Staudinger ligation',
  'confidence': 0.86,
  'entity_text': 'Staudinger ligation',
  'entity_type': 'named_variant',
  'family_name': 'Staudinger Reaction',
  'notes': 'Biocompatible ligation between an aryl azide and α-carboalkoxy triarylphosphine highlighted by the O-methyl imidate example.',
  'page_label': 'p429'},
 {'canonical_name': 'tributylphosphine',
  'confidence': 0.89,
  'entity_text': 'Bu3P',
  'entity_type': 'abbreviation',
  'family_name': 'Staudinger Reaction',
  'notes': 'More nucleophilic trialkylphosphine used in the hamacanthin B application.',
  'page_label': 'p429'}]

def apply_frontmatter_batch48(db_path: str | Path) -> Dict[str, Any]:
    return apply_frontmatter_batch_generic(
        db_path=db_path,
        source_label=SOURCE_LABEL,
        version=FRONTMATTER_BATCH48_VERSION,
        latest_source_zip=LATEST_SOURCE_ZIP,
        batch_no=48,
        page_knowledge_seeds=PAGE_KNOWLEDGE_SEEDS,
        family_pattern_seeds=FAMILY_PATTERN_SEEDS,
        abbreviation_seeds=CURATED_BATCH48_ABBREVIATIONS,
        page_entity_seeds=PAGE_ENTITY_SEEDS,
        replace_existing_page_entities=False,
    )
