
from __future__ import annotations
import sqlite3
from pathlib import Path
from typing import Any, Dict
from app.labint_frontmatter import ensure_frontmatter_schema, normalize_key

FRONTMATTER_BATCH10_VERSION = 'labint_frontmatter_batch10_v1_20260411'
PAGE_KNOWLEDGE_SEEDS = [
    {'source_label':'named_reactions_frontmatter_batch10','page_label':'p52','page_no':52,'title':'Benzilic Acid Rearrangement – Importance and Mechanism','section_name':'VII. Named Organic Reactions in Alphabetical Order','page_kind':'canonical_overview','summary':'Overview page for the benzilic acid rearrangement describing base-induced rearrangement of alpha-diketones into alpha-hydroxy carboxylic acid salts through nucleophilic addition, 1,2-shift, and proton-transfer steps. The page also highlights ring-contraction variants and retro-benzilic acid rearrangements in cyclic systems.','family_names':'Benzilic Acid Rearrangement','reference_family_name':'Benzilic Acid Rearrangement','notes':'Emphasizes hydroxide or alkoxide attack on diketones, irreversible migration, and formation of alpha-hydroxy acid products from acyclic or cyclic alpha-diketones.','image_filename':'named reactions_104.jpg'},
    {'source_label':'named_reactions_frontmatter_batch10','page_label':'p53','page_no':53,'title':'Benzilic Acid Rearrangement – Synthetic Applications','section_name':'VII. Named Organic Reactions in Alphabetical Order','page_kind':'application_example','summary':'Application page for the benzilic acid rearrangement featuring ring-contraction of a pyranosylated indolocarbazole toward the carbohydrate moiety of (+)-K252a, steroidal ketolactol rearrangement to a novel 5-ring D-homosteroid, retro-benzilic acid access to hinesol and agarospirol, and rearrangement routes to shinjulactone derivatives.','family_names':'Benzilic Acid Rearrangement','reference_family_name':'Benzilic Acid Rearrangement','notes':'Applications stress ring contraction, skeletal editing, and base-controlled migration in complex natural-product frameworks.','image_filename':'named reactions_105.jpg'},
    {'source_label':'named_reactions_frontmatter_batch10','page_label':'p54','page_no':54,'title':'Benzoin and Retro-Benzoin Condensation – Importance and Mechanism','section_name':'VII. Named Organic Reactions in Alphabetical Order','page_kind':'canonical_overview','summary':'Overview page for the benzoin and retro-benzoin condensation describing cyanide- or thiazolium-catalyzed umpolung coupling of aldehydes to alpha-hydroxy ketones and the reverse fragmentation of benzoins back to carbonyl compounds. The mechanism highlights cyanohydrin-type activation, Breslow-type thiazolium intermediates, proton transfer, and catalyst turnover.','family_names':'Benzoin and Retro-Benzoin Condensation','reference_family_name':'Benzoin and Retro-Benzoin Condensation','notes':'The page frames classical cyanide catalysis and modern thiazolium/NHC catalysis as complementary benzoin manifolds, with retro-benzoin cleavage as a useful ketone-forming strategy.','image_filename':'named reactions_106.jpg'},
    {'source_label':'named_reactions_frontmatter_batch10','page_label':'p55','page_no':55,'title':'Benzoin and Retro-Benzoin Condensation – Synthetic Applications','section_name':'VII. Named Organic Reactions in Alphabetical Order','page_kind':'application_example','summary':'Application page for the benzoin and retro-benzoin condensation featuring ketone synthesis via cleavage of alpha-benzyloins, access to 2-substituted quinazolines, catalytic crossed aldehyde-ketone benzoin condensation to functionalized preanthraquinones, and benzoin-based assembly of diarylimidazoles.','family_names':'Benzoin and Retro-Benzoin Condensation','reference_family_name':'Benzoin and Retro-Benzoin Condensation','notes':'Applications show both constructive C-C bond formation and retro-benzoin fragmentation logic in heteroaromatic and medicinally relevant settings.','image_filename':'named reactions_107.jpg'},
    {'source_label':'named_reactions_frontmatter_batch10','page_label':'p56','page_no':56,'title':'Bergman Cycloaromatization Reaction – Importance and Mechanism','section_name':'VII. Named Organic Reactions in Alphabetical Order','page_kind':'canonical_overview','summary':'Overview page for the Bergman cycloaromatization reaction describing thermal or metal-assisted cycloaromatization of enediynes to benzenoid diradicals that abstract hydrogen atoms from donors such as cyclohexadiene. The page emphasizes distance and geometry requirements of the enediyne and the relevance of the resulting diradical to DNA-cleaving natural products.','family_names':'Bergman Cycloaromatization Reaction','reference_family_name':'Bergman Cycloaromatization Reaction','notes':'Focuses on enediyne-to-aromatic conversion, benzenoid diradical formation, and conditions such as 150-200 °C or Mg2+-induced cyclization.','image_filename':'named reactions_108.jpg'},
    {'source_label':'named_reactions_frontmatter_batch10','page_label':'p57','page_no':57,'title':'Bergman Cycloaromatization Reaction – Synthetic Applications','section_name':'VII. Named Organic Reactions in Alphabetical Order','page_kind':'application_example','summary':'Application page for the Bergman cycloaromatization reaction featuring 10-membered pyrimidine enediynes, [n]phenacenoporphyrins, calicheamicin/speramicin-inspired trisulfide-triggered cyclizations, 7-methyl-2-methylene-acenaphthen-1-ol, and 2-tert-butylperylene.','family_names':'Bergman Cycloaromatization Reaction','reference_family_name':'Bergman Cycloaromatization Reaction','notes':'Applications highlight triggerable enediyne activation and rapid fused-ring construction from the initially formed diradical.','image_filename':'named reactions_109.jpg'},
    {'source_label':'named_reactions_frontmatter_batch10','page_label':'p58','page_no':58,'title':'Biginelli Reaction – Importance and Mechanism','section_name':'VII. Named Organic Reactions in Alphabetical Order','page_kind':'canonical_overview','summary':'Overview page for the Biginelli reaction describing acid-catalyzed three-component condensation of an aldehyde, a beta-keto ester, and urea or thiourea to give dihydropyrimidinones or related heterocycles. The mechanism features N-acyliminium-ion formation, enolized beta-keto ester attack, and cyclodehydration.','family_names':'Biginelli Reaction','reference_family_name':'Biginelli Reaction','notes':'The page collects classical and modified Biginelli conditions, including Atwal and Shuvalov-type variants, and emphasizes DHPM synthesis.','image_filename':'named reactions_110.jpg'},
    {'source_label':'named_reactions_frontmatter_batch10','page_label':'p59','page_no':59,'title':'Biginelli Reaction – Synthetic Applications','section_name':'VII. Named Organic Reactions in Alphabetical Order','page_kind':'application_example','summary':'Application page for the Biginelli reaction featuring total syntheses of isocrambescidin 800, monastrol, and batzelladine F through tethered or intermolecular multicomponent condensation strategies.','family_names':'Biginelli Reaction','reference_family_name':'Biginelli Reaction','notes':'Applications show enantioselective/tethered Biginelli manifolds and medicinally relevant DHPM scaffolds.','image_filename':'named reactions_111.jpg'},
    {'source_label':'named_reactions_frontmatter_batch10','page_label':'p60','page_no':60,'title':'Birch Reduction – Importance and Mechanism','section_name':'VII. Named Organic Reactions in Alphabetical Order','page_kind':'canonical_overview','summary':'Overview page for the Birch reduction describing dissolving-metal reduction of aromatic rings or electron-poor heteroarenes with alkali metals in liquid ammonia and an alcohol proton source to give unconjugated cyclohexadienes or partially reduced heterocycles. The mechanism proceeds through sequential electron transfer, radical anion formation, protonation, and regiocontrolled second electron/proton delivery.','family_names':'Birch Reduction','reference_family_name':'Birch Reduction','notes':'Highlights substituent-dependent regioselectivity, use of Li or Na in NH3(l), and applicability to pyridines, furans, and related systems under electron-withdrawing substitution.','image_filename':'named reactions_112.jpg'},
    {'source_label':'named_reactions_frontmatter_batch10','page_label':'p61','page_no':61,'title':'Birch Reduction – Synthetic Applications','section_name':'VII. Named Organic Reactions in Alphabetical Order','page_kind':'application_example','summary':'Application page for the Birch reduction featuring syntheses of (-)-taxol, (+)-apovincamine, galbulimima alkaloid GB 13, substituted 2-pyrrolines, and (+)-nemorensic acid through regioselective arene or heteroarene reduction and Birch reductive alkylation.','family_names':'Birch Reduction','reference_family_name':'Birch Reduction','notes':'Applications demonstrate Birch reductive alkylation, oxygenation after partial reduction, and strategic dearomatization in complex natural-product settings.','image_filename':'named reactions_113.jpg'}
]
CURATED_BATCH10_ABBREVIATIONS = [
    {'alias':'NaOH','canonical_name':'sodium hydroxide','entity_type':'base','source_page':52},
    {'alias':'CuCl','canonical_name':'copper(I) chloride','entity_type':'additive','source_page':52},
    {'alias':'CTAP','canonical_name':'cetyltrimethylammonium permanganate','entity_type':'oxidant','source_page':53},
    {'alias':'KCN','canonical_name':'potassium cyanide','entity_type':'catalyst','source_page':54},
    {'alias':'NaCN','canonical_name':'sodium cyanide','entity_type':'catalyst','source_page':54},
    {'alias':'DBU','canonical_name':'1,8-diazabicyclo[5.4.0]undec-7-ene','entity_type':'base','source_page':55},
    {'alias':'MgCl2','canonical_name':'magnesium chloride','entity_type':'metal_salt','source_page':56},
    {'alias':'AIBN','canonical_name':'azobisisobutyronitrile','entity_type':'radical_initiator','source_page':57},
    {'alias':'Bu3SnH','canonical_name':'tributyltin hydride','entity_type':'reagent','source_page':57},
    {'alias':'HCl','canonical_name':'hydrochloric acid','entity_type':'acid','source_page':58},
    {'alias':'FeCl3','canonical_name':'iron(III) chloride','entity_type':'Lewis_acid','source_page':58},
    {'alias':'BF3·OEt2','canonical_name':'boron trifluoride diethyl etherate','entity_type':'Lewis_acid','source_page':58},
    {'alias':'Yb(OTf)3','canonical_name':'ytterbium(III) triflate','entity_type':'Lewis_acid','source_page':59},
    {'alias':'NH3(l)','canonical_name':'liquid ammonia','entity_type':'solvent','source_page':60},
    {'alias':'t-BuOH','canonical_name':'tert-butanol','entity_type':'proton_source','source_page':61},
]
FAMILY_PATTERN_SEEDS = [
    {'family_name':'Benzilic Acid Rearrangement','family_class':'named_reaction','transformation_type':'1,2-rearrangement / ring contraction','mechanism_type':'nucleophilic addition followed by 1,2-shift','reactant_pattern_text':'acyclic or cyclic alpha-diketone under basic conditions','product_pattern_text':'alpha-hydroxy carboxylic acid salt or ring-contracted alpha-hydroxy acid','key_reagents_clue':'NaOH, alkoxides, amide bases, hydroxide attack on diketones','common_solvents':'aqueous alcohols, methanol, basic media','common_conditions':'base-promoted rearrangement; protonation on workup','synonym_names':'benzilic acid rearrangement; retro-benzilic acid rearrangement','description_short':'Base-induced rearrangement of alpha-diketones to alpha-hydroxy acid derivatives with migratory ring contraction variants.','overview_count':1,'application_count':1,'mechanism_count':1},
    {'family_name':'Benzoin and Retro-Benzoin Condensation','family_class':'named_reaction','transformation_type':'umpolung C-C bond formation / retro-fragmentation','mechanism_type':'cyanide or thiazolium/NHC catalysis','reactant_pattern_text':'aldehydes, glyoxals, or alpha-hydroxy ketones under cyanide or thiazolium catalysis','product_pattern_text':'benzoin products or retro-benzoin cleavage products such as ketones and aldehydes','key_reagents_clue':'KCN, NaCN, thiazolium salts, NHC catalysts, DBU','common_solvents':'DMF, THF, alcohols, basic media','common_conditions':'cyanide catalysis or thiazolium catalysis with proton-transfer sequence','synonym_names':'benzoin condensation; retro-benzoin condensation','description_short':'Classical umpolung coupling of aldehydes to benzoins and the reverse fragmentation logic used for ketone synthesis.','overview_count':1,'application_count':1,'mechanism_count':1},
    {'family_name':'Bergman Cycloaromatization Reaction','family_class':'named_reaction','transformation_type':'enediyne cycloaromatization','mechanism_type':'diradical cyclization','reactant_pattern_text':'enediyne or enediyne-like system','product_pattern_text':'benzenoid diradical trapped to an aromatic product','key_reagents_clue':'heat, cyclohexadiene hydrogen donor, MgCl2, benzene','common_solvents':'benzene, methanol, hydrogen-donor media','common_conditions':'thermal or metal-induced cycloaromatization of enediynes','synonym_names':'Bergman cyclization; Bergman cycloaromatization','description_short':'Cycloaromatization of enediynes to benzenoid diradicals that rapidly abstract hydrogen atoms and build aromatic frameworks.','overview_count':1,'application_count':1,'mechanism_count':1},
    {'family_name':'Biginelli Reaction','family_class':'named_reaction','transformation_type':'multicomponent heterocycle synthesis','mechanism_type':'N-acyliminium mediated cyclocondensation','reactant_pattern_text':'aldehyde + beta-keto ester + urea/thiourea','product_pattern_text':'dihydropyrimidinone or related DHPM heterocycle','key_reagents_clue':'HCl, FeCl3, BF3·OEt2, Yb(OTf)3, urea, thiourea','common_solvents':'ethanol, THF, DMF, refluxing alcohols','common_conditions':'acid- or Lewis-acid-catalyzed one-pot three-component condensation','synonym_names':'Biginelli condensation; DHPM synthesis','description_short':'Three-component condensation used to build dihydropyrimidinones from aldehydes, beta-keto esters, and urea derivatives.','overview_count':1,'application_count':1,'mechanism_count':1},
    {'family_name':'Birch Reduction','family_class':'named_reaction','transformation_type':'dissolving-metal dearomatization / reductive alkylation','mechanism_type':'stepwise electron transfer and protonation','reactant_pattern_text':'arene or electron-poor heteroarene with alkali metal in liquid ammonia and alcohol','product_pattern_text':'unconjugated cyclohexadiene or reduced heterocycle','key_reagents_clue':'Li or Na, NH3(l), ROH, t-BuOH, EtOH','common_solvents':'liquid ammonia, THF co-solvent, alcohol proton sources','common_conditions':'low-temperature dissolving-metal reduction; optional Birch reductive alkylation','synonym_names':'Birch reduction; Birch reductive alkylation','description_short':'Dissolving-metal reduction of aromatic rings and heteroarenes to unconjugated dienes or partially reduced heterocycles.','overview_count':1,'application_count':1,'mechanism_count':1},
]
PAGE_ENTITY_SEEDS = [
    {'page_label':'p52','entity_text':'alpha-Diketone','canonical_name':'alpha-Diketone','entity_type':'reactant_class','family_name':'Benzilic Acid Rearrangement','notes':'Core substrate class for benzilic acid rearrangement.','confidence':0.95},
    {'page_label':'p52','entity_text':'1,2-shift','canonical_name':'1,2-shift','entity_type':'mechanistic_term','family_name':'Benzilic Acid Rearrangement','notes':'Migratory step following nucleophilic addition.','confidence':0.94},
    {'page_label':'p52','entity_text':'alpha-Hydroxy acid salt','canonical_name':'alpha-Hydroxy acid salt','entity_type':'product_class','family_name':'Benzilic Acid Rearrangement','notes':'Generic product class shown on the overview page.','confidence':0.9},
    {'page_label':'p53','entity_text':'(+)-K252a carbohydrate moiety','canonical_name':'(+)-K252a carbohydrate moiety','entity_type':'target_molecule','family_name':'Benzilic Acid Rearrangement','notes':'Ring-contraction application from indolocarbazole scaffold.','confidence':0.89},
    {'page_label':'p53','entity_text':'Hinesol','canonical_name':'Hinesol','entity_type':'target_molecule','family_name':'Benzilic Acid Rearrangement','notes':'Retro-benzilic acid rearrangement application.','confidence':0.89},
    {'page_label':'p53','entity_text':'Agarospirol','canonical_name':'Agarospirol','entity_type':'target_molecule','family_name':'Benzilic Acid Rearrangement','notes':'Spirocyclic sesquiterpene application.','confidence':0.89},
    {'page_label':'p54','entity_text':'Benzoin','canonical_name':'Benzoin','entity_type':'product_class','family_name':'Benzoin and Retro-Benzoin Condensation','notes':'Canonical alpha-hydroxy ketone product.','confidence':0.92},
    {'page_label':'p54','entity_text':'Thiazolium salt','canonical_name':'Thiazolium salt','entity_type':'catalyst_class','family_name':'Benzoin and Retro-Benzoin Condensation','notes':'Umpolung catalyst class on the overview page.','confidence':0.93},
    {'page_label':'p54','entity_text':'Breslow intermediate','canonical_name':'Breslow intermediate','entity_type':'intermediate','family_name':'Benzoin and Retro-Benzoin Condensation','notes':'Key umpolung intermediate in thiazolium/NHC catalysis.','confidence':0.92},
    {'page_label':'p55','entity_text':'2-Substituted quinazolines','canonical_name':'2-Substituted quinazolines','entity_type':'product_class','family_name':'Benzoin and Retro-Benzoin Condensation','notes':'Heteroaromatic products enabled by retro-benzoin logic.','confidence':0.9},
    {'page_label':'p55','entity_text':'Functionalized preanthraquinone','canonical_name':'Functionalized preanthraquinone','entity_type':'target_molecule','family_name':'Benzoin and Retro-Benzoin Condensation','notes':'Crossed aldehyde-ketone benzoin condensation product.','confidence':0.88},
    {'page_label':'p55','entity_text':'Diarylimidazole scaffold','canonical_name':'Diarylimidazole scaffold','entity_type':'target_molecule','family_name':'Benzoin and Retro-Benzoin Condensation','notes':'Medicinal chemistry application of benzoin coupling.','confidence':0.88},
    {'page_label':'p56','entity_text':'Enediyne','canonical_name':'Enediyne','entity_type':'reactant_class','family_name':'Bergman Cycloaromatization Reaction','notes':'Characteristic substrate class for Bergman cyclization.','confidence':0.95},
    {'page_label':'p56','entity_text':'Benzenoid diradical','canonical_name':'Benzenoid diradical','entity_type':'intermediate','family_name':'Bergman Cycloaromatization Reaction','notes':'Reactive intermediate after cycloaromatization.','confidence':0.95},
    {'page_label':'p56','entity_text':'Aromatic product','canonical_name':'Aromatic product','entity_type':'product_class','family_name':'Bergman Cycloaromatization Reaction','notes':'Generic trapped aromatic product shown on the overview page.','confidence':0.9},
    {'page_label':'p57','entity_text':'[n]Phenacenoporphyrins','canonical_name':'[n]Phenacenoporphyrins','entity_type':'product_class','family_name':'Bergman Cycloaromatization Reaction','notes':'Porphyrin-derived cycloaromatization products.','confidence':0.89},
    {'page_label':'p57','entity_text':'7-Methyl-2-methylene-acenaphthen-1-ol','canonical_name':'7-Methyl-2-methylene-acenaphthen-1-ol','entity_type':'target_molecule','family_name':'Bergman Cycloaromatization Reaction','notes':'Fused-ring construction example.','confidence':0.88},
    {'page_label':'p57','entity_text':'2-tert-Butylperylene','canonical_name':'2-tert-Butylperylene','entity_type':'target_molecule','family_name':'Bergman Cycloaromatization Reaction','notes':'Perylene construction via Bergman sequence.','confidence':0.88},
    {'page_label':'p58','entity_text':'N-Acyliminium ion','canonical_name':'N-Acyliminium ion','entity_type':'intermediate','family_name':'Biginelli Reaction','notes':'Key cationic intermediate in the classical mechanism.','confidence':0.94},
    {'page_label':'p58','entity_text':'Dihydropyrimidinone','canonical_name':'Dihydropyrimidinone','entity_type':'product_class','family_name':'Biginelli Reaction','notes':'Principal DHPM product class.','confidence':0.92},
    {'page_label':'p58','entity_text':'Urea / thiourea component','canonical_name':'Urea / thiourea component','entity_type':'reactant_class','family_name':'Biginelli Reaction','notes':'Nitrogen-containing three-component partner.','confidence':0.9},
    {'page_label':'p59','entity_text':'Isocrambescidin 800','canonical_name':'Isocrambescidin 800','entity_type':'target_molecule','family_name':'Biginelli Reaction','notes':'Tethered enantioselective Biginelli application.','confidence':0.88},
    {'page_label':'p59','entity_text':'(±)-Monastrol','canonical_name':'(±)-Monastrol','entity_type':'target_molecule','family_name':'Biginelli Reaction','notes':'Medicinally important DHPM application.','confidence':0.9},
    {'page_label':'p59','entity_text':'Batzelladine F','canonical_name':'Batzelladine F','entity_type':'target_molecule','family_name':'Biginelli Reaction','notes':'Complex guanidinium natural product application.','confidence':0.88},
    {'page_label':'p60','entity_text':'Radical anion','canonical_name':'Radical anion','entity_type':'intermediate','family_name':'Birch Reduction','notes':'First electron-transfer intermediate in Birch reduction.','confidence':0.94},
    {'page_label':'p60','entity_text':'Cyclohexadiene','canonical_name':'Cyclohexadiene','entity_type':'product_class','family_name':'Birch Reduction','notes':'Typical partially reduced arene product class.','confidence':0.91},
    {'page_label':'p60','entity_text':'Birch reductive alkylation','canonical_name':'Birch reductive alkylation','entity_type':'variant','family_name':'Birch Reduction','notes':'Variant that traps reduced intermediates with electrophiles.','confidence':0.9},
    {'page_label':'p61','entity_text':'(-)-Taxol','canonical_name':'(-)-Taxol','entity_type':'target_molecule','family_name':'Birch Reduction','notes':'Natural-product application using C-ring Birch reduction.','confidence':0.89},
    {'page_label':'p61','entity_text':'(+)-Apovincamine','canonical_name':'(+)-Apovincamine','entity_type':'target_molecule','family_name':'Birch Reduction','notes':'Birch reductive alkylation example.','confidence':0.89},
    {'page_label':'p61','entity_text':'Galbulimima alkaloid GB 13','canonical_name':'Galbulimima alkaloid GB 13','entity_type':'target_molecule','family_name':'Birch Reduction','notes':'Dearomatization and reductive decyanation application.','confidence':0.88},
]

def _upsert_family(cur, seed):
    vals=(seed['family_name'], normalize_key(seed['family_name']), seed.get('family_class'), seed.get('transformation_type'), seed.get('mechanism_type'), seed.get('reactant_pattern_text'), seed.get('product_pattern_text'), seed.get('key_reagents_clue'), seed.get('common_solvents'), seed.get('common_conditions'), seed.get('synonym_names'), seed.get('description_short'), seed.get('overview_count',0), seed.get('application_count',0), seed.get('mechanism_count',0), 'chemlens_backend_db_schema_frontmatter_batch10_patch_20260411.zip', FRONTMATTER_BATCH10_VERSION)
    cur.execute("""
    INSERT INTO reaction_family_patterns (
      family_name,family_name_norm,family_class,transformation_type,mechanism_type,reactant_pattern_text,product_pattern_text,
      key_reagents_clue,common_solvents,common_conditions,synonym_names,description_short,overview_count,application_count,mechanism_count,
      latest_source_zip,seeded_from,latest_updated_at,created_at,updated_at
    ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,datetime('now'),datetime('now'),datetime('now'))
    ON CONFLICT(family_name_norm) DO UPDATE SET
      family_name=excluded.family_name,family_class=excluded.family_class,transformation_type=excluded.transformation_type,
      mechanism_type=excluded.mechanism_type,reactant_pattern_text=excluded.reactant_pattern_text,product_pattern_text=excluded.product_pattern_text,
      key_reagents_clue=excluded.key_reagents_clue,common_solvents=excluded.common_solvents,common_conditions=excluded.common_conditions,
      synonym_names=excluded.synonym_names,description_short=excluded.description_short,
      overview_count=MAX(reaction_family_patterns.overview_count, excluded.overview_count),
      application_count=MAX(reaction_family_patterns.application_count, excluded.application_count),
      mechanism_count=MAX(reaction_family_patterns.mechanism_count, excluded.mechanism_count),
      latest_source_zip=excluded.latest_source_zip,seeded_from=excluded.seeded_from,latest_updated_at=datetime('now'),updated_at=datetime('now')
    """, vals)

def apply_frontmatter_batch10(db_path: str | Path) -> Dict[str, Any]:
    db_path = str(db_path)
    ensure_frontmatter_schema(db_path)
    conn = sqlite3.connect(db_path)
    cur = conn.cursor()
    for seed in FAMILY_PATTERN_SEEDS:
        _upsert_family(cur, seed)
    page_ids={}
    for seed in PAGE_KNOWLEDGE_SEEDS:
        cur.execute("""
        INSERT INTO manual_page_knowledge (source_label,page_label,page_no,title,section_name,page_kind,summary,family_names,reference_family_name,notes,image_filename,created_at,updated_at)
        VALUES (?,?,?,?,?,?,?,?,?,?,?,datetime('now'),datetime('now'))
        ON CONFLICT(source_label,page_label) DO UPDATE SET
          page_no=excluded.page_no,title=excluded.title,section_name=excluded.section_name,page_kind=excluded.page_kind,summary=excluded.summary,
          family_names=excluded.family_names,reference_family_name=excluded.reference_family_name,notes=excluded.notes,image_filename=excluded.image_filename,updated_at=datetime('now')
        """, (seed['source_label'],seed['page_label'],seed['page_no'],seed['title'],seed['section_name'],seed['page_kind'],seed['summary'],seed['family_names'],seed['reference_family_name'],seed['notes'],seed['image_filename']))
        cur.execute('SELECT id FROM manual_page_knowledge WHERE source_label=? AND page_label=?', (seed['source_label'], seed['page_label']))
        page_ids[seed['page_label']] = cur.fetchone()[0]
    for seed in CURATED_BATCH10_ABBREVIATIONS:
        can_norm=normalize_key(seed['canonical_name']) if seed.get('canonical_name') else None
        cur.execute("""
        INSERT INTO abbreviation_aliases (alias,alias_norm,canonical_name,canonical_name_norm,entity_type,source_label,source_page,confidence,created_at,updated_at)
        VALUES (?,?,?,?,?,?,?,0.92,datetime('now'),datetime('now'))
        ON CONFLICT(alias_norm, canonical_name_norm, entity_type) DO UPDATE SET source_label=excluded.source_label, source_page=excluded.source_page, updated_at=datetime('now')
        """, (seed['alias'], normalize_key(seed['alias']), seed['canonical_name'], can_norm, seed['entity_type'], 'named_reactions_frontmatter_batch10', seed['source_page']))
    for seed in PAGE_ENTITY_SEEDS:
        pid=page_ids[seed['page_label']]
        cur.execute("""
        INSERT INTO manual_page_entities (page_knowledge_id,entity_text,entity_text_norm,canonical_name,entity_type,alias_id,family_name,notes,confidence,created_at,updated_at)
        VALUES (?,?,?,?,?,?,?,?,?,datetime('now'),datetime('now'))
        ON CONFLICT(page_knowledge_id, entity_text_norm, entity_type) DO UPDATE SET
          canonical_name=excluded.canonical_name,family_name=excluded.family_name,notes=excluded.notes,confidence=excluded.confidence,updated_at=datetime('now')
        """, (pid, seed['entity_text'], normalize_key(seed['entity_text']), seed.get('canonical_name'), seed['entity_type'], None, seed.get('family_name'), seed.get('notes'), seed.get('confidence',0.9)))
    conn.commit()
    res={
      'manual_page_knowledge': cur.execute('SELECT COUNT(*) FROM manual_page_knowledge').fetchone()[0],
      'manual_page_entities': cur.execute('SELECT COUNT(*) FROM manual_page_entities').fetchone()[0],
      'abbreviation_aliases': cur.execute('SELECT COUNT(*) FROM abbreviation_aliases').fetchone()[0],
      'reaction_family_patterns': cur.execute('SELECT COUNT(*) FROM reaction_family_patterns').fetchone()[0],
      'batch10_pages': cur.execute("SELECT COUNT(*) FROM manual_page_knowledge WHERE source_label='named_reactions_frontmatter_batch10'").fetchone()[0],
    }
    conn.close(); return res

if __name__ == '__main__':
    from pprint import pprint
    pprint(apply_frontmatter_batch10(Path(__file__).resolve().parent / 'labint.db'))
