from __future__ import annotations

from pathlib import Path
from typing import Any, Dict

from app.labint_frontmatter_batch_restore_utils import (
    apply_frontmatter_batch_generic,
    load_abbreviation_seeds,
    load_family_pattern_seeds,
    load_page_knowledge_seeds,
)

FRONTMATTER_BATCH23_VERSION = 'labint_frontmatter_batch23_v1_20260412'
SOURCE_LABEL = 'named_reactions_frontmatter_batch23'
LATEST_SOURCE_ZIP = 'backend_batch15_23_frontmatter_cumulative_patch_20260412.zip'

PAGE_KNOWLEDGE_SEEDS = load_page_knowledge_seeds(23, SOURCE_LABEL)
FAMILY_PATTERN_SEEDS = load_family_pattern_seeds(23, FRONTMATTER_BATCH23_VERSION)
BATCH23_SOURCE_PAGES = {
    'H2O2': 174,
    'mCPBA': 174,
    'Et3N': 174,
    'HBF4·OEt2': 174,
    'BF3·AcOH': 174,
    'TBAF': 175,
    'NaHCO3': 175,
    'KF': 175,
    'DIBAL-H': 175,
    'AlCl3': 176,
    'TiCl4': 176,
    'TFAA': 177,
    'SnCl4': 177,
    'TiBr4': 177,
    'BF3·OEt2': 178,
    'AgOTf': 179,
    'Me2SO4': 179,
    'H2SO4': 179,
    'Ac2O': 180,
    'AlBr3': 181,
    'n-BuLi': 181,
    'EDCI': 181,
    'DMAP': 181,
    'DEAD': 183,
    'PPh3': 183,
    'NH2NH2·H2O': 182,
    'NMP': 183,
    'DMF': 183,
    'MeNH2': 183,
}
CURATED_BATCH23_ABBREVIATIONS = load_abbreviation_seeds(
    23,
    SOURCE_LABEL,
    source_pages=BATCH23_SOURCE_PAGES,
    default_note='batch23 frontmatter abbreviation seed',
)
PAGE_ENTITY_SEEDS = [{'page_label': 'p174', 'entity_text': 'Fleming-Tamao Oxidation', 'canonical_name': 'Fleming-Tamao Oxidation', 'entity_type': 'reaction_family', 'family_name': 'Fleming-Tamao Oxidation', 'notes': 'Named oxidation family overview.', 'confidence': 0.92}, {'page_label': 'p174', 'entity_text': 'Tamao Oxidation', 'canonical_name': 'Fleming-Tamao Oxidation', 'entity_type': 'related_reaction', 'family_name': 'Fleming-Tamao Oxidation', 'notes': 'Core oxidative desilylation concept explicitly highlighted on the overview page.', 'confidence': 0.87}, {'page_label': 'p174', 'entity_text': 'carbon-silicon bond oxidation', 'canonical_name': None, 'entity_type': 'transformation_class', 'family_name': 'Fleming-Tamao Oxidation', 'notes': 'General transformation converting organosilanes into alcohols.', 'confidence': 0.85}, {'page_label': 'p175', 'entity_text': 'Fleming-Tamao Oxidation', 'canonical_name': 'Fleming-Tamao Oxidation', 'entity_type': 'reaction_family', 'family_name': 'Fleming-Tamao Oxidation', 'notes': 'Application page family anchor.', 'confidence': 0.92}, {'page_label': 'p175', 'entity_text': 'Quinolizidine diol', 'canonical_name': 'Quinolizidine diol', 'entity_type': 'target_molecule', 'family_name': 'Fleming-Tamao Oxidation', 'notes': 'Hydroxylated bicyclic target obtained after Fleming-Tamao oxidation.', 'confidence': 0.86}, {'page_label': 'p175', 'entity_text': '18-epi-Tricyclic core of garsubellin A', 'canonical_name': '18-epi-Tricyclic core of garsubellin A', 'entity_type': 'target_molecule', 'family_name': 'Fleming-Tamao Oxidation', 'notes': 'Late-stage desilylative oxidation example on the application page.', 'confidence': 0.85}, {'page_label': 'p176', 'entity_text': 'Friedel-Crafts Acylation', 'canonical_name': 'Friedel-Crafts Acylation', 'entity_type': 'reaction_family', 'family_name': 'Friedel-Crafts Acylation', 'notes': 'Named electrophilic aromatic acylation overview.', 'confidence': 0.92}, {'page_label': 'p176', 'entity_text': 'acylium ion', 'canonical_name': None, 'entity_type': 'mechanistic_concept', 'family_name': 'Friedel-Crafts Acylation', 'notes': 'Canonical electrophile generated by Lewis-acid activation of the acyl donor.', 'confidence': 0.87}, {'page_label': 'p176', 'entity_text': 'Intramolecular Friedel-Crafts acylation', 'canonical_name': 'Friedel-Crafts Acylation', 'entity_type': 'related_reaction', 'family_name': 'Friedel-Crafts Acylation', 'notes': 'Ring-closing acylation variant explicitly emphasized on the overview page.', 'confidence': 0.86}, {'page_label': 'p177', 'entity_text': 'Friedel-Crafts Acylation', 'canonical_name': 'Friedel-Crafts Acylation', 'entity_type': 'reaction_family', 'family_name': 'Friedel-Crafts Acylation', 'notes': 'Application page family anchor.', 'confidence': 0.92}, {'page_label': 'p177', 'entity_text': '(-)-Hispidospermidin', 'canonical_name': '(-)-Hispidospermidin', 'entity_type': 'target_molecule', 'family_name': 'Friedel-Crafts Acylation', 'notes': 'Natural-product target assembled using intramolecular Friedel-Crafts acylation.', 'confidence': 0.86}, {'page_label': 'p177', 'entity_text': 'Phomazarin', 'canonical_name': 'Phomazarin', 'entity_type': 'target_molecule', 'family_name': 'Friedel-Crafts Acylation', 'notes': 'Ring-closure example highlighted on the application page.', 'confidence': 0.85}, {'page_label': 'p178', 'entity_text': 'Friedel-Crafts Alkylation', 'canonical_name': 'Friedel-Crafts Alkylation', 'entity_type': 'reaction_family', 'family_name': 'Friedel-Crafts Alkylation', 'notes': 'Named electrophilic aromatic alkylation overview.', 'confidence': 0.92}, {'page_label': 'p178', 'entity_text': 'carbocation intermediate', 'canonical_name': None, 'entity_type': 'mechanistic_concept', 'family_name': 'Friedel-Crafts Alkylation', 'notes': 'Electrophilic cationic intermediate responsible for aromatic substitution.', 'confidence': 0.87}, {'page_label': 'p178', 'entity_text': 'hydroarylation', 'canonical_name': None, 'entity_type': 'transformation_class', 'family_name': 'Friedel-Crafts Alkylation', 'notes': 'Variant in which alkenes or alcohol derivatives act as alkylating equivalents.', 'confidence': 0.85}, {'page_label': 'p179', 'entity_text': 'Friedel-Crafts Alkylation', 'canonical_name': 'Friedel-Crafts Alkylation', 'entity_type': 'reaction_family', 'family_name': 'Friedel-Crafts Alkylation', 'notes': 'Application page family anchor.', 'confidence': 0.92}, {'page_label': 'p179', 'entity_text': 'Semisynthetic antimalarial trioxane', 'canonical_name': 'Semisynthetic antimalarial trioxane', 'entity_type': 'product_class', 'family_name': 'Friedel-Crafts Alkylation', 'notes': 'Artemisinin-family trioxane product class assembled through Friedel-Crafts alkylation.', 'confidence': 0.86}, {'page_label': 'p179', 'entity_text': '(+)-Brasiliquinone B', 'canonical_name': '(+)-Brasiliquinone B', 'entity_type': 'target_molecule', 'family_name': 'Friedel-Crafts Alkylation', 'notes': 'Natural-product synthesis example featured on the application page.', 'confidence': 0.85}, {'page_label': 'p180', 'entity_text': 'Fries Rearrangement', 'canonical_name': 'Fries Rearrangement', 'entity_type': 'reaction_family', 'family_name': 'Fries Rearrangement', 'notes': 'Named acyl-migration family overview.', 'confidence': 0.92}, {'page_label': 'p180', 'entity_text': 'Photo-Fries Rearrangement', 'canonical_name': 'Fries Rearrangement', 'entity_type': 'related_reaction', 'family_name': 'Fries Rearrangement', 'notes': 'Photochemical variant explicitly called out on the overview page.', 'confidence': 0.87}, {'page_label': 'p180', 'entity_text': 'Anionic ortho-Fries Rearrangement', 'canonical_name': 'Fries Rearrangement', 'entity_type': 'related_reaction', 'family_name': 'Fries Rearrangement', 'notes': 'Organolithium-driven ortho-acyl migration variant shown on the overview page.', 'confidence': 0.86}, {'page_label': 'p181', 'entity_text': 'Fries Rearrangement', 'canonical_name': 'Fries Rearrangement', 'entity_type': 'reaction_family', 'family_name': 'Fries Rearrangement', 'notes': 'Application page family anchor.', 'confidence': 0.92}, {'page_label': 'p181', 'entity_text': '(M)-Knipholone', 'canonical_name': '(M)-Knipholone', 'entity_type': 'target_molecule', 'family_name': 'Fries Rearrangement', 'notes': 'Atropisomeric natural product obtained through a Fries-type rearrangement sequence.', 'confidence': 0.86}, {'page_label': 'p181', 'entity_text': 'Diazonamide macrocycle', 'canonical_name': 'Diazonamide macrocycle', 'entity_type': 'target_molecule', 'family_name': 'Fries Rearrangement', 'notes': 'Macrocyclization product forged through a photo-Fries rearrangement step.', 'confidence': 0.85}, {'page_label': 'p182', 'entity_text': 'Gabriel Synthesis', 'canonical_name': 'Gabriel Synthesis', 'entity_type': 'reaction_family', 'family_name': 'Gabriel Synthesis', 'notes': 'Named phthalimide-based primary-amine synthesis overview.', 'confidence': 0.92}, {'page_label': 'p182', 'entity_text': 'Ing-Manske Procedure', 'canonical_name': 'Gabriel Synthesis', 'entity_type': 'related_reaction', 'family_name': 'Gabriel Synthesis', 'notes': 'Hydrazinolysis-based deprotection variant cited on the overview page.', 'confidence': 0.87}, {'page_label': 'p182', 'entity_text': 'potassium phthalimide', 'canonical_name': 'potassium phthalimide', 'entity_type': 'reagent_class', 'family_name': 'Gabriel Synthesis', 'notes': 'Masked-ammonia reagent central to the Gabriel synthesis.', 'confidence': 0.85}, {'page_label': 'p183', 'entity_text': 'Gabriel Synthesis', 'canonical_name': 'Gabriel Synthesis', 'entity_type': 'reaction_family', 'family_name': 'Gabriel Synthesis', 'notes': 'Application page family anchor.', 'confidence': 0.92}, {'page_label': 'p183', 'entity_text': 'Peramine', 'canonical_name': 'Peramine', 'entity_type': 'target_molecule', 'family_name': 'Gabriel Synthesis', 'notes': 'Insect feeding deterrent synthesized using a late-stage Gabriel sequence.', 'confidence': 0.86}, {'page_label': 'p183', 'entity_text': 'Swainsonine analogue', 'canonical_name': 'Swainsonine analogue', 'entity_type': 'target_molecule', 'family_name': 'Gabriel Synthesis', 'notes': 'Amino-sugar target prepared using Gabriel installation and deprotection logic.', 'confidence': 0.85}]


def apply_frontmatter_batch23(db_path: str | Path) -> Dict[str, Any]:
    return apply_frontmatter_batch_generic(
        db_path=db_path,
        source_label=SOURCE_LABEL,
        version=FRONTMATTER_BATCH23_VERSION,
        latest_source_zip=LATEST_SOURCE_ZIP,
        batch_no=23,
        page_knowledge_seeds=PAGE_KNOWLEDGE_SEEDS,
        family_pattern_seeds=FAMILY_PATTERN_SEEDS,
        abbreviation_seeds=CURATED_BATCH23_ABBREVIATIONS,
        page_entity_seeds=PAGE_ENTITY_SEEDS,
    )


if __name__ == '__main__':
    from pprint import pprint
    pprint(apply_frontmatter_batch23(Path(__file__).resolve().parent / 'labint.db'))
