from __future__ import annotations

from pathlib import Path
from typing import Any, Dict

from app.labint_frontmatter_batch_restore_utils import (
    apply_frontmatter_batch_generic,
    load_abbreviation_seeds,
    load_family_pattern_seeds,
    load_page_knowledge_seeds,
)

FRONTMATTER_BATCH31_VERSION = 'labint_frontmatter_batch31_v1_20260412'
SOURCE_LABEL = 'named_reactions_frontmatter_batch31'
LATEST_SOURCE_ZIP = 'backend_batch15_31_frontmatter_cumulative_patch_20260412.zip'

PAGE_KNOWLEDGE_SEEDS = load_page_knowledge_seeds(31, SOURCE_LABEL)
FAMILY_PATTERN_SEEDS = load_family_pattern_seeds(31, FRONTMATTER_BATCH31_VERSION)
BATCH31_SOURCE_PAGES = {'4A MS': 262,
 'AcOH': 254,
 'CH2Cl2': 262,
 'DMF': 260,
 'Et2O': 256,
 'Et3N': 257,
 'EtMgBr': 256,
 'K2CO3': 261,
 'KOH': 254,
 'LiCl': 260,
 'MTBE': 259,
 'MeCN': 262,
 'MeMgCl': 259,
 'NH4OAc': 254,
 'NMO': 262,
 'Na2CO3': 261,
 'NaOH': 259,
 'Ni(acac)2': 259,
 'NiCl2': 258,
 'PCC': 257,
 'PPTS': 257,
 'PPh3': 255,
 'Pd(OAc)2': 260,
 'Pd(PPh3)4': 259,
 'PdCl2(P(o-Tol)3)2': 263,
 'TBAF': 257,
 'TBSOTf': 257,
 'TES': 261,
 'THF': 254,
 'TPAP': 262,
 'Tf2O': 259,
 'TfOH': 257,
 'Ti(O-i-Pr)4': 256,
 'n-Bu4NCl': 261,
 'n-BuLi': 255,
 't-BuOK': 255}
CURATED_BATCH31_ABBREVIATIONS = load_abbreviation_seeds(
    31,
    SOURCE_LABEL,
    source_pages=BATCH31_SOURCE_PAGES,
    default_note='batch31 frontmatter abbreviation seed',
)
PAGE_ENTITY_SEEDS = [{'canonical_name': 'Kröhnke Pyridine Synthesis',
  'confidence': 0.92,
  'entity_text': 'Kröhnke Pyridine Synthesis',
  'entity_type': 'reaction_family',
  'family_name': 'Kröhnke Pyridine Synthesis',
  'notes': 'Pyridine-annulation family overview.',
  'page_label': 'p254'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'acylmethylpyridinium salt',
  'entity_type': 'intermediate_class',
  'family_name': 'Kröhnke Pyridine Synthesis',
  'notes': 'Reactive pyridinium intermediate generated from alpha-haloketones and pyridine prior to annulation.',
  'page_label': 'p254'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'substituted pyridine',
  'entity_type': 'product_class',
  'family_name': 'Kröhnke Pyridine Synthesis',
  'notes': 'Characteristic heteroaromatic product class formed after Michael addition and cyclodehydration.',
  'page_label': 'p254'},
 {'canonical_name': 'Kröhnke Pyridine Synthesis',
  'confidence': 0.92,
  'entity_text': 'Kröhnke Pyridine Synthesis',
  'entity_type': 'reaction_family',
  'family_name': 'Kröhnke Pyridine Synthesis',
  'notes': 'Application page family anchor.',
  'page_label': 'p255'},
 {'canonical_name': 'Pyridine-type P,N-ligand',
  'confidence': 0.86,
  'entity_text': 'Pyridine-type P,N-ligand',
  'entity_type': 'target_molecule',
  'family_name': 'Kröhnke Pyridine Synthesis',
  'notes': 'Monoterpene-derived ligand scaffold assembled through Kröhnke annulation of pinocarvone-derived enones.',
  'page_label': 'p255'},
 {'canonical_name': 'Cyclo-2,2′:4′,4″:2″,2‴:4‴,4⁗:2⁗,2⁗⁗-sexipyridine',
  'confidence': 0.83,
  'entity_text': 'Cyclo-2,2′:4′,4″:2″,2‴:4‴,4⁗:2⁗,2⁗⁗-sexipyridine',
  'entity_type': 'target_molecule',
  'family_name': 'Kröhnke Pyridine Synthesis',
  'notes': 'Macrocyclic oligopyridine synthesized by multiple cross-couplings followed by a terminal Kröhnke annulation.',
  'page_label': 'p255'},
 {'canonical_name': 'Kulinovich Reaction',
  'confidence': 0.92,
  'entity_text': 'Kulinovich Reaction',
  'entity_type': 'reaction_family',
  'family_name': 'Kulinovich Reaction',
  'notes': 'Titanium-mediated cyclopropanation family overview.',
  'page_label': 'p256'},
 {'canonical_name': None,
  'confidence': 0.86,
  'entity_text': 'titanacyclopropane',
  'entity_type': 'intermediate_class',
  'family_name': 'Kulinovich Reaction',
  'notes': 'Key organotitanium intermediate that transfers a 1,2-dicarbon equivalent to esters or amides.',
  'page_label': 'p256'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': '1-alkylcyclopropanol',
  'entity_type': 'product_class',
  'family_name': 'Kulinovich Reaction',
  'notes': 'Signature product class generated from esters under Kulinkovich conditions.',
  'page_label': 'p256'},
 {'canonical_name': 'Kulinovich Reaction',
  'confidence': 0.92,
  'entity_text': 'Kulinovich Reaction',
  'entity_type': 'reaction_family',
  'family_name': 'Kulinovich Reaction',
  'notes': 'Application page family anchor.',
  'page_label': 'p257'},
 {'canonical_name': '(S)-Cleonin',
  'confidence': 0.86,
  'entity_text': '(S)-Cleonin',
  'entity_type': 'target_molecule',
  'family_name': 'Kulinovich Reaction',
  'notes': 'Antitumor antibiotic component prepared from an N-Cbz serine derivative using the Kulinkovich reaction.',
  'page_label': 'p257'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'bicyclo[5.3.0]decan-3-one derivative',
  'entity_type': 'target_molecule',
  'family_name': 'Kulinovich Reaction',
  'notes': 'Fused bicyclic ketone derivative accessed through tandem Kulinkovich cyclopropanation and ring-expansion/cyclization.',
  'page_label': 'p257'},
 {'canonical_name': 'Kumada Cross-Coupling',
  'confidence': 0.92,
  'entity_text': 'Kumada Cross-Coupling',
  'entity_type': 'reaction_family',
  'family_name': 'Kumada Cross-Coupling',
  'notes': 'Transition-metal-catalyzed Kumada coupling overview.',
  'page_label': 'p258'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'Grignard reagent',
  'entity_type': 'reactant_class',
  'family_name': 'Kumada Cross-Coupling',
  'notes': 'Organomagnesium coupling partner used in Ni- or Pd-catalyzed carbon-carbon bond formation.',
  'page_label': 'p258'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'coupled product',
  'entity_type': 'product_class',
  'family_name': 'Kumada Cross-Coupling',
  'notes': 'Generic cross-coupled alkene or arene product obtained after oxidative addition, transmetalation, and reductive elimination.',
  'page_label': 'p258'},
 {'canonical_name': 'Kumada Cross-Coupling',
  'confidence': 0.92,
  'entity_text': 'Kumada Cross-Coupling',
  'entity_type': 'reaction_family',
  'family_name': 'Kumada Cross-Coupling',
  'notes': 'Application page family anchor.',
  'page_label': 'p259'},
 {'canonical_name': '(+)-Ambruticin',
  'confidence': 0.86,
  'entity_text': '(+)-Ambruticin',
  'entity_type': 'target_molecule',
  'family_name': 'Kumada Cross-Coupling',
  'notes': 'Natural product whose vinyl iodide was stereospecifically converted to the corresponding diene by Kumada coupling.',
  'page_label': 'p259'},
 {'canonical_name': '[18]Dehydrodexoxyepothilone B',
  'confidence': 0.85,
  'entity_text': '[18]Dehydrodexoxyepothilone B',
  'entity_type': 'target_molecule',
  'family_name': 'Kumada Cross-Coupling',
  'notes': 'Conformationally restricted epothilone analogue assembled by Kumada coupling of a vinyl iodide precursor.',
  'page_label': 'p259'},
 {'canonical_name': 'Larock Indole Synthesis',
  'confidence': 0.92,
  'entity_text': 'Larock Indole Synthesis',
  'entity_type': 'reaction_family',
  'family_name': 'Larock Indole Synthesis',
  'notes': 'Pd-catalyzed indole annulation family overview.',
  'page_label': 'p260'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'o-iodoaniline',
  'entity_type': 'reactant_class',
  'family_name': 'Larock Indole Synthesis',
  'notes': 'Key aryl-halide partner that undergoes oxidative addition before alkyne insertion and annulation.',
  'page_label': 'p260'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'substituted indole',
  'entity_type': 'product_class',
  'family_name': 'Larock Indole Synthesis',
  'notes': 'Characteristic indole product class obtained from Larock heteroannulation of alkynes.',
  'page_label': 'p260'},
 {'canonical_name': 'Larock Indole Synthesis',
  'confidence': 0.92,
  'entity_text': 'Larock Indole Synthesis',
  'entity_type': 'reaction_family',
  'family_name': 'Larock Indole Synthesis',
  'notes': 'Application page family anchor.',
  'page_label': 'p261'},
 {'canonical_name': '(-)-Fuschiaefoline',
  'confidence': 0.86,
  'entity_text': '(-)-Fuschiaefoline',
  'entity_type': 'target_molecule',
  'family_name': 'Larock Indole Synthesis',
  'notes': 'Natural product prepared from a key precursor assembled by Larock indole synthesis.',
  'page_label': 'p261'},
 {'canonical_name': 'gonadotropin releasing hormone antagonist',
  'confidence': 0.84,
  'entity_text': 'gonadotropin releasing hormone antagonist',
  'entity_type': 'target_molecule',
  'family_name': 'Larock Indole Synthesis',
  'notes': '(S)-beta-methyl-2-aryltryptamine-derived antagonist scaffold assembled through Larock annulation and subsequent Suzuki coupling.',
  'page_label': 'p261'},
 {'canonical_name': 'Ley Oxidation',
  'confidence': 0.92,
  'entity_text': 'Ley Oxidation',
  'entity_type': 'reaction_family',
  'family_name': 'Ley Oxidation',
  'notes': 'TPAP/NMO oxidation family overview.',
  'page_label': 'p262'},
 {'canonical_name': 'Ley Oxidation',
  'confidence': 0.84,
  'entity_text': 'TPAP oxidation',
  'entity_type': 'related_reaction',
  'family_name': 'Ley Oxidation',
  'notes': 'Common synonym highlighting use of tetrapropylammonium perruthenate as the catalytic oxidant.',
  'page_label': 'p262'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'aldehyde|ketone',
  'entity_type': 'product_class',
  'family_name': 'Ley Oxidation',
  'notes': 'Typical oxidation products formed from primary and secondary alcohols under TPAP/NMO conditions.',
  'page_label': 'p262'},
 {'canonical_name': 'Ley Oxidation',
  'confidence': 0.92,
  'entity_text': 'Ley Oxidation',
  'entity_type': 'reaction_family',
  'family_name': 'Ley Oxidation',
  'notes': 'Application page family anchor.',
  'page_label': 'p263'},
 {'canonical_name': '(-)-Pironetin (PA48153C)',
  'confidence': 0.86,
  'entity_text': '(-)-Pironetin (PA48153C)',
  'entity_type': 'target_molecule',
  'family_name': 'Ley Oxidation',
  'notes': 'Immunosuppressant whose beta-unsaturated lactone unit was installed after Ley oxidation of an advanced primary alcohol.',
  'page_label': 'p263'},
 {'canonical_name': 'allocyathin B3',
  'confidence': 0.85,
  'entity_text': 'allocyathin B3',
  'entity_type': 'target_molecule',
  'family_name': 'Ley Oxidation',
  'notes': 'Cyathin diterpene natural product whose tetracyclic secondary alcohol precursor was oxidized to the corresponding ketone under TPAP/NMO '
           'conditions.',
  'page_label': 'p263'}]


def apply_frontmatter_batch31(db_path: str | Path) -> Dict[str, Any]:
    return apply_frontmatter_batch_generic(
        db_path=db_path,
        source_label=SOURCE_LABEL,
        version=FRONTMATTER_BATCH31_VERSION,
        latest_source_zip=LATEST_SOURCE_ZIP,
        batch_no=31,
        page_knowledge_seeds=PAGE_KNOWLEDGE_SEEDS,
        family_pattern_seeds=FAMILY_PATTERN_SEEDS,
        abbreviation_seeds=CURATED_BATCH31_ABBREVIATIONS,
        page_entity_seeds=PAGE_ENTITY_SEEDS,
        replace_existing_page_entities=True,
    )
