from __future__ import annotations

from pathlib import Path
from typing import Any, Dict

from app.labint_frontmatter_batch_restore_utils import (
    apply_frontmatter_batch_generic,
    load_abbreviation_seeds,
    load_family_pattern_seeds,
    load_page_knowledge_seeds,
)

FRONTMATTER_BATCH40_VERSION = 'labint_frontmatter_batch40_v1_20260412'
SOURCE_LABEL = 'named_reactions_frontmatter_batch40'
LATEST_SOURCE_ZIP = 'backend_batch15_40_frontmatter_cumulative_patch_20260412.zip'

PAGE_KNOWLEDGE_SEEDS = load_page_knowledge_seeds(40, SOURCE_LABEL)
FAMILY_PATTERN_SEEDS = load_family_pattern_seeds(40, FRONTMATTER_BATCH40_VERSION)
BATCH40_SOURCE_PAGES = {'ABFGH': 349,
 'CDI': 341,
 'Cp2TiMe2': 342,
 'DDQ': 349,
 'DMAP': 341,
 'DMP': 343,
 'ET 743': 349,
 'HMDS': 343,
 'TBDPS': 349,
 'TMSCl': 345,
 'TMSOTf': 343}
CURATED_BATCH40_ABBREVIATIONS = load_abbreviation_seeds(
    40,
    SOURCE_LABEL,
    source_pages=BATCH40_SOURCE_PAGES,
    default_note='batch40 frontmatter abbreviation seed',
)
PAGE_ENTITY_SEEDS = [{'canonical_name': 'Petasis Boronic Acid-Mannich Reaction',
  'confidence': 0.92,
  'entity_text': 'Petasis Boronic Acid-Mannich Reaction',
  'entity_type': 'reaction_family',
  'family_name': 'Petasis Boronic Acid-Mannich Reaction',
  'notes': 'Overview page family anchor for the Petasis boronic acid-Mannich reaction.',
  'page_label': 'p340'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'amine + carbonyl compound + boronic acid',
  'entity_type': 'reactant_class',
  'family_name': 'Petasis Boronic Acid-Mannich Reaction',
  'notes': 'Canonical three-component input set for the Petasis reaction.',
  'page_label': 'p340'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'allylic or benzylic amine',
  'entity_type': 'product_class',
  'family_name': 'Petasis Boronic Acid-Mannich Reaction',
  'notes': 'Characteristic product class obtained after boronic-acid transfer to the iminium intermediate.',
  'page_label': 'p340'},
 {'canonical_name': 'Petasis Boronic Acid-Mannich Reaction',
  'confidence': 0.92,
  'entity_text': 'Petasis Boronic Acid-Mannich Reaction',
  'entity_type': 'reaction_family',
  'family_name': 'Petasis Boronic Acid-Mannich Reaction',
  'notes': 'Application page family anchor.',
  'page_label': 'p341'},
 {'canonical_name': 'Cytoxazone',
  'confidence': 0.85,
  'entity_text': '(-)-Cytoxazone',
  'entity_type': 'target_molecule',
  'family_name': 'Petasis Boronic Acid-Mannich Reaction',
  'notes': 'Cytokine modulator assembled through a Petasis boronic acid-Mannich reaction of D-glyceraldehyde, a chiral amine, and '
           'anisylboronic acid.',
  'page_label': 'p341'},
 {'canonical_name': 'Diketopiperazine derivatives',
  'confidence': 0.84,
  'entity_text': 'Diketopiperazine derivatives',
  'entity_type': 'target_molecule',
  'family_name': 'Petasis Boronic Acid-Mannich Reaction',
  'notes': 'Parallel library products generated from glyoxylic acid, piperazine carboxylic acids, and boronic acids.',
  'page_label': 'p341'},
 {'canonical_name': '2H-Chromene derivatives',
  'confidence': 0.84,
  'entity_text': '2H-Chromene derivatives',
  'entity_type': 'target_molecule',
  'family_name': 'Petasis Boronic Acid-Mannich Reaction',
  'notes': 'Heterocycles formed when the Petasis allylic amine undergoes cyclization to eject dibenzylamine.',
  'page_label': 'p341'},
 {'canonical_name': '6-Deoxycastanospermine',
  'confidence': 0.85,
  'entity_text': '(+)-6-Deoxycastanospermine',
  'entity_type': 'target_molecule',
  'family_name': 'Petasis Boronic Acid-Mannich Reaction',
  'notes': 'Iminosugar target reached via N-acyliminium Petasis addition using a vinylboronic ester.',
  'page_label': 'p341'},
 {'canonical_name': 'Petasis-Ferrier Rearrangement',
  'confidence': 0.92,
  'entity_text': 'Petasis-Ferrier Rearrangement',
  'entity_type': 'reaction_family',
  'family_name': 'Petasis-Ferrier Rearrangement',
  'notes': 'Overview page family anchor for the Petasis-Ferrier rearrangement.',
  'page_label': 'p342'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'enol acetal derived from a 1,3-dioxolan-4-one or 1,3-dioxane-4-one',
  'entity_type': 'reactant_class',
  'family_name': 'Petasis-Ferrier Rearrangement',
  'notes': 'Canonical precursor class for five- and six-membered Petasis-Ferrier rearrangements.',
  'page_label': 'p342'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'substituted tetrahydrofuran or tetrahydropyran',
  'entity_type': 'product_class',
  'family_name': 'Petasis-Ferrier Rearrangement',
  'notes': 'Characteristic oxygen-heterocycle products of the rearrangement.',
  'page_label': 'p342'},
 {'canonical_name': 'Petasis-Ferrier Rearrangement',
  'confidence': 0.92,
  'entity_text': 'Petasis-Ferrier Rearrangement',
  'entity_type': 'reaction_family',
  'family_name': 'Petasis-Ferrier Rearrangement',
  'notes': 'Application page family anchor.',
  'page_label': 'p343'},
 {'canonical_name': 'C3-C19 Subtarget of (+)-Phorboxazole A',
  'confidence': 0.85,
  'entity_text': 'C3-C19 Subtarget of (+)-Phorboxazole A',
  'entity_type': 'target_molecule',
  'family_name': 'Petasis-Ferrier Rearrangement',
  'notes': 'Modified Petasis-Ferrier rearrangement delivered the cis-tetrahydropyran subtarget in phorboxazole studies.',
  'page_label': 'p343'},
 {'canonical_name': 'C22-C26 Subtarget of (+)-Phorboxazole A',
  'confidence': 0.85,
  'entity_text': 'C22-C26 Subtarget of (+)-Phorboxazole A',
  'entity_type': 'target_molecule',
  'family_name': 'Petasis-Ferrier Rearrangement',
  'notes': 'Fully substituted central tetrahydropyran subtarget assembled through a modified Petasis-Ferrier sequence.',
  'page_label': 'p343'},
 {'canonical_name': '(+)-Dactylolide',
  'confidence': 0.85,
  'entity_text': '(+)-Dactylolide',
  'entity_type': 'target_molecule',
  'family_name': 'Petasis-Ferrier Rearrangement',
  'notes': 'Macrocyclic natural product whose key cis-2,6-disubstituted tetrahydropyran was formed by Petasis-Ferrier rearrangement.',
  'page_label': 'p343'},
 {'canonical_name': '(+)-Zampanolide',
  'confidence': 0.83,
  'entity_text': '(+)-Zampanolide',
  'entity_type': 'target_molecule',
  'family_name': 'Petasis-Ferrier Rearrangement',
  'notes': 'Natural product study paired with dactylolide and relying on the same tetrahydropyran-forming rearrangement logic.',
  'page_label': 'p343'},
 {'canonical_name': 'Peterson Olefination',
  'confidence': 0.92,
  'entity_text': 'Peterson Olefination',
  'entity_type': 'reaction_family',
  'family_name': 'Peterson Olefination',
  'notes': 'Overview page family anchor for the Peterson olefination.',
  'page_label': 'p344'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'α-silyl carbanion + carbonyl compound',
  'entity_type': 'reactant_class',
  'family_name': 'Peterson Olefination',
  'notes': 'Canonical reactant pairing for Peterson olefination.',
  'page_label': 'p344'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'alkene from β-hydroxysilane elimination',
  'entity_type': 'product_class',
  'family_name': 'Peterson Olefination',
  'notes': 'Characteristic olefin product class of the Peterson reaction.',
  'page_label': 'p344'},
 {'canonical_name': 'Peterson Olefination',
  'confidence': 0.92,
  'entity_text': 'Peterson Olefination',
  'entity_type': 'reaction_family',
  'family_name': 'Peterson Olefination',
  'notes': 'Application page family anchor.',
  'page_label': 'p345'},
 {'canonical_name': '(+)-Maritimol',
  'confidence': 0.85,
  'entity_text': '(+)-Maritimol',
  'entity_type': 'target_molecule',
  'family_name': 'Peterson Olefination',
  'notes': 'Stemodane diterpenoid synthesized using a Peterson olefination to install a dinitrile precursor for ring annulation.',
  'page_label': 'p345'},
 {'canonical_name': 'Macrocyclic core of Roseophilin',
  'confidence': 0.84,
  'entity_text': 'Macrocyclic core of Roseophilin',
  'entity_type': 'target_molecule',
  'family_name': 'Peterson Olefination',
  'notes': 'Macrocyclic precursor obtained via Peterson olefination on a TMS-substituted imine derivative.',
  'page_label': 'p345'},
 {'canonical_name': '(+)-Brasilenyne',
  'confidence': 0.85,
  'entity_text': '(+)-Brasilenyne',
  'entity_type': 'target_molecule',
  'family_name': 'Peterson Olefination',
  'notes': 'Natural product target using Peterson olefination to install the key (Z)-enyne.',
  'page_label': 'p345'},
 {'canonical_name': '(-)-(Z)-Lancifolol',
  'confidence': 0.85,
  'entity_text': '(-)-(Z)-Lancifolol',
  'entity_type': 'target_molecule',
  'family_name': 'Peterson Olefination',
  'notes': 'Terpenoid target whose (Z)-alkene unit was successfully installed through a Z-selective Peterson olefination.',
  'page_label': 'p345'},
 {'canonical_name': 'Pfitzner-Moffatt Oxidation',
  'confidence': 0.92,
  'entity_text': 'Pfitzner-Moffatt Oxidation',
  'entity_type': 'reaction_family',
  'family_name': 'Pfitzner-Moffatt Oxidation',
  'notes': 'Overview page family anchor for the Pfitzner-Moffatt oxidation.',
  'page_label': 'p346'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'alcohol + activated DMSO/carbodiimide system',
  'entity_type': 'reactant_class',
  'family_name': 'Pfitzner-Moffatt Oxidation',
  'notes': 'Canonical input pattern for Pfitzner-Moffatt oxidation.',
  'page_label': 'p346'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'aldehyde or ketone',
  'entity_type': 'product_class',
  'family_name': 'Pfitzner-Moffatt Oxidation',
  'notes': 'Characteristic carbonyl products of the activated-DMSO oxidation.',
  'page_label': 'p346'},
 {'canonical_name': 'Pfitzner-Moffatt Oxidation',
  'confidence': 0.92,
  'entity_text': 'Pfitzner-Moffatt Oxidation',
  'entity_type': 'reaction_family',
  'family_name': 'Pfitzner-Moffatt Oxidation',
  'notes': 'Application page family anchor.',
  'page_label': 'p347'},
 {'canonical_name': 'Herbicidin B',
  'confidence': 0.85,
  'entity_text': 'Herbicidin B',
  'entity_type': 'target_molecule',
  'family_name': 'Pfitzner-Moffatt Oxidation',
  'notes': 'Nucleoside antibiotic synthesized using a Moffatt oxidation on a protected phenyl sugar derivative.',
  'page_label': 'p347'},
 {'canonical_name': '(+)-Paspalicine',
  'confidence': 0.85,
  'entity_text': '(+)-Paspalicine',
  'entity_type': 'target_molecule',
  'family_name': 'Pfitzner-Moffatt Oxidation',
  'notes': 'Indole diterpene target whose homolytic alcohol intermediate underwent Moffatt oxidation before Rh-catalyzed isomerization.',
  'page_label': 'p347'},
 {'canonical_name': '(+)-Citreoviral',
  'confidence': 0.85,
  'entity_text': '(+)-Citreoviral',
  'entity_type': 'target_molecule',
  'family_name': 'Pfitzner-Moffatt Oxidation',
  'notes': 'Hydroxy-substituted terpenoid assembled through a Moffatt oxidation/NaBH4 inversion sequence.',
  'page_label': 'p347'},
 {'canonical_name': '(-)-Pereniporin A',
  'confidence': 0.85,
  'entity_text': '(-)-Pereniporin A',
  'entity_type': 'target_molecule',
  'family_name': 'Pfitzner-Moffatt Oxidation',
  'notes': 'Drimane-type sesquiterpene prepared via oxidation of a primary alcohol to an aldehyde while preserving a β-hydroxy aldehyde.',
  'page_label': 'p347'},
 {'canonical_name': 'Pictet-Spengler Tetrahydroisoquinoline Synthesis',
  'confidence': 0.92,
  'entity_text': 'Pictet-Spengler Tetrahydroisoquinoline Synthesis',
  'entity_type': 'reaction_family',
  'family_name': 'Pictet-Spengler Tetrahydroisoquinoline Synthesis',
  'notes': 'Overview page family anchor for the Pictet-Spengler tetrahydroisoquinoline synthesis.',
  'page_label': 'p348'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'β-arylethylamine + carbonyl compound',
  'entity_type': 'reactant_class',
  'family_name': 'Pictet-Spengler Tetrahydroisoquinoline Synthesis',
  'notes': 'Canonical substrate pairing for the Pictet-Spengler tetrahydroisoquinoline synthesis.',
  'page_label': 'p348'},
 {'canonical_name': None,
  'confidence': 0.84,
  'entity_text': 'substituted tetrahydroisoquinoline',
  'entity_type': 'product_class',
  'family_name': 'Pictet-Spengler Tetrahydroisoquinoline Synthesis',
  'notes': 'Characteristic heterocycle product of Pictet-Spengler cyclization.',
  'page_label': 'p348'},
 {'canonical_name': 'Pictet-Spengler Tetrahydroisoquinoline Synthesis',
  'confidence': 0.92,
  'entity_text': 'Pictet-Spengler Tetrahydroisoquinoline Synthesis',
  'entity_type': 'reaction_family',
  'family_name': 'Pictet-Spengler Tetrahydroisoquinoline Synthesis',
  'notes': 'Application page family anchor.',
  'page_label': 'p349'},
 {'canonical_name': '(-)-Suaveoline',
  'confidence': 0.85,
  'entity_text': '(-)-Suaveoline',
  'entity_type': 'target_molecule',
  'family_name': 'Pictet-Spengler Tetrahydroisoquinoline Synthesis',
  'notes': 'Indole alkaloid prepared through a cis-selective Pictet-Spengler cyclization controlled by π-stacking with a TBDPS group.',
  'page_label': 'p349'},
 {'canonical_name': '(±)-Deoxyfrenolicin',
  'confidence': 0.85,
  'entity_text': '(±)-Deoxyfrenolicin',
  'entity_type': 'target_molecule',
  'family_name': 'Pictet-Spengler Tetrahydroisoquinoline Synthesis',
  'notes': 'Natural product accessed via an oxa-Pictet-Spengler reaction of a substituted naphthalene derivative.',
  'page_label': 'p349'},
 {'canonical_name': '(+)-Coccinine',
  'confidence': 0.85,
  'entity_text': '(+)-Coccinine',
  'entity_type': 'target_molecule',
  'family_name': 'Pictet-Spengler Tetrahydroisoquinoline Synthesis',
  'notes': 'Montanine-type alkaloid whose highly substituted precursor underwent Pictet-Spengler cyclization in aqueous formaldehyde and '
           'HCl.',
  'page_label': 'p349'},
 {'canonical_name': 'ABFGH Subunit of ET 743',
  'confidence': 0.85,
  'entity_text': 'ABFGH Subunit of ET 743',
  'entity_type': 'target_molecule',
  'family_name': 'Pictet-Spengler Tetrahydroisoquinoline Synthesis',
  'notes': 'Spirocyclic fragment of ET 743 formed through a Pictet-Spengler reaction between phenethylamine and a complex ketone '
           'substrate.',
  'page_label': 'p349'}]


def apply_frontmatter_batch40(db_path: str | Path) -> Dict[str, Any]:
    return apply_frontmatter_batch_generic(
        db_path=db_path,
        source_label=SOURCE_LABEL,
        version=FRONTMATTER_BATCH40_VERSION,
        latest_source_zip=LATEST_SOURCE_ZIP,
        batch_no=40,
        page_knowledge_seeds=PAGE_KNOWLEDGE_SEEDS,
        family_pattern_seeds=FAMILY_PATTERN_SEEDS,
        abbreviation_seeds=CURATED_BATCH40_ABBREVIATIONS,
        page_entity_seeds=PAGE_ENTITY_SEEDS,
    )
