from __future__ import annotations

from pathlib import Path
from typing import Any, Dict

from app.labint_frontmatter_batch_restore_utils import (
    apply_frontmatter_batch_generic,
    load_abbreviation_seeds,
    load_family_pattern_seeds,
    load_page_knowledge_seeds,
)

FRONTMATTER_BATCH18_VERSION = 'labint_frontmatter_batch18_v1_20260412'
SOURCE_LABEL = 'named_reactions_frontmatter_batch18'
LATEST_SOURCE_ZIP = 'backend_batch15_18_frontmatter_cumulative_patch_20260412.zip'

PAGE_KNOWLEDGE_SEEDS = load_page_knowledge_seeds(18, SOURCE_LABEL)
FAMILY_PATTERN_SEEDS = load_family_pattern_seeds(18, FRONTMATTER_BATCH18_VERSION)
BATCH18_SOURCE_PAGES = {'AIBN': 133,
 'BF3·Et2O': 133,
 'LAH': 133,
 'LDA': 128,
 'NIS': 129,
 'NaH': 128,
 'NaHMDS': 131,
 'Oxone': 130,
 'SmI2': 133,
 'TBAF': 125,
 'TMSCl': 126,
 'TiCl4': 124,
 'Yb(OTf)3': 127}
CURATED_BATCH18_ABBREVIATIONS = load_abbreviation_seeds(
    18,
    SOURCE_LABEL,
    source_pages=BATCH18_SOURCE_PAGES,
    default_note='batch18 frontmatter abbreviation seed',
)
PAGE_ENTITY_SEEDS = [{'canonical_name': 'Danheiser Cyclopentene Annulation',
  'confidence': 0.92,
  'entity_text': 'Danheiser Cyclopentene Annulation',
  'entity_type': 'reaction_family',
  'family_name': 'Danheiser Cyclopentene Annulation',
  'notes': 'Named annulation family overview.',
  'page_label': 'p124'},
 {'canonical_name': None,
  'confidence': 0.87,
  'entity_text': 'allylic carbocation',
  'entity_type': 'mechanistic_concept',
  'family_name': 'Danheiser Cyclopentene Annulation',
  'notes': 'Key cationic intermediate invoked after TiCl4 activation and allene addition.',
  'page_label': 'p124'},
 {'canonical_name': None,
  'confidence': 0.85,
  'entity_text': 'highly substituted cyclopentene',
  'entity_type': 'product_class',
  'family_name': 'Danheiser Cyclopentene Annulation',
  'notes': 'Canonical product class shown in the overview scheme.',
  'page_label': 'p124'},
 {'canonical_name': 'Danheiser Cyclopentene Annulation',
  'confidence': 0.92,
  'entity_text': 'Danheiser Cyclopentene Annulation',
  'entity_type': 'reaction_family',
  'family_name': 'Danheiser Cyclopentene Annulation',
  'notes': 'Application page family anchor.',
  'page_label': 'p125'},
 {'canonical_name': None,
  'confidence': 0.86,
  'entity_text': '(+)-Clavukerin',
  'entity_type': 'target_molecule',
  'family_name': 'Danheiser Cyclopentene Annulation',
  'notes': 'Natural-product target assembled from annulation-derived fused cyclopentene intermediates.',
  'page_label': 'p125'},
 {'canonical_name': None,
  'confidence': 0.85,
  'entity_text': 'bicyclic ketone',
  'entity_type': 'target_molecule',
  'family_name': 'Danheiser Cyclopentene Annulation',
  'notes': 'Representative annulation-derived bicyclic ketone product from the disilane variant.',
  'page_label': 'p125'},
 {'canonical_name': "Danishefsky's Diene Cycloaddition",
  'confidence': 0.92,
  'entity_text': "Danishefsky's Diene Cycloaddition",
  'entity_type': 'reaction_family',
  'family_name': "Danishefsky's Diene Cycloaddition",
  'notes': 'Named heterodiene cycloaddition family overview.',
  'page_label': 'p126'},
 {'canonical_name': None,
  'confidence': 0.87,
  'entity_text': 'Mukaiyama aldol pathway',
  'entity_type': 'mechanistic_concept',
  'family_name': "Danishefsky's Diene Cycloaddition",
  'notes': 'Stepwise Lewis-acid-assisted pathway discussed alongside the concerted Diels–Alder manifold.',
  'page_label': 'p126'},
 {'canonical_name': None,
  'confidence': 0.85,
  'entity_text': 'dihydropyrone',
  'entity_type': 'product_class',
  'family_name': "Danishefsky's Diene Cycloaddition",
  'notes': 'Characteristic oxygenated heterocycle formed from aldehyde partners.',
  'page_label': 'p126'},
 {'canonical_name': "Danishefsky's Diene Cycloaddition",
  'confidence': 0.92,
  'entity_text': "Danishefsky's Diene Cycloaddition",
  'entity_type': 'reaction_family',
  'family_name': "Danishefsky's Diene Cycloaddition",
  'notes': 'Application page family anchor.',
  'page_label': 'p127'},
 {'canonical_name': None,
  'confidence': 0.86,
  'entity_text': 'Tubipofuran',
  'entity_type': 'target_molecule',
  'family_name': "Danishefsky's Diene Cycloaddition",
  'notes': 'Marine furanosesquiterpenoid target accessed through a regioselective quinone cycloaddition.',
  'page_label': 'p127'},
 {'canonical_name': None,
  'confidence': 0.85,
  'entity_text': '(-)-Phyllanthine',
  'entity_type': 'target_molecule',
  'family_name': "Danishefsky's Diene Cycloaddition",
  'notes': 'Securinega alkaloid target prepared through Yb(OTf)3-promoted Danishefsky diene annulation with a cyclic imine partner.',
  'page_label': 'p127'},
 {'canonical_name': 'Darzens Glycidic Ester Condensation',
  'confidence': 0.92,
  'entity_text': 'Darzens Glycidic Ester Condensation',
  'entity_type': 'reaction_family',
  'family_name': 'Darzens Glycidic Ester Condensation',
  'notes': 'Named epoxide-forming condensation family overview.',
  'page_label': 'p128'},
 {'canonical_name': None,
  'confidence': 0.87,
  'entity_text': 'halohydrin intermediate',
  'entity_type': 'intermediate_class',
  'family_name': 'Darzens Glycidic Ester Condensation',
  'notes': 'Aldol-type adduct that undergoes intramolecular displacement to the epoxide.',
  'page_label': 'p128'},
 {'canonical_name': None,
  'confidence': 0.85,
  'entity_text': 'glycidic ester',
  'entity_type': 'product_class',
  'family_name': 'Darzens Glycidic Ester Condensation',
  'notes': 'Canonical epoxide-containing product class of the Darzens condensation.',
  'page_label': 'p128'},
 {'canonical_name': 'Darzens Glycidic Ester Condensation',
  'confidence': 0.92,
  'entity_text': 'Darzens Glycidic Ester Condensation',
  'entity_type': 'reaction_family',
  'family_name': 'Darzens Glycidic Ester Condensation',
  'notes': 'Application page family anchor.',
  'page_label': 'p129'},
 {'canonical_name': None,
  'confidence': 0.86,
  'entity_text': '(-)-Coriolin',
  'entity_type': 'target_molecule',
  'family_name': 'Darzens Glycidic Ester Condensation',
  'notes': 'Spiro-epoxide natural product target prepared through a stereocontrolled Darzens-type sequence.',
  'page_label': 'p129'},
 {'canonical_name': None,
  'confidence': 0.85,
  'entity_text': 'Diltiazem',
  'entity_type': 'target_molecule',
  'family_name': 'Darzens Glycidic Ester Condensation',
  'notes': 'Medicinally relevant target reached through an auxiliary-controlled asymmetric Darzens condensation.',
  'page_label': 'p129'},
 {'canonical_name': "Davis' Oxaziridine Oxidations",
  'confidence': 0.92,
  'entity_text': "Davis' Oxaziridine Oxidations",
  'entity_type': 'reaction_family',
  'family_name': "Davis' Oxaziridine Oxidations",
  'notes': 'Named oxaziridine oxygen-transfer family overview.',
  'page_label': 'p130'},
 {'canonical_name': None,
  'confidence': 0.87,
  'entity_text': 'oxaziridine',
  'entity_type': 'reactant_class',
  'family_name': "Davis' Oxaziridine Oxidations",
  'notes': 'Three-membered N-O heterocycle oxygen-transfer reagent family highlighted on the page.',
  'page_label': 'p130'},
 {'canonical_name': None,
  'confidence': 0.85,
  'entity_text': 'alpha-hydroxylated carbonyl compound',
  'entity_type': 'product_class',
  'family_name': "Davis' Oxaziridine Oxidations",
  'notes': 'Canonical product class arising from enolate oxygenation.',
  'page_label': 'p130'},
 {'canonical_name': "Davis' Oxaziridine Oxidations",
  'confidence': 0.92,
  'entity_text': "Davis' Oxaziridine Oxidations",
  'entity_type': 'reaction_family',
  'family_name': "Davis' Oxaziridine Oxidations",
  'notes': 'Application page family anchor.',
  'page_label': 'p131'},
 {'canonical_name': None,
  'confidence': 0.86,
  'entity_text': 'Epothilone B',
  'entity_type': 'target_molecule',
  'family_name': "Davis' Oxaziridine Oxidations",
  'notes': 'Macrocycle target whose alpha-hydroxyl stereochemistry was set with a Davis oxaziridine.',
  'page_label': 'p131'},
 {'canonical_name': None,
  'confidence': 0.85,
  'entity_text': '(-)-Fumiquinazoline A & B',
  'entity_type': 'target_molecule',
  'family_name': "Davis' Oxaziridine Oxidations",
  'notes': 'Complex alkaloid targets assembled using oxaziridine-mediated oxygenation of an indole-derived intermediate.',
  'page_label': 'p131'},
 {'canonical_name': 'De Mayo Cycloaddition',
  'confidence': 0.92,
  'entity_text': 'De Mayo Cycloaddition',
  'entity_type': 'reaction_family',
  'family_name': 'De Mayo Cycloaddition',
  'notes': 'Named photochemical enone-alkene [2+2] family overview.',
  'page_label': 'p132'},
 {'canonical_name': None,
  'confidence': 0.87,
  'entity_text': 'triplet exciplex',
  'entity_type': 'mechanistic_concept',
  'family_name': 'De Mayo Cycloaddition',
  'notes': 'Triplet-state encounter complex invoked before 1,4-biradical formation.',
  'page_label': 'p132'},
 {'canonical_name': None,
  'confidence': 0.85,
  'entity_text': 'substituted cyclobutane',
  'entity_type': 'product_class',
  'family_name': 'De Mayo Cycloaddition',
  'notes': 'Canonical direct product class of the enone-alkene [2+2] photocycloaddition.',
  'page_label': 'p132'},
 {'canonical_name': 'De Mayo Cycloaddition',
  'confidence': 0.92,
  'entity_text': 'De Mayo Cycloaddition',
  'entity_type': 'reaction_family',
  'family_name': 'De Mayo Cycloaddition',
  'notes': 'Application page family anchor.',
  'page_label': 'p133'},
 {'canonical_name': None,
  'confidence': 0.86,
  'entity_text': 'Ingenol',
  'entity_type': 'target_molecule',
  'family_name': 'De Mayo Cycloaddition',
  'notes': 'Diterpenoid target assembled through intramolecular enone-olefin [2+2] photocycloaddition-fragmentation chemistry.',
  'page_label': 'p133'},
 {'canonical_name': None,
  'confidence': 0.85,
  'entity_text': '(+)-Alismol',
  'entity_type': 'target_molecule',
  'family_name': 'De Mayo Cycloaddition',
  'notes': 'Naturally occurring guaiane target prepared from an initial [2+2] photocycloadduct followed by fragmentation and radical '
           'elaboration.',
  'page_label': 'p133'}]


def apply_frontmatter_batch18(db_path: str | Path) -> Dict[str, Any]:
    return apply_frontmatter_batch_generic(
        db_path=db_path,
        source_label=SOURCE_LABEL,
        version=FRONTMATTER_BATCH18_VERSION,
        latest_source_zip=LATEST_SOURCE_ZIP,
        batch_no=18,
        page_knowledge_seeds=PAGE_KNOWLEDGE_SEEDS,
        family_pattern_seeds=FAMILY_PATTERN_SEEDS,
        abbreviation_seeds=CURATED_BATCH18_ABBREVIATIONS,
        page_entity_seeds=PAGE_ENTITY_SEEDS,
    )


if __name__ == '__main__':
    from pprint import pprint
    pprint(apply_frontmatter_batch18(Path(__file__).resolve().parent / 'labint.db'))
